### ISSUE TITLE
Problem with pihole and DNS

### ISSUE THREAD

**Issue by barcik75** [home-assistant/supervisor#1537]
**Home Assistant release with the issue:** 0.106.0

**Operating environment (HassOS/Generic):** Generic Raspberry Pi3

**Supervisor logs:**

**Description of problem:**

I am a new HA user. Yesterday I installed on Raspberry Pi 3. I installed the system manually on VM, not as Hass.io.
At the same time, the pi-hole stands on the same Raspberry. Today I started to configure HA and by the way I noticed problems with the operation of the entire local network. All references to DNS placed on this machine are rejected when HA is running. When HA is turned off, everything returns to normal.
I searched the community and answers here on GitHub regarding DNS operations, but all concerned Hass.io installation, not manual. How can I force hass to run with my DNS not rigidly assigned? However, I want to have control over what DNS is used in my network.
If I have reported the problem in the wrong place, please let me know where I should report it.
Thank you in advance.

`Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 109, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/config_entry_oauth2_flow.py", line 270, in async_step_discovery
    return await self.async_step_pick_implementation()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/config_entry_oauth2_flow.py", line 202, in async_step_pick_implementati
on
    implementations = await async_get_implementations(self.hass, self.DOMAIN)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/config_entry_oauth2_flow.py", line 315, in async_get_implementations
    implementation = await get_impl(hass, domain)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/cloud/account_link.py", line 29, in async_provide_implementation
    services = await _get_services(hass)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/cloud/account_link.py", line 76, in _get_services
    services = await account_link.async_fetch_available_services(hass.data[DOMAIN])
  File "/srv/homeassistant/lib/python3.7/site-packages/hass_nabucasa/account_link.py", line 120, in async_fetch_available_services
    resp = await cloud.client.websession.post(f"{cloud.account_link_url}/services")
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host account-link.nabucasa.com:443 ssl:None [Temporary failure in name resolution]`

**Comment by frenck** [comment]
This is general happens when you don't have assigned your machine a static IP and external DNS servers. Please don't confuse that with a DHCP reservation in your router.

**Comment by barcik75** [comment]
My /etc/dhcpcd.conf file:
`interface wlan0
        static ip_address=192.168.1.150/24
        static routers=192.168.1.1
        static domain_name_servers=127.0.0.1`
No, itsn't problem

**Comment by pvizeli** [comment]
Yep, DNS 127.0.0.1 will not work. The system have many containers with a own localhost and network. If you no tell all that containers that the DNS is the localhost, they look on his own virtual localhost which did not run any DNS server.

**Comment by pvizeli** [comment]
Is solve with > 210 because of new features that make it near impossible to block external DNS if the internal dns is wrong setup
