### ISSUE TITLE
Error after update to 205

### ISSUE THREAD

**Issue by Krocko** [home-assistant/supervisor#1549]
**Home Assistant release with the issue:**

0.106.2
**Operating environment (HassOS/Generic):**

Supervisor 205
**Supervisor logs:**

**Description of problem:**

I got the following error after update to 205
```
20-02-29 17:55:16 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin!
20-02-29 17:55:16 INFO (MainThread) [supervisor.audio] Start Audio plugin
20-02-29 17:55:16 INFO (SyncWorker_6) [supervisor.docker.interface] Clean hassio_audio application
20-02-29 17:55:25 ERROR (SyncWorker_6) [supervisor.docker] Can't start hassio_audio: 500 Server Error: Internal Server Error ("Bind mount failed: '/dev/snd' does not exists")
20-02-29 17:55:25 ERROR (MainThread) [supervisor.audio] Can't start Audio plugin
20-02-29 17:55:25 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Tasks._watchdog_audio_docker() done, defined at /usr/src/supervisor/supervisor/tasks.py:244> exception=AudioError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/tasks.py", line 252, in _watchdog_audio_docker
    await self.sys_audio.start()
  File "/usr/src/supervisor/supervisor/audio.py", line 168, in start
    raise AudioError() from None
supervisor.exceptions.AudioError
```

**Comment by pvizeli** [comment]
What kind of platform is that?

**Comment by Krocko** [comment]
I use it on an synology nas with docker.
