### ISSUE TITLE
Supervisor stopped working - bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by Ka0o0** [home-assistant/supervisor#1586]
**Home Assistant release with the issue:**
0.106.3

**Operating environment (HassOS/Generic):**
HassOS
Raspberry Pi 2 B
Supervisor Version: 209

**Supervisor logs:**

```
Mar 13 13:25:21 homeassistant systemd[1]: Starting HassOS supervisor...
Mar 13 13:25:21 homeassistant docker[31209]: hassos_supervisor
Mar 13 13:25:21 homeassistant systemd[1]: Started HassOS supervisor.
Mar 13 13:25:26 homeassistant hassos-supervisor[31218]: [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
Mar 13 13:25:27 homeassistant hassos-supervisor[31218]: [s6-init] ensuring user provided files have correct perms...exited 0.
Mar 13 13:25:27 homeassistant hassos-supervisor[31218]: [fix-attrs.d] applying ownership & permissions fixes...
Mar 13 13:25:27 homeassistant hassos-supervisor[31218]: [fix-attrs.d] done.
Mar 13 13:25:27 homeassistant hassos-supervisor[31218]: [cont-init.d] executing container initialization scripts...
Mar 13 13:25:27 homeassistant hassos-supervisor[31218]: [cont-init.d] udev.sh: executing...
Mar 13 13:25:27 homeassistant hassos-supervisor[31218]: [13:25:27] INFO: Update udev informations
Mar 13 13:25:28 homeassistant hassos-supervisor[31218]: [cont-init.d] udev.sh: exited 0.
Mar 13 13:25:28 homeassistant hassos-supervisor[31218]: [cont-init.d] done.
Mar 13 13:25:28 homeassistant hassos-supervisor[31218]: [services.d] starting services
Mar 13 13:25:28 homeassistant hassos-supervisor[31218]: [services.d] done.
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]: Traceback (most recent call last):
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:     "__main__", mod_spec)
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:     exec(code, run_globals)
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "/usr/src/supervisor/supervisor/__main__.py", line 7, in <module>
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:     from supervisor import bootstrap
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "/usr/src/supervisor/supervisor/bootstrap.py", line 10, in <module>
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:     from .addons import AddonManager
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "<frozen importlib._bootstrap_external>", line 857, in get_code
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]:   File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
Mar 13 13:25:29 homeassistant hassos-supervisor[31218]: ValueError: bad marshal data (unknown type code)
Mar 13 13:25:30 homeassistant hassos-supervisor[31218]: [cont-finish.d] executing container finish scripts...
Mar 13 13:25:30 homeassistant hassos-supervisor[31218]: [cont-finish.d] done.
Mar 13 13:25:30 homeassistant hassos-supervisor[31218]: [s6-finish] waiting for services.
Mar 13 13:25:30 homeassistant hassos-supervisor[31218]: [s6-finish] sending all processes the TERM signal.
```

**Description of problem:**

Hi,
after rebooting my raspberry pi I ended up in a state where the operating system starts but somehow supervisor won't start. In the logs it can be seen that `ValueError: bad marshal data (unknown type code)` is thrown.
It's similar like #1415 but I'm not even able to call any hass command as I get

```
Get http://supervisor/host/info: dial tcp 172.30.32.2:80: connect: no route to host
```

**Comment by Ka0o0** [comment]
Also, it is very difficult to debug. Whenever I try to log into the docker container it gets terminated because of the error so quickly before I can do something. I already tried stopping the `hassos-supervisor.service` but it is still stopping after erroring.

**Comment by pvizeli** [comment]
> ValueError: bad marshal data (unknown type code)

I saw this only with corrupt images/container. A `hassio su repair` fix that but only if the supervisor is not affected by that issue what it is now. the only way to fix that is to clean up the supervisor image + container a create it new with the latest tag.

**Comment by Ka0o0** [comment]
The thing is that this happened for five new installations. I now replaced my SD card (SandDisk Ultra) with a newer one (SanDisk Extreme). It seems stable now since a couple of days so I guess this must have been the root cause.

**Comment by Ka0o0** [comment]
Just an update on this issue. It has been a couple of weeks now and a few HA-updates since then and my Rpi works flawlessly. I can recommend anyone who is experiencing similar issues to try a new SD-Card.
