### ISSUE TITLE
Node-red adding extra nodes

### ISSUE THREAD

**Issue by Kouwe-sudo** [home-assistant/supervisor#1622]
**Home Assistant release with the issue:**
<
- Frontend -> Developer tools -> Info
- Or use this command: hass --version
Home Assistant 0.107.7
-->

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**

I use NODE-RED as on 'add-on' but I'm not able to add the extra nodes for RFXCOM. This is not a problem of Node-red itself because I'm able to install it on another Pi with 'Buster' and 'Domoticz'. This is the log I get: Since I'm using Hassio I'm not able to fix it myself (or can I?)

-----------------------------------------------------------
2020-04-02T15:27:31.152Z Install : node-red-contrib-rfxcom 2.10.0

2020-04-02T15:27:32.314Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-rfxcom@2.10.0
2020-04-02T15:27:48.439Z [err] npm
2020-04-02T15:27:48.440Z [err]  WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
2020-04-02T15:28:00.390Z [out] 
2020-04-02T15:28:00.390Z [out] > @serialport/bindings@8.0.7 install /config/node-red/node_modules/@serialport/bindings
2020-04-02T15:28:00.390Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-04-02T15:28:00.390Z [out] 
2020-04-02T15:28:02.578Z [err] prebuild-install
2020-04-02T15:28:02.578Z [err]  WARN install No prebuilt binaries found (target=12.15.0 runtime=node arch=arm libc=musl platform=linux)
2020-04-02T15:28:05.573Z [err] gyp
2020-04-02T15:28:05.574Z [err]  
2020-04-02T15:28:05.574Z [err] ERR! build error 
2020-04-02T15:28:05.577Z [err] gyp
2020-04-02T15:28:05.578Z [err]  ERR! stack
2020-04-02T15:28:05.578Z [err]  Error: not found: make
2020-04-02T15:28:05.578Z [err] gyp ERR! 
2020-04-02T15:28:05.579Z [err] stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-04-02T15:28:05.579Z [err] gyp
2020-04-02T15:28:05.579Z [err]  ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-04-02T15:28:05.579Z [err] gyp ERR!
2020-04-02T15:28:05.579Z [err]  stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-04-02T15:28:05.579Z [err] gyp ERR!
2020-04-02T15:28:05.580Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-04-02T15:28:05.580Z [err] gyp ERR!
2020-04-02T15:28:05.580Z [err]  stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-04-02T15:28:05.580Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-04-02T15:28:05.581Z [err] gyp ERR! stack
2020-04-02T15:28:05.581Z [err]      at FSReqCallback.oncomplete (fs.js:158:21)
2020-04-02T15:28:05.582Z [err] gyp
2020-04-02T15:28:05.582Z [err]  ERR! System Linux 4.19.106-v7
2020-04-02T15:28:05.582Z [err] gyp ERR!
2020-04-02T15:28:05.582Z [err]  command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-04-02T15:28:05.583Z [err] gyp ERR!
2020-04-02T15:28:05.583Z [err]  cwd /config/node-red/node_modules/@serialport/bindings
2020-04-02T15:28:05.583Z [err] gyp 
2020-04-02T15:28:05.583Z [err] ERR! node -v
2020-04-02T15:28:05.583Z [err]  v12.15.0
2020-04-02T15:28:05.583Z [err] gyp 
2020-04-02T15:28:05.583Z [err] ERR! node-gyp -v v5.0.5
2020-04-02T15:28:05.584Z [err] gyp ERR! 
2020-04-02T15:28:05.584Z [err] not ok 
2020-04-02T15:28:06.645Z [err] npm 
2020-04-02T15:28:06.645Z [err] ERR! code ELIFECYCLE
2020-04-02T15:28:06.645Z [err] npm ERR!
2020-04-02T15:28:06.646Z [err]  errno 1
2020-04-02T15:28:06.656Z [err] npm 
2020-04-02T15:28:06.657Z [err] ERR! @serialport/bindings@8.0.7 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2020-04-02T15:28:06.657Z [err] npm ERR!
2020-04-02T15:28:06.657Z [err]  Exit status 1
2020-04-02T15:28:06.657Z [err] npm
2020-04-02T15:28:06.657Z [err]  ERR!
2020-04-02T15:28:06.658Z [err]  
2020-04-02T15:28:06.658Z [err] npm 
2020-04-02T15:28:06.658Z [err] ERR! Failed at the @serialport/bindings@8.0.7 install script.
2020-04-02T15:28:06.658Z [err] npm
2020-04-02T15:28:06.659Z [err]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-02T15:28:06.742Z [err] 
2020-04-02T15:28:06.743Z [err] npm ERR! A complete log of this run can be found in:
2020-04-02T15:28:06.743Z [err] npm
2020-04-02T15:28:06.743Z [err]  ERR!     /root/.npm/_logs/2020-04-02T15_28_06_713Z-debug.log
2020-04-02T15:28:06.778Z rc=1

**Comment by pvizeli** [comment]
Open a issue in the repository of that node red add-on
