### ISSUE TITLE
Addon installation broke the supervisor

### ISSUE THREAD

**Issue by lirlocker** [home-assistant/supervisor#1665]
**Home Assistant release with the issue:**
0.108.6

**Operating environment (HassOS/Generic):**
Using supervisor for generic Linux on RaspberryPi 3.

**Supervisor logs:**
```
20-04-19 13:04:32 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 157, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 61, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/supervisor.py", line 82, in info
    ATTR_NAME: addon.name,
  File "/usr/src/supervisor/supervisor/addons/model.py", line 117, in name
    return self.data[ATTR_NAME]
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 91, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'core_duckdns'

```
**Description of problem:**
After installing the DuckDNS add-on through the web interface I can't enter the supervisor tab and I get an error message in the logs as pasted above.

It seems like the add-on is somehow partially installed and this throws an error in the supervisor.

**Comment by lirlocker** [comment]
Deleting the directory "/data/addons/data/core_duckdns" and restarting the Pi seems to have fixed the issue, but it would be nice if there will be a bugfix for that. :)

(I also accidentally deleted the core/duckdns directory, which made it disappear from the addons list, but hey, at least my supervisor works now...)

**Comment by pvizeli** [comment]
> Deleting the directory "/data/addons/data/core_duckdns"

That can't solve anything. The restart fix it. It look like there was an error on delete on the add-on which end up in a unknown system state. I try to reproduce it but without the origin error, I can't know what was happens.

**Comment by pvizeli** [comment]
Nope, everything working. I'm sorry but I can help to fix the root of the issue without have the error message of it. That what you get was just the result of that error which we not known now.
