### ISSUE TITLE
Startup is not fully completed and prohibits restarting HA

### ISSUE THREAD

**Issue by YannikBe** [home-assistant/supervisor#1699]
**Home Assistant release with the issue:**
Home Assistant 0.109.4

**Operating environment (HassOS/Generic):**
HassOS 3.13 on a RPi4

**Supervisor logs:**

- Restarting Home Assistant and waiting for ten minutes until the task times out:
```
20-05-05 17:07:53 INFO (MainThread) [supervisor.homeassistant] Home Assistant pip installation done
20-05-05 17:10:13 INFO (MainThread) [supervisor.host.info] Update local host information
20-05-05 17:10:13 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-05-05 17:10:14 INFO (MainThread) [supervisor.host.services] Update service information
20-05-05 17:10:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-05-05 17:10:14 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-05-05 17:10:14 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-05-05 17:10:14 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-05-05 17:17:55 WARNING (MainThread) [supervisor.homeassistant] Don't wait anymore of Home Assistant startup!
20-05-05 17:17:55 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<process_lock.<locals>.wrap_api() done, defined at /usr/src/supervisor/supervisor/utils/__init__.py:22> exception=HomeAssistantUpdateError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 31, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant.py", line 362, in update
    raise HomeAssistantUpdateError()
supervisor.exceptions.HomeAssistantUpdateError
```
After this error has occured, restarting is possible without any issues again.

- Trying to restart before the abovementioned task has timed out yet:
```
20-05-05 18:56:53 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-05-05 18:56:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-05-05 18:56:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-05-05 18:56:56 INFO (MainThread) [supervisor.store] Load add-ons from store: 66 all - 0 new - 0 remove
20-05-05 18:57:14 INFO (SyncWorker_4) [supervisor.docker.interface] Restart homeassistant/raspberrypi4-homeassistant
20-05-05 19:00:23 ERROR (MainThread) [supervisor.utils] Can't execute restart while a task is in progress
```

**Description of problem:**

After restarting Home Assistant, it is not possible to restart Home Assistant again for exactly ten minutes. After ten minutes of waiting, an asynchronous task is not waited for anymore. Only after that another restart is possible.

**Comment by pvizeli** [comment]
Look like you HA config is corrupt
