### ISSUE TITLE
New docker installation error

### ISSUE THREAD

**Issue by zonak** [home-assistant/supervisor#1725]
**Home Assistant release with the issue:**

amd64-hassio-supervisor with version 223

amd64-hassio-cli tag 25.
amd64-hassio-dns tag 9.
amd64-hassio-multicast tag 2.
amd64-hassio-audio tag 14.

**Operating environment (HassOS/Generic):**

Docker version 18.09.8

**Supervisor logs:**

**Description of problem:**

A clean new installation with docker always stops with an error at the same stage:

```
20-05-16 18:31:19 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-05-16 18:31:24 INFO (MainThread) [__main__] Stopping Supervisor
20-05-16 18:31:24 INFO (MainThread) [supervisor.api] Stop API on 172.30.32.2
20-05-16 18:31:24 INFO (MainThread) [supervisor.hwmon] Stop Supervisor hardware monitor
20-05-16 18:31:24 INFO (MainThread) [supervisor.misc.forwarder] Stop DNS forwarding
20-05-16 18:31:24 INFO (MainThread) [supervisor.core] Supervisor is down
20-05-16 18:31:24 INFO (MainThread) [__main__] Close Supervisor
20-05-16 18:37:09 INFO (SyncWorker_19) [supervisor.docker.interface] Stop homeassistant application
20-05-16 18:38:41 INFO (SyncWorker_19) [supervisor.docker.interface] Clean homeassistant application
20-05-16 18:38:42 ERROR (SyncWorker_19) [concurrent.futures] exception calling callback for <Future at 0x7f29d14a4bd0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.7/asyncio/futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1265, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 635, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 639, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 668, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
20-05-16 18:38:42 ERROR (MainThread) [asyncio] Task was destroyed but it is pending!
task: <Task pending coro=<process_lock.<locals>.wrap_api() running at /usr/src/supervisor/supervisor/utils/__init__.py:31> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.7/asyncio/futures.py:351, <TaskWakeupMethWrapper object at 0x7f29d14a4190>()]>>
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by zonak** [comment]
I am trying to install this on Fedora CoreOS and by replicating [supervised-installer](https://github.com/home-assistant/supervised-installer) I was able to get further.

Now getting (after successfully starting the supervisor):

```
20-05-17 01:16:50 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with CoreDNS plugin!
20-05-17 01:16:50 ERROR (MainThread) [supervisor.tasks] CoreDNS plugin is in fails state / Reset config
```

I guess I'll have to keep at it...
