### ISSUE TITLE
Can't load supervisor

### ISSUE THREAD

**Issue by noelesther** [home-assistant/supervisor#1762]
Home Assistant 0.110.3

RB3+

**Supervisor logs:**
[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] udev.sh: executing... 

[00:27:20] INFO: Update udev informations

[cont-init.d] udev.sh: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/usr/src/supervisor/supervisor/__main__.py", line 7, in <module>

    from supervisor import bootstrap

  File "/usr/src/supervisor/supervisor/bootstrap.py", line 10, in <module>

    from .addons import AddonManager

  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 9, in <module>

    from ..coresys import CoreSys, CoreSysAttributes

  File "/usr/src/supervisor/supervisor/coresys.py", line 7, in <module>

    import aiohttp

  File "/usr/local/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>

    from .client import BaseConnector as BaseConnector

  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 30, in <module>

    from yarl import URL

ImportError: cannot import name 'URL' from 'yarl' (/usr/local/lib/python3.7/site-packages/yarl/__init__.py)

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] udev.sh: executing... 

[00:27:33] INFO: Update udev informations

[cont-init.d] udev.sh: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/usr/src/supervisor/supervisor/__main__.py", line 7, in <module>

    from supervisor import bootstrap

  File "/usr/src/supervisor/supervisor/bootstrap.py", line 10, in <module>

    from .addons import AddonManager

  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 9, in <module>

    from ..coresys import CoreSys, CoreSysAttributes

  File "/usr/src/supervisor/supervisor/coresys.py", line 7, in <module>

    import aiohttp

  File "/usr/local/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>

    from .client import BaseConnector as BaseConnector

  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 30, in <module>

    from yarl import URL

ImportError: cannot import name 'URL' from 'yarl' (/usr/local/lib/python3.7/site-packages/yarl/__init__.py)

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] udev.sh: executing... 

[00:27:47] INFO: Update udev informations

[cont-init.d] udev.sh: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/usr/src/supervisor/supervisor/__main__.py", line 7, in <module>

    from supervisor import bootstrap

  File "/usr/src/supervisor/supervisor/bootstrap.py", line 10, in <module>

    from .addons import AddonManager

  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 9, in <module>

    from ..coresys import CoreSys, CoreSysAttributes

  File "/usr/src/supervisor/supervisor/coresys.py", line 7, in <module>

    import aiohttp

  File "/usr/local/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>

    from .client import BaseConnector as BaseConnector

  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 30, in <module>

    from yarl import URL

ImportError: cannot import name 'URL' from 'yarl' (/usr/local/lib/python3.7/site-packages/yarl/__init__.py)

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

**Description of problem:**

Suddenly Can't use Supervisor. 

I didn't do anything. but It was broken.

**Comment by pvizeli** [comment]
That is a corrupt docker container because of a corrupt file system. We fix that on Home Assistant OS 4.10 and latest start script which is able to recover the Supervisor image/container.
