### ISSUE TITLE
High CPU & mem usage

### ISSUE THREAD

**Issue by ibBogdan** [home-assistant/supervisor#1808]
**Home Assistant release with the issue:**
0.112.0

**Operating environment (HassOS/Generic):**
Ubuntu

**Supervisor logs:**
20-07-02 09:48:57 INFO (SyncWorker_11) [supervisor.docker.interface] Start homeassistant/intel-nuc-homeassistant
20-07-02 09:49:02 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-07-02 09:49:22 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-07-02 09:49:22 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' start 1 add-ons
20-07-02 09:49:22 INFO (SyncWorker_5) [supervisor.docker.interface] Clean addon_cebe7a76_hassio_google_drive_backup application
20-07-02 09:49:23 INFO (SyncWorker_5) [supervisor.docker.addon] Start Docker add-on sabeechen/hassio-google-drive-backup-amd64 with version 0.100.0
20-07-02 09:49:23 INFO (MainThread) [supervisor.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
20-07-02 09:49:23 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
20-07-02 09:49:23 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-07-02 09:49:23 INFO (MainThread) [supervisor.api.security] /snapshots/73acca6f/info access from cebe7a76_hassio_google_drive_backup
20-07-02 09:49:23 INFO (MainThread) [supervisor.api.security] /snapshots/a6261e32/info access from cebe7a76_hassio_google_drive_backup
20-07-02 09:49:23 INFO (MainThread) [supervisor.api.security] /snapshots/a885b964/info access from cebe7a76_hassio_google_drive_backup
20-07-02 09:49:23 INFO (MainThread) [supervisor.api.security] /snapshots/63506f9d/info access from cebe7a76_hassio_google_drive_backup
20-07-02 09:49:28 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
20-07-02 09:49:28 INFO (MainThread) [supervisor.misc.hwmon] Started Supervisor hardware monitor
20-07-02 09:49:28 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-07-02 09:49:28 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-02 09:49:28 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-02 09:49:28 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-02 09:49:28 INFO (MainThread) [supervisor.host.services] Update service information
20-07-02 09:49:28 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-02 09:49:28 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-07-02 09:49:28 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-07-02 09:49:28 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information

**Description of problem:**
i`ve restarted my nuc today and notice a spike in internet trafic.. went further and noticed this:
![image](https://user-images.githubusercontent.com/12171894/86345419-2f079900-bc64-11ea-9960-e92317ed7802.png)

any idea what this might be?

also getting this at restart:
2020-07-02 13:10:20 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_stop[L]>) at /usr/src/homeassistant/homeassistant/core.py:680
TypeError: stop() takes 1 positional argument but 2 were given

2020-07-02 13:16:12 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_stop[L]>) at /usr/src/homeassistant/h>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 692, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 401, in async_run_job
    self.async_add_job(target, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 331, in async_add_job
    task = self.loop.create_task(target(*args))
TypeError: stop() takes 1 positional argument but 2 were given

later edit:

[s6-finish] waiting for services.
2020-07-02 13:57:15 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_stop[L]>) at /usr/src/homeassistant/homeassistant/core.py:680
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 692, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 401, in async_run_job
    self.async_add_job(target, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 331, in async_add_job
    task = self.loop.create_task(target(*args))
TypeError: stop() takes 1 positional argument but 2 were given
Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...879542+03:00>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:81
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 103, in state_change_listener
    event.data.get("new_state"),
  File "/usr/src/homeassistant/homeassistant/core.py", line 401, in async_run_job
    self.async_add_job(target, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 336, in async_add_job
    None, target, *args
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 755, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...880216+03:00>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:81
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 103, in state_change_listener
    event.data.get("new_state"),
  File "/usr/src/homeassistant/homeassistant/core.py", line 401, in async_run_job
    self.async_add_job(target, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 336, in async_add_job
    None, target, *args
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 755, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...880793+03:00>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:81
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 103, in state_change_listener
    event.data.get("new_state"),
  File "/usr/src/homeassistant/homeassistant/core.py", line 401, in async_run_job
    self.async_add_job(target, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 336, in async_add_job
    None, target, *args
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 755, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[13:57:23] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by frenck** [comment]
Hi there @ibBogdan,

Thanks for opening up an issue.

Your process list and logs show an issue with the Home Assistant Core, not the Supervisor. Please report your issue with the Home Assistant Core project: <https://github.com/home-assistant/core/issues>

Thanks 👍
