### ISSUE TITLE
error python

### ISSUE THREAD

**Issue by riddik14** [home-assistant/supervisor#1919]
Filter...
Lines
100
Actions  
      
[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] udev.sh: executing... 

[16:41:22] INFO: Update udev information

[cont-init.d] udev.sh: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "/usr/src/supervisor/supervisor/__main__.py", line 7, in <module>

    from supervisor import bootstrap

  File "/usr/src/supervisor/supervisor/bootstrap.py", line 13, in <module>

    from .addons import AddonManager

  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 9, in <module>

    from ..coresys import CoreSys, CoreSysAttributes

  File "/usr/src/supervisor/supervisor/coresys.py", line 10, in <module>

    from .config import CoreConfig

  File "/usr/src/supervisor/supervisor/config.py", line 23, in <module>

    from .utils.dt import parse_datetime

  File "/usr/src/supervisor/supervisor/utils/dt.py", line 9, in <module>

    import pytz

  File "/usr/local/lib/python3.8/site-packages/pytz/__init__.py", line 19, in <module>

    from pytz.lazy import LazyDict, LazyList, LazySet  # noqa

ValueError: source code string cannot contain null bytes

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] udev.sh: executing... 

[16:41:38] INFO: Update udev information

[cont-init.d] udev.sh: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "/usr/src/supervisor/supervisor/__main__.py", line 7, in <module>

    from supervisor import bootstrap

  File "/usr/src/supervisor/supervisor/bootstrap.py", line 13, in <module>

    from .addons import AddonManager

  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 9, in <module>

    from ..coresys import CoreSys, CoreSysAttributes

  File "/usr/src/supervisor/supervisor/coresys.py", line 10, in <module>

    from .config import CoreConfig

  File "/usr/src/supervisor/supervisor/config.py", line 23, in <module>

    from .utils.dt import parse_datetime

  File "/usr/src/supervisor/supervisor/utils/dt.py", line 9, in <module>

    import pytz

  File "/usr/local/lib/python3.8/site-packages/pytz/__init__.py", line 19, in <module>

    from pytz.lazy import LazyDict, LazyList, LazySet  # noqa

ValueError: source code string cannot contain null bytes

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] udev.sh: executing... 

[16:41:54] INFO: Update udev information

[cont-init.d] udev.sh: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "/usr/src/supervisor/supervisor/__main__.py", line 7, in <module>

    from supervisor import bootstrap

  File "/usr/src/supervisor/supervisor/bootstrap.py", line 13, in <module>

    from .addons import AddonManager

  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 9, in <module>

    from ..coresys import CoreSys, CoreSysAttributes

  File "/usr/src/supervisor/supervisor/coresys.py", line 10, in <module>

    from .config import CoreConfig

  File "/usr/src/supervisor/supervisor/config.py", line 23, in <module>

    from .utils.dt import parse_datetime

  File "/usr/src/supervisor/supervisor/utils/dt.py", line 9, in <module>

    import pytz

  File "/usr/local/lib/python3.8/site-packages/pytz/__init__.py", line 19, in <module>

    from pytz.lazy import LazyDict, LazyList, LazySet  # noqa

ValueError: source code string cannot contain null bytes

**Comment by balloob** [comment]
Please fill in the issue template when creating issues.
