### ISSUE TITLE
Repeating supervisor.auth error

### ISSUE THREAD

**Issue by Didgeridrew** [home-assistant/supervisor#1941]
**Home Assistant release with the issue:**

Home Assistant 0.114.2

Frontend version: 20200811.0

**Operating environment (HassOS/Generic):**

HassOS 4.12

**Supervisor logs:**

Supervisor v. 234

> 20-08-17 20:10:03 ERROR (MainThread) [supervisor.auth] Can't request auth on Home Assistant!
> 20-08-17 20:10:03 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
> 20-08-17 20:16:04 INFO (MainThread) [supervisor.auth] Auth request from core_mosquitto for mqtt1
> 20-08-17 20:16:05 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
> 20-08-17 20:16:06 ERROR (MainThread) [supervisor.auth] Can't request auth on Home Assistant!
> 20-08-17 20:16:15 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
> 20-08-17 20:22:07 INFO (MainThread) [supervisor.auth] Auth request from core_mosquitto for mqtt1
> 20-08-17 20:22:08 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
> 20-08-17 20:22:10 ERROR (MainThread) [supervisor.auth] Can't request auth on Home Assistant!
> 20-08-17 20:22:17 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token

This repeats every 6 minutes or so.

**Description of problem:**

For the past two days, about every six minutes, I've received the following notification:

> Login attempt failed
> Login attempt or request with invalid authentication from 172.30.32.2" 

**Core log:**

> 2020-08-17 16:09:34 ERROR (Recorder) [homeassistant.components.recorder] Error executing query: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed
> [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
> [parameters: ('state_changed', '{}', 'LOCAL', '2020-08-17 20:09:33.050638', '2020-08-17 20:09:33.062057', '90c92cbde0c511eaa1a07bc226cdf389', None, None)]
> (Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
> 2020-08-17 16:09:34 ERROR (Recorder) [homeassistant.components.recorder] Error saving events: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed
> [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
> [parameters: ('state_changed', '{}', 'LOCAL', '2020-08-17 20:09:33.050638', '2020-08-17 20:09:33.062057', '90c92cbde0c511eaa1a07bc226cdf389', None, None)]
> (Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 433, in _commit_event_session_or_retry
>     self._commit_event_session()
>   File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 484, in _commit_event_session
>     self.event_session.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
>     self.transaction.commit()
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 502, in commit
>     self._assert_active(prepared_ok=True)
>   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
>     raise sa_exc.InvalidRequestError(
> sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed
> [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
> [parameters: ('state_changed', '{}', 'LOCAL', '2020-08-17 20:09:33.050638', '2020-08-17 20:09:33.062057', '90c92cbde0c511eaa1a07bc226cdf389', None, None)]
> (Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)

**The Host log** 

> [  356.556618] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
> [  356.565580] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
> [  672.552170] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
> [  672.565094] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
> [  988.544857] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
> [  988.562490] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
> [ 1304.544263] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
> [ 1304.553336] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
> [ 1351.224853] udevd[189]: starting version 3.2.9
> [ 1351.297000] udevd[190]: starting eudev-3.2.9
> [ 1620.547941] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
> [ 1620.565816] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
> [ 1936.568927] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
> [ 1936.580599] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled

The host has always been on a wired connection and has never had a wlan connection setup.

**Configuration log **

This error as well as a couple others from the same source file, but different line numbers. Each error lists hundreds of occurences.

> ## Log Details (ERROR)
> 
> Logger: homeassistant.components.recorder
> Source: components/recorder/__init__.py:377
> Integration: Recorder ([documentation](https://www.home-assistant.io/integrations/recorder), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+recorder%22))
> First occurred: 4:06:05 PM (688 occurrences)
> Last logged: 4:37:36 PM
> 
> * Error adding event: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('state_changed', '{}', 'LOCAL', '2020-08-17 20:37:23.532568', '2020-08-17 20:37:23.543702', '74787667e0c911eab9c84fce572a50f6', None, None)] (Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
> * Error adding event: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('state_changed', '{}', 'LOCAL', '2020-08-17 20:37:24.615765', '2020-08-17 20:37:24.632246', '751dbf2de0c911ea9d55450df60a9ec6', None, None)] (Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
> * Error adding event: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('state_changed', '{}', 'LOCAL', '2020-08-17 20:37:27.132622', '2020-08-17 20:37:27.147902', '769dc526e0c911eabb2dbbc23fe361b2', None, None)] (Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
> * Error adding event: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('state_changed', '{}', 'LOCAL', '2020-08-17 20:37:33.057714', '2020-08-17 20:37:33.070036', '7a25e989e0c911ea9c6add2501c22dc6', None, None)] (Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
> * Error adding event: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('state_changed', '{}', 'LOCAL', '2020-08-17 20:37:36.833483', '2020-08-17 20:37:36.844874', '7c6602c7e0c911ea85f94bce4821af64', None, None)] (Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 377, in run self.event_session.flush() File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2523, in flush self._flush(objects) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2618, in _flush flush_context.transaction = transaction = self.begin( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 953, in begin self.transaction = self.transaction._begin(nested=nested) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 317, in _begin

**Comment by pvizeli** [comment]
`20-08-17 20:22:10 ERROR (MainThread) [supervisor.auth] Can't request auth on Home Assistant!`

Look like your home assistant core is broken and did not allow us to renew the token. Remove your SQL database and restart
