### ISSUE TITLE
Communication problems

### ISSUE THREAD

**Issue by drthanwho** [home-assistant/supervisor#2108]
**Home Assistant release with the issue:** 0.115.0

**Operating environment (HassOS/Generic):** HassOS 5.1 
Running HassOS 5.1 (64bit) on SSD on Rpi4 4GB with latest supervisor 245

**Supervisor logs:** Unable to load supervisor panel to access the logs

**Description of problem:**
I have been running HassOS 5.1 from SSD without any major problems (or at least with no problems relating to this in my opinion). The only other major problem I had which I'm not sure if it relates but figured I would mention is that my database got corrupted a few weeks back so I did the mistake of just restarting (instead of deleting the database first), So upon restart, the system completely hang and after a very long time it booted but gave _"read-only database"_ errors and the only way I could fix it was to plug the SSD on another machine and manually delete the .db file from there. 

This time, the last time I checked the system everything was working OK. And now I realised that something was off.
Going through my setup, apart from not being able to access the supervisor panel, this is what else is not working at all. 

- deconz is down
- Speedtest integration
- no history graphs are loading
- SSH sensors are also not working
- CPU is at around 65% (I assume since the issue occured)
- ESPHOME isn't accessible but nodes are still running

at the related closed issue that got out of hand @ pvizeli mentioned to use the help portal to see what's going on. This is also something I'm unable to access
![image](https://user-images.githubusercontent.com/22405505/95245615-a45ea900-0813-11eb-9f67-2b46e7f088d5.png)

The only thing I was able to do was turn off the power and let it boot up again. It took a lot longer than usual but it booted. I can see that now the supervisor updated itself (as I had 245 installed and now I see it's saying 246)

Since it rebooted I unfortunately have no logs to show. Is there a way to save logs like there is with snapshots so I can share them next time this happens? Also I did have _share diagnostics_ enabled but I don't know if that would have been useful or not. 

Let me know if there is any more info I could provide

**Comment by ludeeus** [comment]
Are you sure _anything_ was working at all?
The HA UI could have been browser cache.

Since none of your add-ons (or supervisor) were working, it sounds like you had network issues on the host.
Is this connected with ethernet? did you look at the laps on the ethernet port?

**Comment by ludeeus** [comment]
How long did you give it, before rebooting?
The pages will be unavailable during the SU updates, which on a pi can take some time

**Comment by drthanwho** [comment]
I noticed the issue last night (say 11pm) at which point I started writing this issue here. But I had to work so I never submitted it. 
And this morning I woke up to a message from a family member saying the found the floodlight outside turned on (which apparently happened during the night) and they couldn't connect to HA to turn it off. 

And even then I only rebooted it 2 hours ago, so we are talking 12+ hours here. Perhaps the supervisor updated after the hard reboot, which would explain how long it took to but up (usually 1 - 2mins but took about 10)

**Comment by ludeeus** [comment]
So HA was unreachable as well?
Since you said you could watch camera streams I thought that it was up.

**Comment by drthanwho** [comment]
HA was up to begin with. Everytime I had this type of issue HA works and it's Supervisor that is down and thus impossible to reload HA. 
But in this case it seems that at some point in the night HA also ended up going down. I left it with HA being up and woke up with nothing being reachable.

**Comment by pvizeli** [comment]
If the help website is also down (like you show in screenshot) it's the hole docker backend which have issue

**Comment by drthanwho** [comment]
I moved to an SSH to avoid having corruption issues like I used to. I assume there isn't a way to check this? Just that if it happens again I should format the drive from scratch?

**Comment by drthanwho** [comment]
So now it seems it happened again. CPU is 80-90%. Most things are down, however I find it strange how HA instance is up but the observer is down. I managed to get the logs from HA though this time.

I just removed "Received message for unregistered webhook..." logs cos I get too many of those. Eveything else I've left in. 

```yaml
2020-10-18 00:45:36 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f989e41f0>, 'Connect timed out. (connect timeout=5.0)')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-18 01:49:31 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.543773361248] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2020-10-18 02:02:02 WARNING (Thread-9) [pychromecast.socket_client] [Κουζίνα display(192.168.1.21):8009] Heartbeat timeout, resetting connection
2020-10-18 04:12:00 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`homeassistant`.`states`, CONSTRAINT `states_ibfk_2` FOREIGN KEY (`old_state_id`) REFERENCES `states` (`state_id`))')
[SQL: DELETE FROM states WHERE states.last_updated < %s]
[parameters: (datetime.datetime(2020, 10, 8, 15, 29, 59, tzinfo=<UTC>),)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-10-18 04:12:00 WARNING (Recorder) [homeassistant.components.recorder.purge] Error purging history: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`homeassistant`.`states`, CONSTRAINT `states_ibfk_2` FOREIGN KEY (`old_state_id`) REFERENCES `states` (`state_id`))')
[SQL: DELETE FROM states WHERE states.last_updated < %s]
[parameters: (datetime.datetime(2020, 10, 8, 15, 29, 59, tzinfo=<UTC>),)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-10-18 04:45:50 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-18 04:45:50 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-18 04:46:16 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Heartbeat timeout, resetting connection
2020-10-18 06:08:19 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f989e41f0>, 'Connect timed out. (connect timeout=5.0)')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-18 08:18:47 WARNING (MainThread) [homeassistant.components.automation.couch_lamp_off] Couch Lamp Off: Already running
2020-10-18 08:20:20 WARNING (MainThread) [homeassistant.components.automation.couch_lamp_off] Couch Lamp Off: Already running
2020-10-18 09:16:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.seventeentrack_package_lt111200941nl is taking over 10 seconds
2020-10-18 10:45:51 ERROR (MainThread) [custom_components.hacs.repository.plugin.iantrich.untappd-card] GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-18 10:45:51 ERROR (MainThread) [custom_components.hacs.factory] iantrich/untappd-card - GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-18 11:57:32 WARNING (SyncWorker_48) [homeassistant.components.telegram_bot] Disallowed targets: [280755619], using default: 627190871
2020-10-18 15:43:02 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from d54c36455.access.telenet.be (84.195.100.85) (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36)
2020-10-18 16:32:15 WARNING (SyncWorker_59) [homeassistant.components.telegram_bot] Disallowed targets: [280755619], using default: 627190871
2020-10-18 16:33:12 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-18 16:33:12 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-18 16:33:12 ERROR (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error reading from socket.
2020-10-18 16:33:12 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error communicating with socket, resetting connection
2020-10-18 17:13:32 ERROR (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error reading from socket.
2020-10-18 17:13:32 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error communicating with socket, resetting connection
2020-10-18 17:13:32 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-18 17:13:32 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-18 17:13:35 WARNING (SyncWorker_2) [homeassistant.components.telegram_bot] Disallowed targets: [280755619], using default: 627190871
2020-10-18 17:13:47 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-18 17:13:47 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-18 17:13:47 ERROR (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error reading from socket.
2020-10-18 17:13:47 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error communicating with socket, resetting connection
2020-10-18 17:13:56 WARNING (Thread-9) [pychromecast.socket_client] [Κουζίνα display(192.168.1.21):8009] Heartbeat timeout, resetting connection
2020-10-18 18:06:41 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-18 18:06:41 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-18 18:06:41 ERROR (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error reading from socket.
2020-10-18 18:06:41 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error communicating with socket, resetting connection
2020-10-18 20:11:54 ERROR (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error reading from socket.
2020-10-18 20:11:54 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error communicating with socket, resetting connection
2020-10-18 20:11:54 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-18 20:11:54 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-18 20:12:04 WARNING (Thread-9) [pychromecast.socket_client] [Κουζίνα display(192.168.1.21):8009] Heartbeat timeout, resetting connection
2020-10-18 20:12:24 ERROR (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Failed to connect to service Chromecast-84131d0d67c934225fe12f3b11e02846._googlecast._tcp.local., retrying in 5.0s
2020-10-18 20:12:24 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Failed to connect to service Google-Cast-Group-d2c2d5bd846d4ce1b067e1bf9698d047._googlecast._tcp.local., retrying in 5.0s
2020-10-18 20:51:49 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from ppp-94-66-223-248.home.otenet.gr (94.66.223.248) (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36)
2020-10-18 20:51:49 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from ppp-94-66-223-248.home.otenet.gr (94.66.223.248) (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36)
2020-10-18 20:51:49 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from ppp-94-66-223-248.home.otenet.gr (94.66.223.248) (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36)
2020-10-18 22:21:00 ERROR (MainThread) [homeassistant.components.upnp] Timeout fetching UPNP IGD data
2020-10-18 23:49:51 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f989e41f0>, 'Connect timed out. (connect timeout=5.0)')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-19 00:05:49 ERROR (MainThread) [custom_components.hacs.repository.plugin.iantrich.untappd-card] GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-19 00:05:49 ERROR (MainThread) [custom_components.hacs.factory] iantrich/untappd-card - GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-19 01:01:34 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f989e41f0>, 'Connect timed out. (connect timeout=5.0)')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-19 02:42:05 ERROR (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error reading from socket.
2020-10-19 02:42:05 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error communicating with socket, resetting connection
2020-10-19 02:42:05 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-19 02:42:05 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-19 03:06:09 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.545754782640] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2020-10-19 03:50:17 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-19 03:50:17 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-19 03:50:48 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Heartbeat timeout, resetting connection
2020-10-19 04:12:00 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`homeassistant`.`states`, CONSTRAINT `states_ibfk_2` FOREIGN KEY (`old_state_id`) REFERENCES `states` (`state_id`))')
[SQL: DELETE FROM states WHERE states.last_updated < %s]
[parameters: (datetime.datetime(2020, 10, 8, 15, 29, 59, tzinfo=<UTC>),)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-10-19 04:12:00 WARNING (Recorder) [homeassistant.components.recorder.purge] Error purging history: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`homeassistant`.`states`, CONSTRAINT `states_ibfk_2` FOREIGN KEY (`old_state_id`) REFERENCES `states` (`state_id`))')
[SQL: DELETE FROM states WHERE states.last_updated < %s]
[parameters: (datetime.datetime(2020, 10, 8, 15, 29, 59, tzinfo=<UTC>),)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-10-19 04:45:55 WARNING (Thread-9) [pychromecast.socket_client] [Κουζίνα display(192.168.1.21):8009] Heartbeat timeout, resetting connection
2020-10-19 07:07:12 ERROR (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error reading from socket.
2020-10-19 07:07:12 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Error communicating with socket, resetting connection
2020-10-19 07:07:12 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-19 07:07:12 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-19 08:04:51 WARNING (MainThread) [homeassistant.components.esphome] Error getting initial data for sonoff_basic_2.local: Timeout while waiting for API response!
2020-10-19 08:06:08 WARNING (SyncWorker_26) [homeassistant.components.telegram_bot] Disallowed targets: [280755619], using default: 627190871
2020-10-19 08:06:31 WARNING (MainThread) [homeassistant.components.automation.couch_lamp_off] Couch Lamp Off: Already running
2020-10-19 08:14:53 WARNING (MainThread) [homeassistant.components.automation.couch_lamp_off] Couch Lamp Off: Already running
2020-10-19 13:25:52 ERROR (MainThread) [custom_components.hacs.repository.plugin.iantrich.untappd-card] GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-19 13:25:52 ERROR (MainThread) [custom_components.hacs.factory] iantrich/untappd-card - GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-19 15:48:48 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f989e41f0>, 'Connect timed out. (connect timeout=5.0)')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-19 16:48:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1285, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service notify/mobile_app_sm_a500fu
2020-10-19 16:48:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1285, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service notify/mobile_app_bv4000pro
2020-10-20 02:45:50 ERROR (MainThread) [custom_components.hacs.repository.plugin.iantrich.untappd-card] GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-20 02:45:50 ERROR (MainThread) [custom_components.hacs.factory] iantrich/untappd-card - GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-20 03:22:47 WARNING (Thread-9) [pychromecast.socket_client] [Κουζίνα display(192.168.1.21):8009] Heartbeat timeout, resetting connection
2020-10-20 03:26:07 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f989e41f0>, 'Connect timed out. (connect timeout=5.0)')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-20 04:12:00 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`homeassistant`.`states`, CONSTRAINT `states_ibfk_2` FOREIGN KEY (`old_state_id`) REFERENCES `states` (`state_id`))')
[SQL: DELETE FROM states WHERE states.last_updated < %s]
[parameters: (datetime.datetime(2020, 10, 8, 15, 29, 59, tzinfo=<UTC>),)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-10-20 04:12:00 WARNING (Recorder) [homeassistant.components.recorder.purge] Error purging history: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`homeassistant`.`states`, CONSTRAINT `states_ibfk_2` FOREIGN KEY (`old_state_id`) REFERENCES `states` (`state_id`))')
[SQL: DELETE FROM states WHERE states.last_updated < %s]
[parameters: (datetime.datetime(2020, 10, 8, 15, 29, 59, tzinfo=<UTC>),)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-10-20 04:51:28 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-20 04:51:28 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-20 04:51:53 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Heartbeat timeout, resetting connection
2020-10-20 08:05:53 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2020-10-20 13:48:37 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.543776647536] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2020-10-20 16:05:49 ERROR (MainThread) [custom_components.hacs.repository.plugin.iantrich.untappd-card] GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-20 16:05:49 ERROR (MainThread) [custom_components.hacs.factory] iantrich/untappd-card - GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-20 17:32:41 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f989e41f0>, 'Connect timed out. (connect timeout=5.0)')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-20 23:37:13 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f989e41f0>, 'Connect timed out. (connect timeout=5.0)')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-21 00:36:13 WARNING (MainThread) [homeassistant.components.automation.eisodos_cam_on_kouzina_display] Eisodos Cam on Kouzina Display: Already running
2020-10-21 02:25:53 WARNING (Thread-9) [pychromecast.socket_client] [Κουζίνα display(192.168.1.21):8009] Heartbeat timeout, resetting connection
2020-10-21 03:05:34 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error reading from socket.
2020-10-21 03:05:34 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.1.20):32196] Error communicating with socket, resetting connection
2020-10-21 03:06:00 WARNING (Thread-7) [pychromecast.socket_client] [TV(192.168.1.20):8009] Heartbeat timeout, resetting connection
2020-10-21 04:12:00 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`homeassistant`.`states`, CONSTRAINT `states_ibfk_2` FOREIGN KEY (`old_state_id`) REFERENCES `states` (`state_id`))')
[SQL: DELETE FROM states WHERE states.last_updated < %s]
[parameters: (datetime.datetime(2020, 10, 8, 15, 29, 59, tzinfo=<UTC>),)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-10-21 04:12:00 WARNING (Recorder) [homeassistant.components.recorder.purge] Error purging history: (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`homeassistant`.`states`, CONSTRAINT `states_ibfk_2` FOREIGN KEY (`old_state_id`) REFERENCES `states` (`state_id`))')
[SQL: DELETE FROM states WHERE states.last_updated < %s]
[parameters: (datetime.datetime(2020, 10, 8, 15, 29, 59, tzinfo=<UTC>),)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-10-21 05:25:51 ERROR (MainThread) [custom_components.hacs.repository.plugin.iantrich.untappd-card] GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-21 05:25:51 ERROR (MainThread) [custom_components.hacs.factory] iantrich/untappd-card - GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card
2020-10-21 08:27:42 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection.548046310752] Disconnected: Did not receive auth message within 10 seconds
2020-10-21 08:27:42 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection.547852522160] Disconnected: Did not receive auth message within 10 seconds
2020-10-21 08:31:59 WARNING (MainThread) [homeassistant.components.automation.couch_lamp_off] Couch Lamp Off: Already running
2020-10-21 08:43:10 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.545763900192] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2020-10-21 08:43:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.545760360288] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2020-10-21 10:23:36 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f902682e0>: Failed to establish a new connection: [Errno -3] Try again')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-21 10:23:41 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f00a48e50>: Failed to establish a new connection: [Errno -3] Try again')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-21 10:23:46 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f10d556a0>: Failed to establish a new connection: [Errno -3] Try again')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-21 10:23:51 ERROR (updater) [telegram.ext.updater] Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d228dc0>: Failed to establish a new connection: [Errno -3] Try again'))
2020-10-21 10:23:57 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f111b9340>: Failed to establish a new connection: [Errno -3] Try again')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-21 10:24:02 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8e027820>: Failed to establish a new connection: [Errno -3] Try again')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-21 10:24:07 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d96be20>: Failed to establish a new connection: [Errno -3] Try again')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-21 10:24:11 ERROR (MainThread) [homeassistant.components.google_assistant.http] Could not contact https://homegraph.googleapis.com/v1/devices:reportStateAndNotification
2020-10-21 10:24:11 ERROR (MainThread) [homeassistant.components.google_assistant.http] Could not contact https://homegraph.googleapis.com/v1/devices:reportStateAndNotification
2020-10-21 10:24:11 ERROR (MainThread) [homeassistant.components.google_assistant.http] Could not contact https://homegraph.googleapis.com/v1/devices:reportStateAndNotification
2020-10-21 10:24:12 ERROR (updater) [telegram.ext.updater] Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7e9bbae610>: Failed to establish a new connection: [Errno -3] Try again'))
2020-10-21 10:24:19 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9a1d0190>: Failed to establish a new connection: [Errno -3] Try again')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-21 10:24:24 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7e9b75fc10>: Failed to establish a new connection: [Errno -3] Try again')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
2020-10-21 10:24:29 WARNING (updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d96f910>: Failed to establish a new connection: [Errno -3] Try again')': /bot927965807:AAE8ATPOX1lhlODpRxPYPJFKfTAYkNLOhXA/getUpdates
```

**Comment by drthanwho** [comment]
Handled after the 2020.12.0 updates onwards 👍
