### ISSUE TITLE
Standard/default addon repository doesn't load. Community repo does work however.

### ISSUE THREAD

**Issue by kwaazaar** [home-assistant/supervisor#2262]
## The problem
Default addons don't show. Only community addons show. Seems to be a problem loading the repository.
This is a standard installation running on a RP4.

## Environment

- Home Assistant Core release with the issue: HassOS 4.16
- Last working Home Assistant Core release (if known): ?
- Operating environment (OS/Container/Supervised/Core): Supervisor 2020.11.0
- Integration causing this issue: -
- Link to integration documentation on our website: -

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs
~~~
20-11-17 20:32:16 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
20-11-17 20:33:41 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/home-assistant/hassio-addons repository
20-11-17 20:33:43 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/e724ce20/repository.json: [Errno 2] No such file or directory: '/data/addons/git/e724ce20/repository.json'
20-11-17 20:33:43 ERROR (MainThread) [supervisor.store] https://github.com/home-assistant/hassio-addons is not a valid add-on repository. 
20-11-17 20:33:43 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/home-assistant/hassio-addons
20-11-17 20:33:43 INFO (MainThread) [supervisor.store] Loading add-ons from store: 45 all - 0 new - 0 remove
20-11-17 20:33:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-11-17 20:33:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-11-17 20:33:56 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-850' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:64> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 67, in update
    return await self.git.pull()
  File "/usr/src/supervisor/supervisor/store/git.py", line 102, in pull
    branch = self.repo.active_branch.name
  File "/usr/local/lib/python3.8/site-packages/git/repo/base.py", line 718, in active_branch
    return self.head.reference
  File "/usr/local/lib/python3.8/site-packages/git/refs/symbolic.py", line 270, in _get_reference
    sha, target_ref_path = self._get_ref_info(self.repo, self.path)
  File "/usr/local/lib/python3.8/site-packages/git/refs/symbolic.py", line 181, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/usr/local/lib/python3.8/site-packages/git/refs/symbolic.py", line 150, in _get_ref_info_helper
    assert(len(tokens) != 0)
AssertionError
20-11-17 20:33:56 INFO (MainThread) [supervisor.store] Loading add-ons from store: 45 all - 0 new - 0 remove
~~~

```txt

```

**Comment by pvizeli** [comment]
Fix with 2020.11.1
