### ISSUE TITLE
Cannot set network ip address from supervisor 

### ISSUE THREAD

**Issue by katonage** [home-assistant/supervisor#2278]
### Describe the issue
From home assistant supervisor menu nothing happens when tapping on change ip address. 

My understanding from the log that it can not under what is in its config data. 

I have rpi4 upgraded everything to the latest today. beta Channel. 

At the first setup (32bit SD card image) I added network config file to have wifi and DHCP. Later I configured from the supervisor fix ip (a month ago). It works fine, no symptoms. 
Now I can't access that option again. 

### Steps to reproduce

1. 
2. ...
3. ...

### Enviroment details

- **Operating System:**: 4.17
- **Supervisor version:**: xxx
- **Home Assistant version**: 0.118.2

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

20-11-21 05:43:37 INFO (MainThread) [supervisor.host.network] Updating local network information
20-11-21 05:43:39 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
20-11-21 05:43:39 INFO (MainThread) [supervisor.host] Host information reload completed
20-11-21 05:51:48 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-11-21 06:21:55 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-11-21 06:34:13 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-11-21 06:49:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-11-21 06:49:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/bestlibre/hassio-addons/ repository
20-11-21 06:49:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-11-21 06:49:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
20-11-21 06:49:55 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6fc777c6/snapcastserver/config.json: required key not provided @ data['arch']. Got None
20-11-21 06:49:55 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6fc777c6/mopidy_alpine/config.json: required key not provided @ data['arch']. Got None
20-11-21 06:49:55 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6fc777c6/nextcloud/config.json: required key not provided @ data['arch']. Got None
20-11-21 06:49:55 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6fc777c6/kanboard/config.json: required key not provided @ data['arch']. Got None
20-11-21 06:49:56 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6fc777c6/snapcastserver/config.json: required key not provided @ data['arch']. Got None
20-11-21 06:49:56 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6fc777c6/mopidy_alpine/config.json: required key not provided @ data['arch']. Got None
20-11-21 06:49:56 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6fc777c6/nextcloud/config.json: required key not provided @ data['arch']. Got None
20-11-21 06:49:56 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/6fc777c6/kanboard/config.json: required key not provided @ data['arch']. Got None
20-11-21 06:49:56 INFO (MainThread) [supervisor.store] Loading add-ons from store: 83 all - 0 new - 0 remove
20-11-21 06:49:56 INFO (MainThread) [supervisor.store] Loading add-ons from store: 83 all - 0 new - 0 remove
20-11-21 06:50:02 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json
20-11-21 06:51:55 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-11-21 07:21:56 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-11-21 07:34:15 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-11-21 07:50:19 INFO (MainThread) [supervisor.host.info] Updating local host information
20-11-21 07:50:20 INFO (MainThread) [supervisor.host.services] Updating service information
20-11-21 07:50:20 INFO (MainThread) [supervisor.host.network] Updating local network information
20-11-21 07:50:22 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
20-11-21 07:50:22 INFO (MainThread) [supervisor.host] Host information reload completed
20-11-21 07:52:00 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-11-21 08:22:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-11-21 08:34:16 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-11-21 08:37:43 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 132, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 194, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 60, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/network.py", line 156, in info
    for interface in self.sys_host.network.interfaces
  File "/usr/src/supervisor/supervisor/host/network.py", line 54, in interfaces
    interfaces.append(Interface.from_dbus_interface(inet))
  File "/usr/src/supervisor/supervisor/host/network.py", line 291, in from_dbus_interface
    Interface._map_nm_wifi(inet),
  File "/usr/src/supervisor/supervisor/host/network.py", line 348, in _map_nm_wifi
    WifiMode(inet.settings.wireless.mode),
  File "/usr/local/lib/python3.8/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 617, in __new__
    raise ve_exc
ValueError: None is not a valid WifiMode

</details>

**Comment by katonage** [comment]
After updating, everything is fine. Thank you!
