### ISSUE TITLE
Supervisor won't update from 0.116.4 to 0.118.2

### ISSUE THREAD

**Issue by xvolte** [home-assistant/supervisor#2282]
### Describe the issue
My supervisor don't want to update when i click the "update" button from version 0.116.4 to version 0.118.2
HassOS is up to date.

### Steps to reproduce

1. i go in the supervisor dashboard and click on "update"

### Enviroment details

- **Operating System:**: HassOS 4.17
- **Supervisor version:**: 2020.11.0
- **Home Assistant version**: Home Assistant 0.116.4

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
20-11-21 11:17:56 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 0.118.2
20-11-21 11:17:56 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image homeassistant/raspberrypi3-homeassistant:0.116.4 to homeassistant/raspberrypi3-homeassistant:0.118.2
20-11-21 11:17:56 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image homeassistant/raspberrypi3-homeassistant with tag 0.118.2.
20-11-21 11:21:32 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.118.2 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi3-homeassistant:0.118.2: No such image: homeassistant/raspberrypi3-homeassistant:0.118.2").
20-11-21 11:21:32 INFO (SyncWorker_3) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 17.3 GiB
20-11-21 11:21:32 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed
20-11-21 11:21:32 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-10157' coro=<process_lock.<locals>.wrap_api() done, defined at /usr/src/supervisor/supervisor/utils/__init__.py:23> exception=HomeAssistantUpdateError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 217, in update
    raise HomeAssistantUpdateError()
supervisor.exceptions.HomeAssistantUpdateError
```
![image](https://user-images.githubusercontent.com/21142611/99876190-7089e800-2bf5-11eb-9408-d41bac0a5a75.png)

</details>

**Comment by ludeeus** [comment]
Run `ha su repair`

**Comment by xvolte** [comment]
This command worked :) thanks a lot !
any idea what went wrong ?
And what does this command do that was not able to do the regular "update" button ?

Thanks in advance,

**Comment by ludeeus** [comment]
Not really, some issue with docker on your installation.
The command clears out old stuff and rebuild the env.

**Comment by xvolte** [comment]
OK thanks a lot for the insights!
