### ISSUE TITLE
Installation in unhealthy state - ConnectivityCheckEnabled

### ISSUE THREAD

**Issue by EmmanuelLM** [home-assistant/supervisor#2330]
**Systems:**
- Odroid-XU4
- OS: DietPi v6.33.3 (based on Debian 9)
- Supervisor: 2020.12.2 (stable channel)
- Home-Assistant: 0.118.4
- All running on docker 19.03.13
- Connected via ethernet

**Info**

System Health

Home Assistant Core Integration

version: 0.118.4
installation_type: Home Assistant Supervised
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.14.180+
arch: armv7l
timezone: Europe/London

Home Assistant Cloud

logged_in: true
subscription_expiration: December 16, 2020, 12:00 AM
relayer_connected: true
remote_enabled: false
remote_connected: false
alexa_enabled: false
google_enabled: true
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Hass.io

host_os: Debian GNU/Linux 9 (stretch)
update_channel: stable
supervisor_version: 2020.12.2
docker_version: 19.03.13
disk_total: 28.1 GB
disk_used: 14.6 GB
healthy: failed to load: Unhealthy
supported: failed to load: Unsupported
supervisor_api: ok
version_api: ok
installed_addons: Node-RED (7.2.11), Let's Encrypt (4.11.0), Mosquitto broker (5.1), ESPHome (1.15.3), MariaDB (2.2.1), InfluxDB (3.7.9), Samba share (9.3.0), Traccar (0.9.2), Grafana (5.3.6), phpMyAdmin (0.1.4), NGINX Home Assistant SSL proxy (3.0.1), File editor (5.2.0), Zigbee2mqtt (1.16.1), TasmoAdmin (0.13.1)

Lovelace

dashboards: 2
mode: storage
views: 11
resources: 2

**Problem**

Installation was carried out with the convenience script install.sh

Apart from the 'Unsupported OS', everything was running fine.

Today, the Supervisor started throwing out the following error:
"20-12-03 14:24:13 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-374' coro=<HostManager.reload() done, defined at /usr/src/supervisor/supervisor/host/__init__.py:90> exception=KeyError('ConnectivityCheckEnabled')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/host/__init__.py", line 99, in reload
    await self.network.update()
  File "/usr/src/supervisor/supervisor/host/network.py", line 107, in update
    await self.check_connectivity()
  File "/usr/src/supervisor/supervisor/host/network.py", line 76, in check_connectivity
    if not self.sys_dbus.network.connectivity_enabled:
  File "/usr/src/supervisor/supervisor/dbus/network/__init__.py", line 58, in connectivity_enabled
    return self.properties[DBUS_ATTR_CONNECTION_ENABLED]
KeyError: 'ConnectivityCheckEnabled'"

I checked that Network-Manager was enabled, re-run the install.sh script without any issues.
I tried to manually set the IP via the Home-Assistant web interface and got a Error 500.

I am not 100% sure where else to look. If I understand the error correctly, the system indicates that it is not connected (to the internet?).

**Comment by EmmanuelLM** [comment]
This is the Error 500 when trying to change the IP settings:

20-12-03 14:43:38 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 133, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 195, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 60, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/network.py", line 208, in interface_update
    await asyncio.shield(self.sys_host.network.apply_changes(interface))
  File "/usr/src/supervisor/supervisor/host/network.py", line 173, in apply_changes
    await self.update()
  File "/usr/src/supervisor/supervisor/host/network.py", line 107, in update
    await self.check_connectivity()
  File "/usr/src/supervisor/supervisor/host/network.py", line 76, in check_connectivity
    if not self.sys_dbus.network.connectivity_enabled:
  File "/usr/src/supervisor/supervisor/dbus/network/__init__.py", line 58, in connectivity_enabled
    return self.properties[DBUS_ATTR_CONNECTION_ENABLED]
KeyError: 'ConnectivityCheckEnabled'

**Comment by EmmanuelLM** [comment]
After a bit of reading through the code, I *think* the connectivity is checked using the gdbus command line.

As it happens, this was not installed on my system and was provided by libglib2.0-bin [I will file a bug report against the installer.sh if needed].

I have rebooted the system, ran "ha supervisor repair", rebooted the system again and.... no dice! I still get the error :(

**Comment by georaspi** [comment]
I had very similar issue. What worked for me was to upgrade to Buster 10 (yes I know, I was outdated!) and this solved it.

**Comment by dferrante** [comment]
for anyone coming to this thread using Docker/Ubuntu as their HA OS/deployment combo, i had this same issue, and fixed it by finally upgrading from 16.04 to 20.04
