### ISSUE TITLE
Raspberry Pi | Addon Repositories missing / not working

### ISSUE THREAD

**Issue by eyduh** [home-assistant/supervisor#2397]
Hi,
fresh install on a Raspberry Pi 4, I've tried both the 32 and the 64bit images.

At first it was working fine on a 64bit image, but I wanted to get the GPIO working so reflashed a 32bit image.

Now I can't get the addons to work on either the 32 or 64bit images.

Under addons, repositories, there's nothing. If I try to add them manually I get the spinny wheel forever and the log below:

```
21-01-04 02:48:51 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-01-04 02:48:51 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'NoneType' object has no attribute 'active_branch'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 61, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 143, in pull
    branch = self.repo.active_branch.name
AttributeError: 'NoneType' object has no attribute 'active_branch'
21-01-04 02:48:51 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2119' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:101> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 61, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 143, in pull
    branch = self.repo.active_branch.name
AttributeError: 'NoneType' object has no attribute 'active_branch'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 105, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 67, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
21-01-04 02:48:51 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove
21-01-04 02:48:51 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove
21-01-04 02:49:40 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/home-assistant/addons repository
21-01-04 02:49:42 ERROR (MainThread) [supervisor.store] https://github.com/home-assistant/addons is not a valid add-on repository
21-01-04 02:49:42 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/96a017aa/repository.json: [Errno 2] No such file or directory: '/data/addons/git/96a017aa/repository.json'
21-01-04 02:49:42 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/96a017aa/repository.json
21-01-04 02:49:42 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove
21-01-04 02:49:42 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-01-04 02:49:42 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
21-01-04 02:49:42 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-04 02:49:42 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-04 02:49:42 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-01-04 02:49:42 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
21-01-04 02:49:42 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-04 02:49:42 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-04 02:49:45 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/96a017aa/repository.json: [Errno 2] No such file or directory: '/data/addons/git/96a017aa/repository.json'
21-01-04 02:49:45 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/96a017aa/repository.json
21-01-04 02:49:45 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove
21-01-04 02:49:45 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-01-04 02:49:45 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
21-01-04 02:49:45 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-04 02:49:45 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-04 02:49:45 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-01-04 02:49:45 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
21-01-04 02:49:45 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-04 02:49:45 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-04 02:51:27 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-01-04 02:51:27 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-01-04 02:51:28 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-01-04 03:02:14 INFO (MainThread) [supervisor.store.git] Cloning add-on https://home-assistant.io/addons repository
21-01-04 03:02:15 ERROR (MainThread) [supervisor.store.git] Can't clone https://home-assistant.io/addons repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://home-assistant.io/addons /data/addons/git/56fa7159
  stderr: 'Cloning into '/data/addons/git/56fa7159'...
fatal: repository 'https://home-assistant.io/addons/' not found
'.
21-01-04 03:02:15 ERROR (MainThread) [supervisor.store] Can't load data from repository https://home-assistant.io/addons
21-01-04 03:02:15 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/96a017aa/repository.json: [Errno 2] No such file or directory: '/data/addons/git/96a017aa/repository.json'
21-01-04 03:02:15 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/96a017aa/repository.json
21-01-04 03:02:15 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove
21-01-04 03:02:15 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-01-04 03:02:15 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
21-01-04 03:02:15 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-04 03:02:15 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-04 03:02:15 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-01-04 03:02:15 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
21-01-04 03:02:15 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-04 03:02:15 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-04 03:02:15 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
21-01-04 03:02:15 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
21-01-04 03:02:15 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-04 03:02:15 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-04 03:02:27 INFO (MainThread) [supervisor.store.git] Cloning add-on https://hass.io/addons repository
```

**Comment by thorsten** [comment]
Same issue here on a RasPi 4

**Comment by thorsten** [comment]
Okay, it worked after restarting the supervisor.

**Comment by eyduh** [comment]
> Okay, it worked after restarting the supervisor.

So I tried this (and a full reboot from the Configurations pane) and what do you know, the official addons showed back up!
Now the addon pane shows this:
![image](https://user-images.githubusercontent.com/29815625/103579047-e8774d80-4ed7-11eb-9b4f-72ef0671bd54.png)

The "Repositories menu is still a bit weird showing "unknown" on the hass.io/addons entry but it works, however adding the community addons doesnt work:
![image](https://user-images.githubusercontent.com/29815625/103579368-7ce1b000-4ed8-11eb-8b58-ac90172e59f2.png)

I'll try the restart / reboot again and see if it shows up despite the error message.

log:
```
21-01-04 21:00:00 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/hassio-addons/repository repository
21-01-04 21:00:02 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 45 new - 0 remove
21-01-04 21:00:02 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: 366579fa
21-01-04 21:00:02 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://hass.io/addons
21-01-04 21:00:02 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-04 21:00:02 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-04 21:00:38 INFO (MainThread) [supervisor.store.git] Cloning add-on https://hass.io/addons repository
21-01-04 21:02:49 ERROR (MainThread) [supervisor.store.git] Can't clone https://hass.io/addons repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://hass.io/addons /data/addons/git/366579fa
  stderr: 'Cloning into '/data/addons/git/366579fa'...
fatal: unable to access 'https://hass.io/addons/': Failed to connect to hass.io port 443: Operation timed out
'.
21-01-04 21:02:49 ERROR (MainThread) [supervisor.store] Can't load data from repository https://hass.io/addons
21-01-04 21:02:49 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
21-01-04 21:02:49 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: 366579fa
21-01-04 21:02:49 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://hass.io/addons
21-01-04 21:02:49 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-04 21:02:49 INFO (MainThread) [supervisor.resolution.check] System checks complete
```

Aaand, yup - the community addons DO show up in spite of the error message:
![image](https://user-images.githubusercontent.com/29815625/103579750-29bc2d00-4ed9-11eb-859f-45b421b3f3a3.png)

This time I didn't even restart, I only went to check the logs and then came back to find them all there.
Uhm, I'm not sure if to close this or not seeing as the intended function is there in spite of error messages.
