### ISSUE TITLE
2021.1.0 not available for i386

### ISSUE THREAD

**Issue by Kisty** [home-assistant/supervisor#2410]
Hi there!

I'm running HA supervisor on my i386 EeePC 1000 but I can't update the supervisor from 2020.12.1 to 2021.1.0 because there is no docker image available.

Any ideas?

Thanks!

#### Supervisor logs

<details>
  <summary>Logs</summary>

  ```
21-01-07 21:59:04 INFO (MainThread) [supervisor.homeassistant] Update Home Assistant to version 2021.1.0
21-01-07 21:59:04 INFO (SyncWorker_1) [supervisor.docker.interface] Update image homeassistant/qemux86-homeassistant:2020.12.1 to homeassistant/qemux86-homeassistant:2021.1.0
21-01-07 21:59:04 INFO (SyncWorker_1) [supervisor.docker.interface] Pull image homeassistant/qemux86-homeassistant tag 2021.1.0.
21-01-07 22:12:52 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install homeassistant/qemux86-homeassistant:2021.1.0 -> 404 Client Error: Not Found ("no such image: homeassistant/qemux86-homeassistant:2021.1.0: No such image: homeassistant/qemux86-homeassistant:2021.1.0").
21-01-07 22:12:52 WARNING (MainThread) [supervisor.homeassistant] Update Home Assistant image fails
21-01-07 22:17:12 INFO (MainThread) [supervisor.misc.tasks] Found new Supervisor version
21-01-07 22:17:12 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version None
21-01-07 22:17:12 INFO (SyncWorker_8) [supervisor.docker.interface] Pull image homeassistant/i386-hassio-supervisor tag None.
21-01-07 22:17:14 ERROR (SyncWorker_8) [supervisor.docker.interface] Can't install homeassistant/i386-hassio-supervisor:None -> 404 Client Error: Not Found ("manifest for homeassistant/i386-hassio-supervisor:None not found: manifest unknown: manifest unknown").
21-01-07 22:17:14 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor fails!
21-01-07 22:17:14 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Tasks._update_supervisor() done, defined at /usr/src/supervisor/supervisor/misc/tasks.py:155> exception=SupervisorUpdateError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 166, in _update_supervisor
    await self.sys_supervisor.update()
  File "/usr/src/supervisor/supervisor/supervisor.py", line 126, in update
    raise SupervisorUpdateError() from None
supervisor.exceptions.SupervisorUpdateError
  ```
</details>

**Comment by Kisty** [comment]
After clearing space as I did some research and part of the problem lied with not enough space so cleared space, tried `ha su repair` then rebooted but still getting this

### Supervisor logs
<details>
  <summary>Logs</summary>
  
  ```
21-01-13 09:18:11 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
21-01-13 09:23:11 INFO (MainThread) [supervisor.misc.tasks] Found new Supervisor version
21-01-13 09:23:11 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version None
21-01-13 09:23:11 INFO (SyncWorker_6) [supervisor.docker.interface] Pull image homeassistant/i386-hassio-supervisor tag None.
21-01-13 09:23:13 ERROR (SyncWorker_6) [supervisor.docker.interface] Can't install homeassistant/i386-hassio-supervisor:None -> 404 Client Error: Not Found ("manifest for homeassistant/i386-hassio-supervisor:None not found: manifest unknown: manifest unknown").
21-01-13 09:23:13 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor fails!
21-01-13 09:23:13 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Tasks._update_supervisor() done, defined at /usr/src/supervisor/supervisor/misc/tasks.py:155> exception=SupervisorUpdateError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 166, in _update_supervisor
    await self.sys_supervisor.update()
  File "/usr/src/supervisor/supervisor/supervisor.py", line 126, in update
    raise SupervisorUpdateError() from None
supervisor.exceptions.SupervisorUpdateError
  ```
</details>

**Comment by ludeeus** [comment]
Okey, so here something is now properly stored in your env.
Let's try to reset that.

```bash
ha su options -c beta
ha su reload
ha su options -c stable
ha su reload
ha su repair
ha su update
ha info
```

**Comment by Kisty** [comment]
Thanks for your help, @ludeeus. Tried that and it failed unfortunately.

<details>
<summary>Output</summary>

  ```
ha su options -c beta
ha su reload
ha su options -c stable
ha su reload
ha su repair
ha su update
ha info
ha su info
Command completed successfully.                                                                                                                                                                                                     
Command completed successfully.                                                                                                                                                                                                     
Command completed successfully.                                                                                                                                                                                                     
Processing... Done.                                                                                                                                                                                                                 
                                                                                                                                                                                                                                    
Command completed successfully.                                                                                                                                                                                                     
Processing... Done.                                                                                                                                                                                                                 
                                                                                                                                                                                                                                    
Error: Unknown Error, see logs                                                                                                                                                                                                      
arch: i386                                                                                                                                                                                                                          
channel: stable                                                                                                                                                                                                                     
docker: 19.03.6                                                                                                                                                                                                                     
hassos: null                                                                                                                                                                                                                        
homeassistant: 2021.1.1                                                                                                                                                                                                             
hostname: ubuntu                                                                                                                                                                                                                    
logging: info                                                                                                                                                                                                                       
machine: qemux86                                                                                                                                                                                                                    
supervisor: "227"                                                                                                                                                                                                                   
supported_arch:                                                                                                                                                                                                                     
- i386                                                                                                                                                                                                                              
timezone: Europe/London                                                                                                                                                                                                             
addons:                                                                                                                                                                                                                             
- description: Check current Home Assistant configuration against a new version                                                                                                                                                     
  icon: true                                                                                                                                                                                                                        
  installed: "3.1"                                                                                                                                                                                                                  
  logo: true                                                                                                                                                                                                                        
  name: Check Home Assistant configuration                                                                                                                                                                                          
  repository: core                                                                                                                                                                                                                  
  slug: core_check_config                                                                                                                                                                                                           
  state: stopped                                                                                                                                                                                                                    
  version: "3.1"                                                                                                                                                                                                                    
- description: Simple browser-based file editor for Home Assistant                                                                                                                                                                  
  icon: true                                                                                                                                                                                                                        
  installed: "4.7"                                                                                                                                                                                                                  
  logo: true                                                                                                                                                                                                                        
  name: File editor                                                                                                                                                                                                                 
  repository: core                                                                                                                                                                                                                  
  slug: core_configurator                                                                                                                                                                                                           
  state: started                                                                                                                                                                                                                    
  version: "4.7"                                                                                                                                                                                                                    
- description: Free Dynamic DNS (DynDNS or DDNS) service with Let's Encrypt support                                                                                                                                                 
  icon: true                                                                                                                                                                                                                        
  installed: 1.12.4                                                                                                                                                                                                                 
  logo: true                                                                                                                                                                                                                        
  name: Duck DNS                                                                                                                                                                                                                    
  repository: core                                                                                                                                                                                                                  
  slug: core_duckdns                                                                                                                                                                                                                
  state: started                                                                                                                                                                                                                    
  version: 1.12.4                                                                                                                                                                                                                   
- description: An SSL/TLS proxy                                                                                                                                                                                                     
  icon: true                                                                                                                                                                                                                        
  installed: 3.0.1                                                                                                                                                                                                                  
  logo: true                                                                                                                                                                                                                        
  name: NGINX Home Assistant SSL proxy 
  repository: core
  slug: core_nginx_proxy
  state: started
  version: 3.0.1
- description: SSH & Web Terminal access to your Home Assistant instance
  icon: true
  installed: 7.1.0  logo: true
  name: SSH & Web Terminal
  repository: a0d7b954
  slug: a0d7b954_ssh
  state: started
  version: 7.1.0
- description: Centrally manage all your Sonoff-Tasmota devices
  icon: true
  installed: 0.13.1
  logo: true  name: TasmoAdmin
  repository: a0d7b954
  slug: a0d7b954_sonweb
  state: stopped
  version: 0.13.1
- description: An Open Source MQTT broker
  icon: true
  installed: "5.1"
  logo: true
  name: Mosquitto broker
  repository: core
  slug: core_mosquitto
  state: started
  version: "5.1"
- description: A cross-platform system monitoring tool
  icon: true
  installed: 0.9.1
  logo: true
  name: Glances
  repository: a0d7b954
  slug: a0d7b954_glances
  state: stopped
  version: 0.9.1
addons_repositories:
- https://github.com/hassio-addons/repository
- https://github.com/danielwelch/hassio-zigbee2mqtt
- https://github.com/esphome/hassio
- https://github.com/Apipa169/Assistant-Relay-for-Hassio
- https://github.com/AndBobsYourUncle/hassio-addons
arch: i386
channel: stable
ip_address: <redacted>
logging: info
timezone: Europe/London
version: "227"
version_latest: null
wait_boot: 5
  ```
</details>

**Comment by ludeeus** [comment]
You are running an unsupported installation with Ubuntu, and your Supervisor version is really old (227).
I suggest you reinstall with Debian which is supported or that you use Home Assistant Operating System.
Closing this as unsupported.
<https://github.com/home-assistant/architecture/blob/master/adr/0012-define-supported-installation-method.md>
<https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>
