### ISSUE TITLE
"no such image" when trying to update HA hoses system

### ISSUE THREAD

**Issue by lancelon** [home-assistant/supervisor#2523]
### Describe the issue

Tried to update to the latest HA via the GUI (clicked the button to upgrade) but then after waiting nothing happened so I went to the supervisor logs to find `("no such image: homeassistant/raspberrypi3-homeassistant:2021.2.1: No such image: homeassistant/raspberrypi3-homeassistant:2021.2.1").`
I then thought "oh, I'll try a host restart". BIG MISTAKE. The system has still not come up and that was hours ago and I've attempted multiple restarts and repairs and restores since.

### Steps to reproduce

1. ... Be running 2021.1.4
2. ... Attempt to upgrade using the gui
3. ...Be prepared for major problems

### Enviroment details

- **Operating System:**: xxx
- **Supervisor version:**: xxx
- **Home Assistant version**: xxx

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[13:31:03] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-02-07 13:31:18 ERROR (MainThread) [homeassistant.config] Package zigbee2mqtt setup failed. Integration input_number Integration 'input_number' not found. (See /config/packages/zigbee2mqtt.yaml:1). 
2021-02-07 13:31:18 ERROR (MainThread) [homeassistant.config] Package zigbee2mqtt setup failed. Integration input_text Integration 'input_text' not found. (See /config/packages/zigbee2mqtt.yaml:1). 
2021-02-07 13:31:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-07 13:31:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-07 13:31:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-07 13:31:18 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for logbook:  we are unable to resolve (sub)dependency person
2021-02-07 13:31:18 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for alarmo:  we are unable to resolve (sub)dependency person
2021-02-07 13:31:18 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for hacs:  we are unable to resolve (sub)dependency person
2021-02-07 13:31:18 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for default_config:  we are unable to resolve (sub)dependency person
2021-02-07 13:31:18 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 320, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 312, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 117, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/src/homeassistant/homeassistant/runner.py", line 106, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 122, in async_setup_hass
    await async_from_config_dict(config_dict, hass) is not None
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 234, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 464, in _async_set_up_integrations
    for dep in itg.all_dependencies:
  File "/usr/src/homeassistant/homeassistant/loader.py", line 373, in all_dependencies
    raise RuntimeError("Dependencies not resolved!")
RuntimeError: Dependencies not resolved!
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[15:26:56] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
~ $ ha core logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[15:26:56] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-02-07 15:27:10 ERROR (MainThread) [homeassistant.config] Package zigbee2mqtt setup failed. Integration input_number Integration 'input_number' not found. (See /config/packages/zigbee2mqtt.yaml:1). 
2021-02-07 15:27:10 ERROR (MainThread) [homeassistant.config] Package zigbee2mqtt setup failed. Integration input_text Integration 'input_text' not found. (See /config/packages/zigbee2mqtt.yaml:1). 
2021-02-07 15:27:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-07 15:27:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-07 15:27:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-07 15:27:11 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for logbook:  we are unable to resolve (sub)dependency person
2021-02-07 15:27:11 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for alarmo:  we are unable to resolve (sub)dependency person
2021-02-07 15:27:11 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for hacs:  we are unable to resolve (sub)dependency person
2021-02-07 15:27:11 ERROR (MainThread) [homeassistant.loader] Unable to resolve dependencies for default_config:  we are unable to resolve (sub)dependency person
2021-02-07 15:27:11 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 320, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 312, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 117, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/src/homeassistant/homeassistant/runner.py", line 106, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 122, in async_setup_hass
    await async_from_config_dict(config_dict, hass) is not None
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 234, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 464, in _async_set_up_integrations
    for dep in itg.all_dependencies:
  File "/usr/src/homeassistant/homeassistant/loader.py", line 373, in all_dependencies
    raise RuntimeError("Dependencies not resolved!")
RuntimeError: Dependencies not resolved!
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
</details>

### System Information

```

Version | 2021.1.4
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.79-v7
CPU Architecture | armv7l
Timezone | Europe/London



```

[Thread here](https://community.home-assistant.io/t/rebooted-host-now-ha-wont-boot/278010)

What I'd really like to know is am I wasting my time reflashing my SD card and trying to restore a snapshot onto it?!

</details>

**Comment by lancelon** [comment]
Got back into the GUI and attempted a restore of a recent fully functional snapshot and get this again

```
21-02-07 20:39:28 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:2021.1.4 ->   404 Client Error for http+docker://localhost/v1.40/images/homeassistant/raspberrypi3-homeassistant:2021.1.4/json: Not Found ("no such image: homeassistant/raspberrypi3-homeassistant:2021.1.4: No such image: homeassistant/raspberrypi3-homeassistant:2021.1.4").
21-02-07 20:39:28 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed
21-02-07 20:39:28 ERROR (MainThread) [supervisor.snapshots] Restore 8899d6a5 error
```

**Comment by lancelon** [comment]
So I finally got my system back by :-

- Doing a ha supervisor repair
- Doing a ha core start
- When I got the front end up, switching to beta track
- Upgrading supervisor
- Upgrading host
- Restore snapshot

That worked. But it took a whole afternoon/evening.
