### ISSUE TITLE
2021.3.0 Local Addon gives this error : 'NoneType' object has no attribute 'is_file'

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/supervisor#2669]
### Describe the issue you are experiencing

I was working with local addon, no issues, since now supervisor updated to 2021.3.0

### What is the used version of the Supervisor?

supervisor-2021.03.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.2.3

### Steps to reproduce the issue

make a local addon as descibed here: https://developers.home-assistant.io/docs/add-ons/tutorial/

gives this error upon start

### Anything in the Supervisor logs that might be useful for us?

```
```
21-03-03 19:11:51 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'NoneType' object has no attribute 'is_file'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 182, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 491, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 500, in _build
    build_env = AddonBuild(self.coresys, self.addon)
  File "/usr/src/supervisor/supervisor/addons/build.py", line 32, in __init__
    super().__init__(
  File "/usr/src/supervisor/supervisor/utils/common.py", line 59, in __init__
    self.read_data()
  File "/usr/src/supervisor/supervisor/utils/common.py", line 72, in read_data
    if self._file.is_file():
AttributeError: 'NoneType' object has no attribute 'is_file'
```

```

my core is still at version : core-2021.2.3

**Comment by ludeeus** [comment]
Add a blank `build.yaml` file in the same directory

**Comment by pergolafabio** [comment]
ok, that did it , thnx

is it a bug? or ?

**Comment by ludeeus** [comment]
Yes
