### ISSUE TITLE
Error updating addon with config

### ISSUE THREAD

**Issue by KTibow** [home-assistant/supervisor#2672]
### Describe the issue you are experiencing

I made a custom addon and put it in `/addons`. The source is in KTibow/fridge/leftunder_addon. When I try to update / install, I get this error:
```
21-03-04 03:06:44 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'NoneType' object has no attribute 'is_file'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 182, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 491, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 500, in _build
    build_env = AddonBuild(self.coresys, self.addon)
  File "/usr/src/supervisor/supervisor/addons/build.py", line 32, in __init__
    super().__init__(
  File "/usr/src/supervisor/supervisor/utils/common.py", line 59, in __init__
    self.read_data()
  File "/usr/src/supervisor/supervisor/utils/common.py", line 72, in read_data
    if self._file.is_file():
AttributeError: 'NoneType' object has no attribute 'is_file'
```

### What is the used version of the Supervisor?

supervisor-2021.03.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.3.0

### Steps to reproduce the issue

I'm not sure if this could easily be reproducible. Many updates happened along the way. Here's what how I got the addon.
1. Set up Samba share
2. Copy KTibow/fridge/leftunder_addon to `/addons` in HA
3. Reload addons and try to install
4. Nothing happens (spinning circle cancels) and error is in log

### Anything in the Supervisor logs that might be useful for us?

```txt
21-03-04 03:06:44 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'NoneType' object has no attribute 'is_file'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 182, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 491, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 500, in _build
    build_env = AddonBuild(self.coresys, self.addon)
  File "/usr/src/supervisor/supervisor/addons/build.py", line 32, in __init__
    super().__init__(
  File "/usr/src/supervisor/supervisor/utils/common.py", line 59, in __init__
    self.read_data()
  File "/usr/src/supervisor/supervisor/utils/common.py", line 72, in read_data
    if self._file.is_file():
AttributeError: 'NoneType' object has no attribute 'is_file'
```

**Comment by pvizeli** [comment]
Doublicate https://github.com/home-assistant/supervisor/issues/2669
