### ISSUE TITLE
New error after some changes to the configuration and updating the Mosquitto Add-on

### ISSUE THREAD

**Issue by martymarty004** [home-assistant/supervisor#2902]
### The problem

I recently made some changes to the configuration of HA and the Add-ons (I started to use Secrets and split up the configuration.yaml file, the Config Check was OK), and I noticed the error below in the Supervisor logs afterwards 
(it doesn't show up in the settings page). 
An identical error appears every few minutes.
Everything seems to be working fine except of the error.

### What is version of Home Assistant Core has the issue?

2021.5.4

### What was the last working version of Home Assistant Core?

2021.5.4

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
##########################
##  CONFIGURATION.YAML  ##
##########################


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


logger:
  default: info


# Text to speech
tts:
  - platform: google_translate



# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


sensor: !include sensor.yaml
light: !include light.yaml


homeassistant:
  customize: !include customize.yaml
  


wake_on_lan:



# TV Samsung
samsungtv:
  - host: 192.168.1.7
    name: TV Samsung
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "*redacted*"



# HomeKit
homekit: !include homekit_config.yaml



###############################
# Mosquitto Add-on configuration
###############################

logins:
  - username: '!secret Mosquitto_User'
    password: '!secret Mosquitto_Passw'
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false



###############################
# DuckDNS Add-on configuration
###############################


lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: '!secret DuckDNS_Token'
domains:
  - *redacted*.duckdns.org
aliases: []
seconds: 600



###############################
# Samba Add-on configuration
###############################

workgroup: WORKGROUP
username: '!secret Samba_User'
password: '!secret Samba_Passw'
interface: ''
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false

#########################
```

### Anything in the logs that might be useful for us?

```txt
21-05-19 09:05:54 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-878' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)
```

### Additional information

![image](https://user-images.githubusercontent.com/61474670/118788948-90dceb80-b894-11eb-93d1-30a6292151b0.png)

![image](https://user-images.githubusercontent.com/61474670/118788991-9b978080-b894-11eb-92a4-0a32fda1b642.png)

**Comment by frenck** [comment]
Transferring the issue to the Supervisor repository, as this is originating from there.

**Comment by martymarty004** [comment]
Here is my `ha info` output:
```
arch: armv7
channel: stable
docker: 19.03.15
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "5.13"
homeassistant: 2021.5.4
hostname: homeassistant
logging: info
machine: raspberrypi4
operating_system: Home Assistant OS 5.13
state: running
supervisor: 2021.04.3
supported: true
supported_arch:
- armv7
- armhf
timezone: Europe/Rome
```

**Comment by martymarty004** [comment]
Just to be clear, which update will contain this bug fix?
