### ISSUE TITLE
Continuous error in Supervisor logs, no known user impact

### ISSUE THREAD

**Issue by mixpix405** [home-assistant/supervisor#2908]
### Describe the issue you are experiencing

After updating to core-2021.5.5 I've noticed that exactly every 2 minutes there is a repeating error in the supervisor logs. I do not have any known symptoms - everything in my HomeAssistant setup seems to be working as expected. I do not believe the error existed prior to 2021.5.5, but I admittedly do not check my supervisor logs very often if I'm not having any issues, so it could've exited prior.

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2021.5.5

### Steps to reproduce the issue

No steps, just noticed the error in my logs.

### Anything in the Supervisor logs that might be useful for us?

```txt
21-05-20 12:55:42 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-342353' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)
```

### Additional information

I've restarted Home assistant, reloaded and restarted the supervisor, and I've rebooted the host Debian machine, but the error continues.

Docker version according to the Supervisor panel is 20.10.6

**Comment by mixpix405** [comment]
Sorry for the duplicate. I'm apparently terrible at searching github for already submitted issues.
