### ISSUE TITLE
Error during update Z-Wave JS addon

### ISSUE THREAD

**Issue by bieniu** [home-assistant/supervisor#2985]
### Describe the issue you are experiencing

When I trie to update Z-Wave JS addon from version 0.1.27 to 0.1.28 I get `KeyError: 'core_zwave_js'` error in supervisor log.

### What is the used version of the Supervisor?

supervisor-2021.06.6

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Linux nuc 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux

### What version of Home Assistant Core is installed?

core-2021.6.6

### Steps to reproduce the issue

1. Go to Supervisor -> Dashboard
2. Click Z-Wave JS addon
3. Click Update

### Anything in the Supervisor logs that might be useful for us?

```txt
21-06-30 12:42:52 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'core_zwave_js'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 265, in update
    store = self.store[slug]
KeyError: 'core_zwave_js'
```
```


### Additional information

_No response_

**Comment by ludeeus** [comment]
Paste the entire supervisor log after doing;
- Restart the supervisor
- Update the addon

**Comment by bieniu** [comment]
Strange thing, after supervisor restart, the addon update was successful. Before that, I restarted the entire server twice and kept getting this error.

```
21-06-30 13:12:17 INFO (MainThread) [__main__] Closing Supervisor
21-06-30 11:12:20 INFO (MainThread) [supervisor.bootstrap] Use the old homeassistant repository for machine extraction
21-06-30 11:12:20 INFO (MainThread) [__main__] Initializing Supervisor setup
21-06-30 11:12:20 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
21-06-30 13:12:20 WARNING (MainThread) [supervisor.bootstrap] Missing SUPERVISOR_MACHINE environment variable. Fallback to deprecated extraction!
21-06-30 13:12:20 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: intel-nuc
21-06-30 13:12:20 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/amd64-hassio-supervisor with version 2021.06.6
21-06-30 13:12:20 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-06-30 13:12:20 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
21-06-30 13:12:20 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-30 13:12:20 INFO (MainThread) [__main__] Setting up Supervisor
21-06-30 13:12:20 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
21-06-30 13:12:21 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
21-06-30 13:12:27 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
21-06-30 13:12:27 INFO (MainThread) [supervisor.host.info] Updating local host information
21-06-30 13:12:27 INFO (MainThread) [supervisor.host.services] Updating service information
21-06-30 13:12:27 INFO (MainThread) [supervisor.host.network] Updating local network information
21-06-30 13:12:29 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-06-30 13:12:29 INFO (MainThread) [supervisor.host] Host information reload completed
21-06-30 13:12:29 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
21-06-30 13:12:29 INFO (MainThread) [supervisor.host.services] Reloading local service hassio-apparmor.service
21-06-30 13:12:30 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-dns with version 2021.06.0
21-06-30 13:12:30 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
21-06-30 13:12:30 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-audio with version 2021.04.0
21-06-30 13:12:30 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-cli with version 2021.05.1
21-06-30 13:12:30 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-observer with version 2021.06.0
21-06-30 13:12:30 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-multicast with version 2021.04.0
21-06-30 13:12:30 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-06-30 13:12:32 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/intel-nuc-homeassistant with version 2021.6.6
21-06-30 13:12:32 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 32 Home Assistant secrets
21-06-30 13:12:32 INFO (MainThread) [supervisor.hassos] No Home Assistant Operating System found
21-06-30 13:12:33 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
21-06-30 13:12:33 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
21-06-30 13:12:35 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 63 new - 0 remove
21-06-30 13:12:35 INFO (MainThread) [supervisor.addons] Found 8 installed add-ons
21-06-30 13:12:35 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/bitwarden/amd64 with version 0.11.0
21-06-30 13:12:35 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to esphome/esphome-hassio-amd64 with version 1.19.4
21-06-30 13:12:35 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/traccar/amd64 with version 0.12.0
21-06-30 13:12:35 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-check_config with version 3.7.1
21-06-30 13:12:35 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-mosquitto with version 6.0.1
21-06-30 13:12:35 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-mariadb with version 2.4.0
21-06-30 13:12:35 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-zwave_js with version 0.1.27
21-06-30 13:12:35 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-rpc_shutdown with version 2.2
21-06-30 13:12:35 INFO (MainThread) [supervisor.snapshots] Found 51 snapshot files
21-06-30 13:12:35 INFO (MainThread) [supervisor.discovery] Loaded 2 messages
21-06-30 13:12:35 INFO (MainThread) [supervisor.ingress] Loaded 1 ingress sessions
21-06-30 13:12:35 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-06-30 13:12:35 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-06-30 13:12:35 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-06-30 13:12:36 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-30 13:12:36 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
21-06-30 13:12:36 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-06-30 13:12:36 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-30 13:12:36 INFO (MainThread) [__main__] Running Supervisor
21-06-30 13:12:36 INFO (MainThread) [supervisor.jobs] 'HassOS.mark_healthy' blocked from execution, no Home Assistant OS available
21-06-30 13:12:36 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
21-06-30 13:12:36 INFO (MainThread) [supervisor.core] Supervisor reboot detected
21-06-30 13:12:36 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
21-06-30 13:12:36 INFO (MainThread) [supervisor.core] Supervisor is up and running
21-06-30 13:12:36 INFO (MainThread) [supervisor.host.info] Updating local host information
21-06-30 13:12:36 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-06-30 13:12:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-06-30 13:12:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-06-30 13:12:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-06-30 13:12:36 INFO (MainThread) [supervisor.host.services] Updating service information
21-06-30 13:12:36 INFO (MainThread) [supervisor.host.network] Updating local network information
21-06-30 13:12:36 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-06-30 13:12:36 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-06-30 13:12:38 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-30 13:12:38 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-06-30 13:12:38 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-06-30 13:12:39 INFO (MainThread) [supervisor.host] Host information reload completed
21-06-30 13:16:03 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt_client'
21-06-30 13:16:04 INFO (MainThread) [supervisor.auth] Successful login for 'mqtt_client'
21-06-30 13:18:58 INFO (MainThread) [supervisor.snapshots] Creating new partial-snapshot with slug 7d9239f3
21-06-30 13:18:58 INFO (MainThread) [supervisor.snapshots] Snapshotting 7d9239f3 store Add-ons
21-06-30 13:18:58 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_zwave_js
21-06-30 13:19:01 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_zwave_js
21-06-30 13:19:01 INFO (MainThread) [supervisor.snapshots] Creating partial-snapshot with slug 7d9239f3 completed
21-06-30 13:19:01 INFO (SyncWorker_1) [supervisor.docker.interface] Updating image homeassistant/amd64-addon-zwave_js:0.1.27 to homeassistant/amd64-addon-zwave_js:0.1.28
21-06-30 13:19:01 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image homeassistant/amd64-addon-zwave_js with tag 0.1.28.
21-06-30 13:19:15 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_core_zwave_js application
21-06-30 13:19:20 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_zwave_js application
21-06-30 13:19:20 INFO (MainThread) [supervisor.addons] Add-on 'core_zwave_js' successfully updated
```

**Comment by ludeeus** [comment]
Then you had issues after the previous startup, which is now resolved 👍
