### ISSUE TITLE
Restoring snapshots of older HA versions fails as images are not found in github packages

### ISSUE THREAD

**Issue by mgolisch** [home-assistant/supervisor#2996]
### Describe the issue you are experiencing

when trying to restore a snapshot containing an older ha version it fails with :
`Error:` Unknown error, see `supervisor`
when doing a partial restore(ha only) and if doing a full restore it tries to restore it but fails and then the homeassistant container doesnt come up anymore.

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.1

### What version of Home Assistant Core is installed?

core-2021.5.5

### Steps to reproduce the issue

1. restore snapshot with ha version thats a few month old(tried with a snapshot that contains core-2021.2.1 and one with a version from 2020)

### Anything in the Supervisor logs that might be useful for us?

```txt
1-07-06 19:54:01 INFO (MainThread) [supervisor.snapshots] Restoring e6bf5655 Home-Assistant
21-07-06 19:54:01 INFO (MainThread) [supervisor.snapshots] Restore e6bf5655 wait for Home-Assistant
21-07-06 19:54:01 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2020.12.1
21-07-06 19:54:01 INFO (SyncWorker_2) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/qemux86-64-homeassistant:2021.5.5 to ghcr.io/home-assistant/qemux86-64-homeassistant:2020.12.1
21-07-06 19:54:01 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/qemux86-64-homeassistant with tag 2020.12.1.
21-07-06 19:54:02 ERROR (SyncWorker_2) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/qemux86-64-homeassistant:2020.12.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2020.12.1&fromImage=ghcr.io%2Fhome-assistant%2Fqemux86-64-homeassistant: Internal Server Error ("name unknown")
21-07-06 19:54:02 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed
21-07-06 19:54:02 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.UPDATE_FAILED - ContextType.CORE / None
21-07-06 19:54:02 ERROR (MainThread) [supervisor.snapshots] Restore e6bf5655 error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/snapshots/__init__.py", line 370, in do_restore_partial
    await task_hass
  File "/usr/src/supervisor/supervisor/snapshots/__init__.py", line 403, in _core_update
    await self.sys_homeassistant.core.update(version)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 107, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 240, in update
    raise HomeAssistantUpdateError()
supervisor.exceptions.HomeAssistantUpdateError
```

**Comment by ludeeus** [comment]
Should be working now back to January 2020
