### ISSUE TITLE
Add on error

### ISSUE THREAD

**Issue by countrysideboy** [home-assistant/supervisor#3034]
### Describe the issue you are experiencing

Add-on list empty

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Ubuntu 20.04.2 LTS

### What version of Home Assistant Core is installed?

core-2021.7.4

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-06-22 00:29:58 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-06-22 00:29:58 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/:refs/heads/"'.
Traceback (most recent call last):
File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
return await self._method(args, **kwargs)
File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
await self.sys_run_in_executor(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 818, in fetch
self._assert_refspec()
File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 782, in _assert_refspec
raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/:refs/heads/"'.
21-06-22 00:29:58 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-187372' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=JobException()>
Traceback (most recent call last):
File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
return await self._method(args, **kwargs)
File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
await self.sys_run_in_executor(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 818, in fetch
self._assert_refspec()
File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 782, in _assert_refspec
raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/:refs/heads/"'.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
await self.git.pull()
File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 111, in wrapper
raise JobException() from err
supervisor.exceptions.JobException
```

**Comment by ludeeus** [comment]
Only Debian is supported as the host OS for a supervised installation
https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md

**Comment by countrysideboy** [comment]
The OS is called armbian.
