### ISSUE TITLE
The add-on cannot be reloaded

### ISSUE THREAD

**Issue by Clevival2021** [home-assistant/supervisor#3047]
### Describe the issue you are experiencing

The add-on cannot be reloaded

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.2

### What version of Home Assistant Core is installed?

core-2021.7.4

### Steps to reproduce the issue

1.The add-on cannot be reloaded

### Anything in the Supervisor logs that might be useful for us?

```txt
21-08-04 15:06:20 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-08-04 15:06:20 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-08-04 15:06:20 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 818, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 782, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
21-08-04 15:06:22 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2041' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 818, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 782, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 111, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
21-08-04 15:06:22 INFO (MainThread) [supervisor.store] Loading add-ons from store: 39 all - 0 new - 0 remove
21-08-04 15:06:22 INFO (MainThread) [supervisor.store] Loading add-ons from store: 39 all - 0 new - 0 remove
```

**Comment by fir3burn** [comment]
I have the same issue. I cant update the zwave-js addon and cant update core to 2021.9 because schema api v8 requirements of zwave-js in this version.
