### ISSUE TITLE
[zeroconf] Choked at offset

### ISSUE THREAD

**Issue by jrm523** [home-assistant/supervisor#3071]
### The problem

I have experienced this error on a new install of Home Assistant OS VM running on VMware Workstation Pro 16. 

### What is version of Home Assistant Core has the issue?

core-2021.8.8

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

zeroconf

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/zeroconf/

### Example YAML snippet

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - ::1
```

### Anything in the logs that might be useful for us?

```txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
2021-08-23 14:11:30 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /host/reboot request Server disconnected
2021-08-23 14:11:30 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /host/reboot - 
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-08-23 14:13:09 WARNING (MainThread) [zeroconf] Choked at offset 32942 while unpacking b'\x00\x00\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x0ehomeassistant8\x05local\x00\x00\xff\x00\x011homeassistant8 [4719c51feaca4eb1811f920c78b3a2a2]\x0c_workstation\x04_tcp\xc0\x1b\x00\xff\x00\x010homeassistant [4719c51feaca4eb1811f920c78b3a2a2]\xc0X\x00\xff\x00\x01\xc0\x0c\x00\x1c\x80\x01\x00\x00\x00x\x00\x10\xfe\x80\x00\x00\x00\x00\x00\x00\x85\xed\x1c\xdcj/D\x06\xc0&\x00\x10\x80\x01\x00\x00\x00x\x00\x01\x00\xc0&\x00!\x80\x01\x00\x00\x00x\x00\x1c\x00\x00\x00\x00\x00\x00\x0ehomeassistant8\x05local\x00'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 111, in __init__
    self.read_others()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 178, in read_others
    domain = self.read_name()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
    self.offset = self._decode_labels_at_offset(self.offset, labels)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 309, in _decode_labels_at_offset
    raise IncomingDecodeError("Corrupt packet received while decoding name")
zeroconf._exceptions.IncomingDecodeError: Corrupt packet received while decoding name
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
2021-08-23 14:37:38 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /host/reboot request Server disconnected
2021-08-23 14:37:38 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /host/reboot - 
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-08-23 14:39:15 WARNING (MainThread) [zeroconf] Choked at offset 32942 while unpacking b'\x00\x00\x00\x00\x00\x02\x00\x00\x00\x03\x00\x001homeassistant6 [4719c51feaca4eb1811f920c78b3a2a2]\x0c_workstation\x04_tcp\x05local\x00\x00\xff\x00\x01\x0ehomeassistant6\xc0P\x00\xff\x00\x010homeassistant [4719c51feaca4eb1811f920c78b3a2a2]\xc0>\x00\xff\x00\x01\xc0\x0c\x00\x10\x80\x01\x00\x00\x00x\x00\x01\x00\xc0\x0c\x00!\x80\x01\x00\x00\x00x\x00\x1c\x00\x00\x00\x00\x00\x00\x0ehomeassistant6\x05local\x00\xc0[\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\x1f\xc4'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 111, in __init__
    self.read_others()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 178, in read_others
    domain = self.read_name()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
    self.offset = self._decode_labels_at_offset(self.offset, labels)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 309, in _decode_labels_at_offset
    raise IncomingDecodeError("Corrupt packet received while decoding name")
zeroconf._exceptions.IncomingDecodeError: Corrupt packet received while decoding name
```

### Additional information

I currently only have four integrations loaded (Samba, Visual Studio, Nginx Proxy Manager, and MariaDB.  I have no devices added. Every time I initiate a reboot from the Supervisor System page, there is two errors regarding reboot and then a block of error lines for zeroconf that starts with **"choked at offset"** and ends with **"corrupt packet received while decoding name"**. This is consistently repeatable.

This is my first time posting an issue to Github. Please let me know if you have any questions or need any additional information. Thanks in advance for such a great home automation platform!

**Comment by bdraco** [comment]
Looks like its trying to handle conflicting names:

<img width="392" alt="Screen Shot 2021-08-23 at 10 33 04 PM" src="https://user-images.githubusercontent.com/663432/130551600-87c18232-6ba9-4ecb-9def-559562dfaba7.png">

**Comment by bdraco** [comment]
https://github.com/systemd/systemd/blame/main/src/resolve/resolved-dns-packet.c#L535

There is a change here in 248 but I don't think its related
https://github.com/systemd/systemd/commit/daced7483b54d9166080343efa52c2f38997c83c

**Comment by bdraco** [comment]
This is happening with and without the brackets
```
2021-08-24 13:40:55 DEBUG (MainThread) [zeroconf] Choked at offset 32938 while unpacking b'\x00\x00\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x0ehomeassistant3\x05local\x00\x00\xff\x00\x01/homeassistant3 8cb39b13cf3f49a484de32f800b23266\x0c_workstation\x04_tcp\xc0\x1b\x00\xff\x00\x01.homeassistant 8cb39b13cf3f49a484de32f800b23266\xc0V\x00\xff\x00\x01\xc0\x0c\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd5\x9d\xc0&\x00\x10\x80\x01\x00\x00\x00x\x00\x01\x00\xc0&\x00!\x80\x01\x00\x00\x00x\x00\x1c\x00\x00\x00\x00\x00\x00\x0ehomeassistant3\x05local\x00'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/_protocol.py", line 111, in __init__
    self.read_others()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/_protocol.py", line 178, in read_others
    domain = self.read_name()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/_protocol.py", line 268, in read_name
    self.offset = self._decode_labels_at_offset(self.offset, labels)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/_protocol.py", line 309, in _decode_labels_at_offset
    raise IncomingDecodeError("Corrupt packet received while decoding name")
zeroconf._exceptions.IncomingDecodeError: Corrupt packet received while decoding name

```

`systemctl restart systemd-resolved` will trigger it

**Comment by bdraco** [comment]
Net::DNS can't parse the packet either

```
use Net::DNS;
use Data::Dumper;

print Dumper(Net::DNS::Packet->new("\x00\x00\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x0ehomeassistant3\x05local\x00\x00\xff\x00\x01/homeassistant3 8cb39b13cf3f49a484de32f800b23266\x0c_workstation\x04_tcp\xc0\x1b\x00\xff\x00\x01.homeassistant 8cb39b13cf3f49a484de32f800b23266\xc0V\x00\xff\x00\x01\xc0\x0c\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd5\x9d\xc0&\x00\x10\x80\x01\x00\x00\x00x\x00\x01\x00\xc0&\x00!\x80\x01\x00\x00\x00x\x00\x1c\x00\x00\x00\x00\x00\x00\x0ehomeassistant3\x05local\x00"))
```
