### ISSUE TITLE
2021.06.8 github Actions build Image can't start

### ISSUE THREAD

**Issue by hassiocn** [home-assistant/supervisor#3109]
### Describe the issue you are experiencing

I forked and build 2021.06.8 release. 
when it's 8.27 I built one,the image can start correctly,it was ok.
but 9.8,I built one again,I changed nothing,but the image can't start

error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 8, in <module>
    from supervisor import bootstrap
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 19, in <module>
    from .addons import AddonManager
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 26, in <module>
    from .addon import Addon
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 67, in <module>
    from ..utils.tar import atomic_contents_add, secure_path
  File "/usr/src/supervisor/supervisor/utils/tar.py", line 10, in <module>
    from cryptography.hazmat.primitives import padding
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named '_cffi_backend'

I checked the diff:
pip3 list diff
setuptools         57.1.0
setuptools         58.0.2
typing-extensions  3.10.0.0
typing-extensions  3.10.0.2
wheel              0.36.2
wheel              0.37.0

apk list diff
![image](https://user-images.githubusercontent.com/89345729/132603452-780539c7-e358-4e2b-a85e-00b57ee0b4cf.png)

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

debian-10.10.0

### What version of Home Assistant Core is installed?

core current stable

### Steps to reproduce the issue

1. checkout 2021.06.8 release as branch
2.change build action to my own docker repo
3.manually trigger build action
4. start the image use docker run as /usr/sbin/hassio-supervisor
5. error message
...

### Anything in the Supervisor logs that might be useful for us?

```txt
error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 8, in <module>
    from supervisor import bootstrap
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 19, in <module>
    from .addons import AddonManager
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 26, in <module>
    from .addon import Addon
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 67, in <module>
    from ..utils.tar import atomic_contents_add, secure_path
  File "/usr/src/supervisor/supervisor/utils/tar.py", line 10, in <module>
    from cryptography.hazmat.primitives import padding
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

### Additional information

I checked the diff:
pip3 list diff
setuptools         57.1.0
setuptools         58.0.2
typing-extensions  3.10.0.0
typing-extensions  3.10.0.2
wheel              0.36.2
wheel              0.37.0

apk list diff
![image](https://user-images.githubusercontent.com/89345729/132603452-780539c7-e358-4e2b-a85e-00b57ee0b4cf.png)

**Comment by ludeeus** [comment]
fixed in wheels master branch
