### ISSUE TITLE
Error supervisor after upgrade to 2021.09.2

### ISSUE THREAD

**Issue by SergeyBakinskiy** [home-assistant/supervisor#3146]
### Describe the issue you are experiencing

After the update, the installed addons do not start.

### What is the used version of the Supervisor?

supervisor-2021.09.2

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.4

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

1.Upgrade supervisor fom 9.1 to 9.2
2.We check the running addons and see that they are all turned off
3.We try to run it and catch an error " Failed to start add-on Unknown error, see supervisor logs" 

...

### Anything in the Supervisor logs that might be useful for us?

```txt
File "/usr/src/supervisor/supervisor/addons/addon.py", line 606, in start self.save_persist() File "/usr/src/supervisor/supervisor/addons/addon.py", line 447, in save_persist self.sys_addons.data.save_data() File "/usr/src/supervisor/supervisor/utils/common.py", line 92, in save_data self._data = self._schema(self._data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping cval = cvalue(key_path, value) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping cval = cvalue(key_path, value) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run return self._exec(self._compiled, value, path) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec v = func(path, v) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping cval = cvalue(key_path, value) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run return self._exec(self._compiled, value, path) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 260, in _exec return func(path, v) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 827, in validate_value if data != schema: File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ne__ return not self.__eq__(compareto) File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 97, in __eq__ raise AwesomeVersionCompare("Not a valid AwesomeVersion object") awesomeversion.exceptions.AwesomeVersionCompare: Not a valid AwesomeVersion object 21-09-25 15:40:47 ERROR (MainThread) [aiohttp.server] Error handling request Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request resp = await self._request_handler(request) File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle reraise(*_capture_exception(hub)) File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise raise value File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle response = await old_handle(self, request) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle resp = await handler(request) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl return await handler(request) File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 139, in system_validation return await handler(request) File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 205, in token_validation return await handler(request) File "/usr/src/supervisor/supervisor/api/utils.py", line 65, in wrap_api answer = await method(api, *args, **kwargs) File "/usr/src/supervisor/supervisor/addons/addon.py", line 606, in start self.save_persist() File "/usr/src/supervisor/supervisor/addons/addon.py", line 447, in save_persist self.sys_addons.data.save_data() File "/usr/src/supervisor/supervisor/utils/common.py", line 92, in save_data self._data = self._schema(self._data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping cval = cvalue(key_path, value) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping cval = cvalue(key_path, value) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run return self._exec(self._compiled, value, path) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec v = func(path, v) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping cval = cvalue(key_path, value) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run return self._exec(self._compiled, value, path) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 260, in _exec return func(path, v) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 827, in validate_value if data != schema: File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ne__ return not self.__eq__(compareto) File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 97, in __eq__ raise AwesomeVersionCompare("Not a valid AwesomeVersion object") awesomeversion.exceptions.AwesomeVersionCompare: Not a valid AwesomeVersion object 21-09-25 15:40:54 INFO (MainThread) [supervisor.backups.manager] Found 3 backup files 21-09-25 15:40:54 INFO (MainThread) [supervisor.backups.manager] Found 3 backup files
```

### Additional information

Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:221
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 15:40:20 (6 occurrences)
Last logged: 15:50:44

/addons/core_check_config/start return code 500
/addons/15ef4d2f_esphome/start return code 500
/addons/core_configurator/start return code 500
/addons/core_letsencrypt/start return code 500
/addons/a0d7b954_logviewer/start return code 500

**Comment by johanschelin** [comment]
This is solved with the new 2021.09.3 that's jsut been published.
