### ISSUE TITLE
USB component could not be loaded

### ISSUE THREAD

**Issue by Rindula** [home-assistant/supervisor#3232]
### Describe the issue you are experiencing

When (re-)booting after the latest update (HASS 2021.10.4 and OS Version 6.5) the supervisor won't boot due to an error in the `usb` integration. In my config it's only referenced by `default_config`.

### What is the used version of the Supervisor?

unable to see, probably latest

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.5

### What version of Home Assistant Core is installed?

2021.10.4

### Steps to reproduce the issue

1. Updated from 2021.10.3 to 2021.10.4 via ui
2. Updated OS from 6.4 to 6.5 via ui

### Anything in the Supervisor logs that might be useful for us?

```txt
2021-10-14 13:06:42 ERROR (MainThread) [homeassistant.components.hassio.handler] /homeassistant/options return code 403
2021-10-14 13:06:42 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/options return code 403
2021-10-14 13:06:42 ERROR (MainThread) [homeassistant.components.hassio.handler] /info return code 403
2021-10-14 13:06:42 WARNING (MainThread) [homeassistant.components.hassio] Can't read last version:
2021-10-14 13:06:42 ERROR (MainThread) [homeassistant.components.hassio.handler] /ingress/panels return code 403
2021-10-14 13:06:42 ERROR (MainThread) [homeassistant.components.hassio.addon_panel] Can't read panel info:
2021-10-14 13:06:43 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Supervisor for hassio
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 623, in async_setup_entry
coordinator = HassioDataUpdateCoordinator(hass, entry, dev_reg)
File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 702, in __init__
self.is_hass_os = "hassos" in get_info(self.hass)
TypeError: argument of type 'NoneType' is not iterable
2021-10-14 13:06:51 ERROR (MainThread) [homeassistant.setup] Error during setup of component usb
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
result = await task
File "/usr/src/homeassistant/homeassistant/components/usb/__init__.py", line 69, in async_setup
await usb_discovery.async_setup()
File "/usr/src/homeassistant/homeassistant/components/usb/__init__.py", line 102, in async_setup
await self._async_start_monitor()
File "/usr/src/homeassistant/homeassistant/components/usb/__init__.py", line 114, in _async_start_monitor
info = await system_info.async_get_system_info(self.hass)
File "/usr/src/homeassistant/homeassistant/helpers/system_info.py", line 52, in async_get_system_info
info_object["supervisor"] = info.get("supervisor")
AttributeError: 'NoneType' object has no attribute 'get'
2021-10-14 13:06:53 ERROR (MainThread) [snitun.client.client_peer] Challenge/Response error with SniTun server (0 bytes read on a total of 32 expected bytes)
2021-10-14 13:06:53 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server
2021-10-14 13:06:54 ERROR (MainThread) [homeassistant.components.updater] Unexpected error fetching Home Assistant update data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/usr/src/homeassistant/homeassistant/components/updater/__init__.py", line 82, in check_new_version
newest = core_info["version_latest"]
TypeError: 'NoneType' object is not subscriptable
```

### Additional information

![image](https://user-images.githubusercontent.com/20195655/137310797-bb3feee0-704b-4bd5-8759-4aec0f3ad749.png)
## System Health

error | failed to load: unknown
-- | --

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4825
Installed Version | 1.15.2
Stage | running
Available Repositories | 881
Installed Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 27. Oktober 2021, 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 11
views | 11
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by ludeeus** [comment]
The logs provided are from core (same with the title), add supervisor logs.
