### ISSUE TITLE
exception=ConnectionResetError('Cannot write to closing transport')

### ISSUE THREAD

**Issue by phdelodder** [home-assistant/supervisor#3269]
### Describe the issue you are experiencing

After upgrade Debian 10 to Debain 11, the log is giving every minute : `/usr/src/supervisor/supervisor/api/ingress.py:280> exception=ConnectionResetError('Cannot write to closing transport')>`

### What is the used version of the Supervisor?

supervisor-2021.10.6

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 11 (bullseye)

### What version of Home Assistant Core is installed?

core-2021.10.6

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-10-27 09:04:06 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-687' coro=<_websocket_forward() done, defined at /usr/src/supervisor/supervisor/api/ingress.py:280> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/ingress.py", line 287, in _websocket_forward
    await ws_to.send_bytes(msg.data)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 155, in send_bytes
    await self._writer.send(data, binary=True, compress=compress)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 685, in send
    await self._send_frame(message, WSMsgType.BINARY, compress)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by lbbrhzn** [comment]
I get similar errors now, after upgrading to 2012.12.3:

```
21-12-20 19:54:01 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-631' coro=<_websocket_forward() done, defined at /usr/src/supervisor/supervisor/api/ingress.py:280> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/ingress.py", line 287, in _websocket_forward
    await ws_to.send_bytes(msg.data)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 156, in send_bytes
    await self._writer.send(data, binary=True, compress=compress)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 688, in send
    await self._send_frame(message, WSMsgType.BINARY, compress)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```
