### ISSUE TITLE
HA core keep crashing  in supervisor installation 

### ISSUE THREAD

**Issue by ssinghj** [home-assistant/supervisor#3345]
### Describe the issue you are experiencing

Hi, 
After installing the HA supervised while following the official way on Debian 11 on Rasberry Pi 4 B 4GB, the HA core is keep crashing. I tried everything, eg. reverting HA core to the previous version and re-flashing on Debian 10. But every time i get the same result and after installation rest, all other containers get up withing any problem and HA core is crashing. 
Here are the logs which i captured from the supervisor container

### What is the used version of the Supervisor?

supervisor-1.0.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

11

### What version of Home Assistant Core is installed?

11.05

### Steps to reproduce the issue

1. 
Installed HA supervisor while following the official guide
https://github.com/home-assistant/supervised-installer
2.
After successful completion of installation, all containers got up except HA core

### Anything in the Supervisor logs that might be useful for us?

```txt
21-12-04 23:57:24 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-12-04 23:57:24 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-12-04 23:57:24 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-12-04 23:57:24 INFO (MainThread) [supervisor.host.services] Updating service information
21-12-04 23:57:24 INFO (MainThread) [supervisor.host.network] Updating local network information
21-12-04 23:57:25 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-12-04 23:57:25 INFO (MainThread) [supervisor.host.manager] Host information reload completed
21-12-05 00:01:14 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse
21-12-05 00:01:15 INFO (SyncWorker_3) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/raspberrypi4-64-homeassistant with version 2021.11.3
21-12-05 00:01:15 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
**21-12-05 00:01:20 ERROR (MainThread) [supervisor.homeassistant.core] Home Assistant ha
```

### Additional information

I also tried with 'ha' commands to restart, rebuild the core but it didn't work out

**Comment by ssinghj** [comment]
Here are further errors i captured while trying to rebuild the HA core with 'ha' command.

'''
21-12-08 09:50:03 ERROR (MainThread) [supervisor.homeassistant.core] Home Assistant has crashed!
21-12-08 09:50:18 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-32' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=HomeAssistantCrashError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 198, in _watchdog_homeassistant_docker
    await self.sys_homeassistant.core.rebuild()
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 317, in rebuild
    await self._start()
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 270, in _start
    await self._block_till_run(self.sys_homeassistant.version)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 453, in _block_till_run
    raise HomeAssistantCrashError()
supervisor.exceptions.HomeAssistantCrashError
'''
