### ISSUE TITLE
It seems Supervisor randomly crushes

### ISSUE THREAD

**Issue by damiano75** [home-assistant/supervisor#3405]
### Describe the issue you are experiencing

It seems Supervisor stops to works randomly, then HA loses connection and also SSH connection is lost. Raspberry Pi3 completely stuck, I need to unplug the power supply to reboot the system. I changed the sdhc card, reinstalled HA OS from scratch and restored the backup

![image](https://user-images.githubusercontent.com/47896789/149624562-e5d732c4-fe2b-4fef-af53-d62e97a35d61.png)

### What is the used version of the Supervisor?

supervisor-2021.12.2

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 7.1

### What version of Home Assistant Core is installed?

core-2021.12.9

### Steps to reproduce the issue

1. It seems sometimes I have the issue starting some add-on
2. Sometimes just when I try to open the Supervisor page
3. Sometimes when I changed some cards in Lovelace front-end
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-01-15 15:05:18 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-277' coro=<HomeAssistantWebSocket.async_send_message() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:210> exception=TypeError('Received message 8:1000 is not str')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 212, in async_send_message
    if not await self._can_send(message):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 190, in _can_send
    self._client = await self._get_ws_client()
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 171, in _get_ws_client
    client = await WSClient.connect_with_auth(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 147, in connect_with_auth
    auth_ok_message = await client.receive_json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 290, in receive_json
    data = await self.receive_str(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 275, in receive_str
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not str")
TypeError: Received message 8:1000 is not str
```

**Comment by ykuijs** [comment]
Could this be related to my issue in the Core repo? https://github.com/home-assistant/core/issues/64323

**Comment by damiano75** [comment]
HA restarts about every two hours, in home-assistant.log.1:

```
2022-03-17 10:34:16 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /core/stats request
2022-03-17 10:34:16 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /core/stats - 
2022-03-17 10:34:16 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /supervisor/stats request
2022-03-17 10:34:16 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /supervisor/stats - 
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_ssh/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_configurator/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/a0d7b954_nginxproxymanager/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/cebe7a76_hassio_google_drive_backup/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_duckdns/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_samba/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/a0d7b954_logviewer/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_mariadb/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/a0d7b954_nut/stats request
2022-03-17 10:34:46 WARNING (MainThread) [homeassistant.components.hassio] Can't read Supervisor data: 
2022-03-17 10:35:00 ERROR (MainThread) [homeassistant.components.nut] Error fetching NUT resource status data: Error fetching UPS state
```

In the SU logs:
```
22-03-17 10:33:41 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-03-17 10:34:47 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-03-17 10:34:55 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-03-17 10:34:58 WARNING (MainThread) [supervisor.updater] Can't fetch versions from https://version.home-assistant.io/stable.json: Timeout
22-03-17 10:35:00 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-03-17 10:35:05 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
22-03-17 10:35:23 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-03-17 10:35:23 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-03-17 10:35:33 INFO (MainThread) [supervisor.api.middleware.security] /core/logs access from core_ssh
22-03-17 10:35:54 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-03-17 10:35:54 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-03-17 10:36:02 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Home Assistant Docker!
22-03-17 10:36:02 INFO (SyncWorker_7) [supervisor.docker.interface] Starting homeassistant
22-03-17 10:36:03 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-03-17 10:36:37 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-03-17 10:36:38 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-17 10:38:15 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
```

I upgrade HA to 2022.3.5, Supervisor to 2022.03.4 and SO to 7.5 but issue is still present.
It is very annoying, also because it is difficult to debug it.
I tried to stop NUT addon, but it is not the cause.

Could you please help us?

**Comment by damiano75** [comment]
> Could this be related to my issue in the Core repo? [home-assistant/core#64323](https://github.com/home-assistant/core/issues/64323)

Maybe, it is very difficult to debug

**Comment by damiano75** [comment]
From the HOST logs:

```
[ 7485.536504] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=aa496eb8b1ba4ee6da9d904259b4279eee7fe9d93a0f499ef52aa4c7f72e3095,mems_allowed=0,global_oom,task_memcg=/docker/aa496eb8b1ba4ee6da9d904259b4279eee7fe9d93a0f499ef52aa4c7f72e3095,task=python3,pid=5453,uid=0
[ 7485.537079] Out of memory: Killed process 5453 (python3) total-vm:1399268kB, anon-rss:490280kB, file-rss:212kB, shmem-rss:0kB, UID:0 pgtables:2468kB oom_score_adj:0
[ 7485.834447] oom_reaper: reaped process 5453 (python3), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

Could it be a RAM problem?

**Comment by damiano75** [comment]
It seems in my case (Raspberry Pi 3B+ 1G RAM) I found a workaround: I installed the 32bit image instead of 64bit, even if this one is recommended, and now HA and Supervisor are very stable
