### ISSUE TITLE
awesomeversion.exceptions.AwesomeVersionCompareException: Not a valid AwesomeVersion object

### ISSUE THREAD

**Issue by bnounours** [home-assistant/supervisor#3453]
### Describe the issue you are experiencing

Hello,

After a power cut, my home assistant did not work at all, not web interface. 

After investigation I see that the supervisor docker is no more present.
I launch `hassos-supervisor` command and the docker image is pulled and the docker started.
Unfortunately the docker continuously fail to start, delete it self, retry ...

I manage to get the log and find this stack:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 43, in <module>
    loop.run_until_complete(coresys.core.connect())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/supervisor/supervisor/core.py", line 80, in connect
    if self.sys_config.version == self.sys_supervisor.version:
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 133, in __eq__
    raise AwesomeVersionCompareException("Not a valid AwesomeVersion object")
awesomeversion.exceptions.AwesomeVersionCompareException: Not a valid AwesomeVersion object
```
I did not find issue related to this error nor any clue on google.
I decided to have a look into the code and find that the version value are read from the config.json file.
I then open this file and found that for some reason the version = null

I changed it to "2022.01.1" and now the supervisor starts !, but it is still in dangling mode :(

Now I see in the observer that it is not supported
```
Supervisor: | Connected
-- | --
Supported: | Unsupported
Healthy: | Healthy
```

### What is the used version of the Supervisor?

unknow, system tab doesn't work. The docker image tag is 2022.01.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

unknow, system tab doesn't work

### What version of Home Assistant Core is installed?

2022.2.5

### Steps to reproduce the issue

1. change the value of version in config.json to null
2. stop supervisor
3. start supervisor
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-02-17 23:21:50 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-02-17 23:21:50 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
22-02-17 23:21:50 ERROR (MainThread) [supervisor.homeassistant.api] Can't update Home Assistant access token!
...
22-02-17 23:21:50 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found unsupported images: {'ghcr.io/home-assistant/raspberrypi3-64-homeassistant'} (more-info: https://www.home-assistant.io/more-info/unsupported/software)
```

### Additional information

Bad config.json file
```
{
  "timezone": "Europe/Paris",
  "addons_custom_list": [
    "https://github.com/hassio-addons/repository",
    "https://github.com/haberda/hassio_addons"
  ],
  "wait_boot": 5,
  "debug": false,
  "debug_block": false,
  "logging": "info",
  "last_boot": "2022-02-17T21:00:05",
  "version": null,
  "diagnostics": null
}
```
Good one:
```
{
  "timezone": "Europe/Paris",
  "addons_custom_list": [
    "https://github.com/hassio-addons/repository",
    "https://github.com/haberda/hassio_addons"
  ],
  "wait_boot": 5,
  "debug": false,
  "debug_block": false,
  "logging": "info",
  "last_boot": "2022-02-17T21:00:05",
  "version": "2022.02.dev1701",
  "diagnostics": null
}
```

**Comment by bnounours** [comment]
When the supervisor restarted, I rebooted the rpi and now it seems to be ok
