### ISSUE TITLE
supervisor asyncio repeated errors 

### ISSUE THREAD

**Issue by tammeryousef1006** [home-assistant/supervisor#3485]
### Describe the issue you are experiencing

i always get these errors repeated in every 5 min or less

22-03-04 16:16:00 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2015' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 417, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 473, in watchdog_application
    port = self.ports.get(f"{t_port}/tcp", t_port)
AttributeError: 'NoneType' object has no attribute 'get'

### What is the used version of the Supervisor?

supervisor-2022.01.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 7.4

### What version of Home Assistant Core is installed?

core-2022.3.1

### Steps to reproduce the issue

1.
2.
3.
...
tried to reload and restart supervisor but the problem shows up after and never stop

### Anything in the Supervisor logs that might be useful for us?

```txt
22-03-04 16:10:00 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1767' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 417, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 473, in watchdog_application
    port = self.ports.get(f"{t_port}/tcp", t_port)
AttributeError: 'NoneType' object has no attribute 'get'
22-03-04 16:12:00 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1884' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 417, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 473, in watchdog_application
    port = self.ports.get(f"{t_port}/tcp", t_port)
AttributeError: 'NoneType' object has no attribute 'get'
22-03-04 16:14:00 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1972' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 417, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 473, in watchdog_application
    port = self.ports.get(f"{t_port}/tcp", t_port)
AttributeError: 'NoneType' object has no attribute 'get
```

**Comment by tammeryousef1006** [comment]
i found a solution to turn off watchdog for the addon (RTSPtoWeb - WebRTC)
