### ISSUE TITLE
Can't restore addons from a backup in Supervisor 2022.03.2

### ISSUE THREAD

**Issue by sermayoral** [home-assistant/supervisor#3497]
### Describe the issue you are experiencing

Cannot restore any addon from a backup when the addon is not installed on the system

### What is the used version of the Supervisor?

2022.03.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian Bullseye (aarch64)

### What version of Home Assistant Core is installed?

2022.3.3

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-03-09 21:42:59 INFO (MainThread) [supervisor.addons.addon] Restore config for addon a0d7b954_vscode
22-03-09 21:43:00 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'a0d7b954_vscode'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'a0d7b954_vscode'
22-03-09 21:43:00 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on a0d7b954_vscode: 
22-03-09 21:44:54 INFO (MainThread) [supervisor.addons.addon] Restore config for addon a0d7b954_unifi
22-03-09 21:44:54 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'a0d7b954_unifi'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'a0d7b954_unifi'
22-03-09 21:44:54 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on a0d7b954_unifi: 
22-03-09 21:44:56 INFO (MainThread) [supervisor.addons.addon] Restore config for addon a0d7b954_nginxproxymanager
22-03-09 21:44:56 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'a0d7b954_nginxproxymanager'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'a0d7b954_nginxproxymanager'
22-03-09 21:44:56 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on a0d7b954_nginxproxymanager: 
22-03-09 21:44:56 INFO (MainThread) [supervisor.addons.addon] Restore config for addon 5c53de3b_esphome
22-03-09 21:44:56 ERROR (MainThread) [supervisor.jobs] Unhandled exception: '5c53de3b_esphome'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: '5c53de3b_esphome'
22-03-09 21:44:56 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on 5c53de3b_esphome: 
22-03-09 21:44:56 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_mosquitto
22-03-09 21:44:56 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'core_mosquitto'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 367, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 832, in restore
    restore_image = self._image(data[ATTR_SYSTEM])
  File "/usr/src/supervisor/supervisor/addons/model.py", line 629, in _image
    return config[ATTR_IMAGE].format(arch=self.arch)
  File "/usr/src/supervisor/supervisor/addons/model.py", line 509, in arch
    if ATTR_IMAGE in self.data:
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 157, in data
    return self.sys_addons.data.system[self.slug]
KeyError: 'core_mosquitto'
22-03-09 21:44:56 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on core_mosquitto:
```

**Comment by crhass** [comment]
I am getting this too, after installing supervisor 2022.03.2 and losing access to my supervisor page, I prepared a new rpi3 with 64bit image. I restored my full snapshot and everything restored except all the add-ons.

I thought this was because I moved from 32 to 64bit but maybe not?

**Comment by sermayoral** [comment]
> I am getting this too, after installing supervisor 2022.03.2 and losing access to my supervisor page, I prepared a new rpi3 with 64bit image. I restored my full snapshot and everything restored except all the add-ons.
> 
> I thought this was because I moved from 32 to 64bit but maybe not?

No. I have the same problem from 64 to 64. It's a supervisor problem

**Comment by nodomain** [comment]
Same here. Can I somehow install an older supervisor version? 

Bad timing, I wanted to re-install due to issues with my storage :(

**Comment by sermayoral** [comment]
I found that, if you install the addon on the new system, without starting and configuring anything on the addon, you can restore the addon from a backup to import your previous configuration and it works. The problem is restoring an addon when it doesn't exist on your system (that is a normal behaviour when you install a new system)

**Comment by crhass** [comment]
> I found that, if you install the addon on the new system, without starting and configuring anything on the addon, you can restore the addon from a backup to import your previous configuration and it works. The problem is restoring an addon when it doesn't exist on your system (that is a normal behaviour when you try to restore a full backup)

Does this work around restore the folders?

**Comment by sermayoral** [comment]
> > I found that, if you install the addon on the new system, without starting and configuring anything on the addon, you can restore the addon from a backup to import your previous configuration and it works. The problem is restoring an addon when it doesn't exist on your system (that is a normal behaviour when you try to restore a full backup)
> 
> Does this work around restore the folders?

No. For the folders you have to unzip the backup and copy the folders manually to your home assistant instance :-(

**Comment by johncoles** [comment]
Can confirm that for me atleast installing the add-ons then rerunning the restore works.

**Comment by johncoles** [comment]
> The error seems clear. Try to find some data of the installed addons (I think the slug). Since the addon is not installed, it throws an unhandled exception.
> 
Indeed, though it might be nice to point the user in the direction of "Have you installed the add-on?"

**Comment by Varming73** [comment]
After upgrading the supervisor and restoring all my Zigbee devices are gone in the Zigbee2mqtt add in. I guess that is related to this somehow. Got no lights in the house now :(

**Comment by janick** [comment]
> 

It may be related to this one: https://github.com/home-assistant/core/issues/67780

I hope not because I'm planning to install Zigbee2mqtt to see if it works around the ZHA problem.

**Comment by sermayoral** [comment]
@mdegat01 please, don't forget to do a release as soon as possible. Backup and restore is not still possible for us with the actual release...

**Comment by ocalvo** [comment]
[I am seeing the same](https://github.com/home-assistant/supervisor/issues/3512)

**Comment by HarvsG** [comment]
```
22-03-13 11:16:48 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files
22-03-13 11:16:48 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files
22-03-13 11:16:56 INFO (MainThread) [supervisor.backups.manager] Full-Restore 1331b368 start
22-03-13 11:16:56 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' stopping 0 add-ons
22-03-13 11:16:56 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping homeassistant application
22-03-13 11:17:14 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' stopping 0 add-ons
22-03-13 11:17:14 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' stopping 0 add-ons
22-03-13 11:17:14 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' stopping 0 add-ons
22-03-13 11:17:50 INFO (MainThread) [supervisor.backups.manager] Restoring 1331b368 Docker config
22-03-13 11:17:50 INFO (MainThread) [supervisor.backups.manager] Restoring 1331b368 folders
22-03-13 11:17:50 WARNING (MainThread) [supervisor.backups.backup] Can't restore folder share: _restore() takes 0 positional arguments but 1 was given
22-03-13 11:17:50 WARNING (MainThread) [supervisor.backups.backup] Can't restore folder addons/local: _restore() takes 0 positional arguments but 1 was given
22-03-13 11:17:50 WARNING (MainThread) [supervisor.backups.backup] Can't restore folder ssl: _restore() takes 0 positional arguments but 1 was given
22-03-13 11:17:50 WARNING (MainThread) [supervisor.backups.backup] Can't restore folder media: _restore() takes 0 positional arguments but 1 was given
22-03-13 11:17:50 INFO (MainThread) [supervisor.backups.manager] Restoring 1331b368 Home Assistant Core
22-03-13 11:17:50 ERROR (MainThread) [supervisor.homeassistant.module] Can't read tarfile <securetar.SecureTarFile object at 0x7f8e7889a0>: not a gzip file
22-03-13 11:17:50 ERROR (MainThread) [supervisor.backups.manager] Restore 1331b368 error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 378, in restore
    await self.sys_run_in_executor(_extract_tarfile)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 374, in _extract_tarfile
    with tar_file as backup:
  File "/usr/local/lib/python3.9/site-packages/securetar/__init__.py", line 82, in __enter__
    self._tar = tarfile.open(fileobj=self, mode=self._tar_mode, dereference=False)
  File "/usr/local/lib/python3.9/tarfile.py", line 1639, in open
    stream = _Stream(name, filemode, comptype, fileobj, bufsize)
  File "/usr/local/lib/python3.9/tarfile.py", line 370, in __init__
    self._init_read_gz()
  File "/usr/local/lib/python3.9/tarfile.py", line 477, in _init_read_gz
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 252, in _do_restore
    task_hass = await backup.restore_homeassistant()
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 480, in restore_homeassistant
    await self.sys_homeassistant.restore(homeassistant_file)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 380, in restore
    raise HomeAssistantError(
supervisor.exceptions.HomeAssistantError: Can't read tarfile <securetar.SecureTarFile object at 0x7f8e7889a0>: not a gzip file
22-03-13 11:17:50 INFO (SyncWorker_2) [supervisor.docker.interface] Starting homeassistant
22-03-13 11:17:51 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
```
