### ISSUE TITLE
 Supervisor Reporting Unsupported Installation 

### ISSUE THREAD

**Issue by lawrencelnm** [home-assistant/supervisor#3503]
### Describe the issue you are experiencing

Hi there,

I don't know where to go to ask for help. 

I was trying to update Node-Red plugin today with latest version but wasn't successful. I then went through to check my system and noticed my Supervisor (under System) having a "Your Installation is Unhealthy"
Eventually restarting the Supervisor clears it, and I was able to update Node Red plugin.

I checked again later, and the error has returned.

I have no idea what is causing this issue as my Home Assistant has been running "Healthy" for a year now. I haven't installed any additional plugins, of software from HACS the last few weeks. 

The only thing I did is move to the recent Core release. I've updated to core-2022.3.3 around 3 days ago.

Can someone help me out? Or assist me in narrowing down what exactly is "Unhealthy" here. Clicking the error just brings me to a generic home assistant link telling me to reinstall my home assistant entirely - not helpful.

I have tried restoring from the full backup I've created 3 days ago, prior to upgrade to 2022.3.3. However the whole backup function in home assistant is not working. I believe this is a bug introduced in 2022.3.2. 

![image](https://user-images.githubusercontent.com/83073450/157646912-51880c92-18c4-4ec6-b31e-06435c503cdd.png)

### What is the used version of the Supervisor?

supervisor-2022.03.2

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 7.4

### What version of Home Assistant Core is installed?

core-2022.3.3

### Steps to reproduce the issue

I don't know.

### Anything in the Supervisor logs that might be useful for us?

```txt
22-03-10 21:31:38 INFO (MainThread) [supervisor.backups.manager] Found 35 backup files
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/9cc7cd2c.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/d19e5213.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/f4cb0762.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/cfc50ffa.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/86df78c1.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/4d240515.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/7736f4da.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/f5842272.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/6873e6e3.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/ca4b1d78.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/e027d358.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/9ce02fc2.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/f21544ec.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/8abdf37c.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/2cea76d2.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/534bfde8.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/70d84633.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/60233f08.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/7d9e1113.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/9f0ca59a.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/babcad16.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/99534f5c.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/636b28cc.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/4d352ae3.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/d18ca9bb.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/595d9bd8.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/3e9981b6.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/c64cc7f4.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/9d18c276.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:38 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/backup/bcd4b386.tar: expected boolean for dictionary value @ data['protected']. Got '3'
22-03-10 21:31:47 INFO (MainThread) [supervisor.jobs] 'BackupManager.do_restore_full' blocked from execution, system is not healthy
```

**Comment by darkponay** [comment]
Hi,
I have the same problem on Odroid N2 with eMMC, but i don't have HACS installed. Here are my logs:
```
22-03-10 12:16:00 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-10 12:16:00 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.FREEZE
22-03-10 12:16:10 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
22-03-10 12:16:19 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
22-03-10 12:16:19 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 90ff4242 completed
22-03-10 12:16:19 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2022.3.3
22-03-10 12:16:19 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/odroid-n2-homeassistant:2022.3.2 to ghcr.io/home-assistant/odroid-n2-homeassistant:2022.3.3
22-03-10 12:16:19 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/odroid-n2-homeassistant with tag 2022.3.3.
22-03-10 12:16:39 CRITICAL (SyncWorker_3) [supervisor.docker.interface] Pulled image ghcr.io/home-assistant/odroid-n2-homeassistant:2022.3.3 failed on content-trust verification!
22-03-10 12:16:39 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed
22-03-10 12:16:47 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug edec6fbd
22-03-10 12:16:47 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
22-03-10 12:17:07 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
22-03-10 12:17:08 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug edec6fbd completed
22-03-10 12:17:08 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2022.3.3
22-03-10 12:17:08 INFO (SyncWorker_2) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/odroid-n2-homeassistant:2022.3.2 to ghcr.io/home-assistant/odroid-n2-homeassistant:2022.3.3
22-03-10 12:17:08 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/odroid-n2-homeassistant with tag 2022.3.3.
22-03-10 12:18:22 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 229, in update
    await _update(version)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 207, in _update
    await self.instance.update(
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
asyncio.exceptions.TimeoutError
```

**Comment by frenck** [comment]
@darkponay You are experiencing a different issue, please follow <https://github.com/home-assistant/supervisor/issues/3495#issuecomment-1063909657> for that one.

**Comment by andrict** [comment]
Hi
I am getting the same warnings / errors. Running the same code versions as @lawrencelnm posted.
You are running an unsupported installation LEARN MORE
Your installation is unhealthy LEARN MORE

Part of Log entries
22-03-10 21:42:27 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 21:42:27 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-03-10 21:42:27 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-03-10 21:42:35 WARNING (MainThread) [supervisor.resolution.evaluations.base] System detect unauthorized source code modifications. (more-info: https://www.home-assistant.io/more-info/unsupported/source_mods)
22-03-10 21:42:35 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-10 21:42:35 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy
22-03-10 21:42:37 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary

**Comment by frenck** [comment]
@andrict You are experiencing a different issue, please follow <https://github.com/home-assistant/supervisor/issues/3495#issuecomment-1063909657> for that one.

**Comment by frenck** [comment]
Closing this issue as a duplicate, please follow: https://github.com/home-assistant/supervisor/issues/3495#issuecomment-1063909657

**Comment by jollsterep** [comment]
Similar issue here, have updated Supervisor to latest version (stable) today, then I wanted to update Core to 2022.03.3 but got error as mentioned in top post.
![image](https://user-images.githubusercontent.com/84158454/157654230-637bbc63-28f0-4c65-8919-a768ab6edd4e.png)

Get same error when trying to update Node-red
No Backups are available anymore (except for the one exported to google drive on 8th of march)
I can try to restore if I got the time this week.

**Comment by lawrencelnm** [comment]
> Similar issue here, have updated Supervisor to latest version (stable) today, then I wanted to update Core to 2022.03.3 but got error as mentioned in top post. ![image](https://user-images.githubusercontent.com/84158454/157654230-637bbc63-28f0-4c65-8919-a768ab6edd4e.png)
> 
> Get same error when trying to update Node-red No Backups are available anymore (except for the one exported to google drive on 8th of march) I can try to restore if I got the time this week.

Thank you! I thought I was going insane and I'm really freaking out whether an intruder has hacked into my home assistant based on the link from the "LEARN MORE".

![image](https://user-images.githubusercontent.com/83073450/157654838-d6511d64-23fe-4aa7-8304-01158f9a38e9.png)

**Comment by frenck** [comment]
Could you guys please stop posting unrelated content and follow the linked issue?

Thanks! 👍
