### ISSUE TITLE
Strange behaviour of System Autofix

### ISSUE THREAD

**Issue by martymarty004** [home-assistant/supervisor#3572]
### Describe the issue you are experiencing

After updating to the latest version of Home Assistant, the following error started appearing once in a while.

This doesn't seem to cause any actual problems with my installation.

### What is the used version of the Supervisor?

supervisor-2022.04.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

7.6

### What version of Home Assistant Core is installed?

core-2022.4.3

### Steps to reproduce the issue

1. Update HA to core-2022.4.x (from core-2022.3.x)
2. Update Supervisor to supervisor-2022.04.0
3. The following error appears every couple of hours

### Anything in the Supervisor logs that might be useful for us?

```txt
22-04-14 23:19:24 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-04-14 23:19:24 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-04-14 23:19:24 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-04-14 23:19:24 INFO (MainThread) [supervisor.resolution.fixups.store_execute_reset] Reset corrupt Store: core
22-04-14 23:19:24 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/home-assistant/addons repository
22-04-14 23:19:25 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-04-14 23:19:26 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
22-04-14 23:19:26 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
22-04-14 23:19:26 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
```

### Additional information

There is a previous error in the logs, but I think it's a simple connection failure. 
Here it is:
```txt
22-04-14 23:07:21 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-04-14 23:07:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-04-14 23:07:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-04-14 23:07:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
22-04-14 23:07:21 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: expected flush after ref listing'.
22-04-14 23:07:22 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-13461' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 750, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: expected flush after ref listing'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
```

**Comment by mdegat01** [comment]
Yea I've noticed this as well. I had it on my list to look into but I'm wondering if its related to #3567 . It looks like the hassio component is forcing a full update check every 5 minutes. Which means every HA user with supervisor is cloning that core addons repo every 5 minutes. I'm thinking github may not like that.

**Comment by mdegat01** [comment]
Duplicate #3561
