### ISSUE TITLE
Backup impossible since core-2022.4.4 (or core-2022.4.3)

### ISSUE THREAD

**Issue by puttemanp** [home-assistant/supervisor#3576]
### Describe the issue you are experiencing

While trying to create my regular backup I noticed that the latest backup available was the one created when upgrading to core-2022.4.2, 2 days ago.
When I upgrade I always select to create a backup. So I guess that the issue popped up in core-2022.4.3.
When I try to create a full or partial backup, it fails after a while.

### What is the used version of the Supervisor?

supervisor-2022.04.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 7.6

### What version of Home Assistant Core is installed?

core-2022.4.4

### Steps to reproduce the issue

1.Create full or partial backup
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-04-15 12:49:44 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 3729ca1f
22-04-15 12:49:44 INFO (MainThread) [supervisor.backups.manager] Backing up 3729ca1f store Add-ons
22-04-15 12:49:44 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_appdaemon
22-04-15 12:49:44 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_appdaemon
22-04-15 12:49:44 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_configurator
22-04-15 12:49:44 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_configurator
22-04-15 12:49:44 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_grafana
22-04-15 12:49:44 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_grafana
22-04-15 12:49:44 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_influxdb
22-04-15 12:52:45 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-04-15 12:52:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-04-15 12:52:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-04-15 12:52:45 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: Could not read from remote repository.'.
22-04-15 12:52:45 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-16788' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 750, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'fatal: Could not read from remote repository.'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
```

**Comment by mdegat01** [comment]
The error you're showing isn't related to backups. You're showing the same error seen in #3561 . Can you show the error you're seeing when you try to take a backup?
