### ISSUE TITLE
Upgrading Supervisor to 2022.05.0 cause Zoneminder integration connection to stop working

### ISSUE THREAD

**Issue by AndersWestman** [home-assistant/supervisor#3626]
### Describe the issue you are experiencing

After upgrading Supervisor to 2022.05.0 the connection to Zoneminder server is lost.
Error message in core-logs changes slightly after upgrading core from 2022.4.7 to 2022.5.0 or 2022.5.1.

**log core 2022.4.7**
`Logger: zoneminder.zm
Source: /usr/local/lib/python3.9/site-packages/zoneminder/zm.py:141
First occurred: 3 maj 2022 21:48:08 (17033 occurrences)
Last logged: 09:57:37

Unable to connect to ZoneMinder
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5e3851bf10>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='zoneminder.local', port=80): Max retries exceeded with url: /zm/api/host/daemonCheck.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e3851bf10>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/zoneminder/zm.py", line 115, in _zm_request
    req = requests.request(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='zoneminder.local', port=80): Max retries exceeded with url: /zm/api/host/daemonCheck.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e3851bf10>: Failed to establish a new connection: [Errno -2] Name does not resolve'))`

**log core 2022.5.0**
`Logger: homeassistant.setup
Source: components/zoneminder/__init__.py:78
First occurred: 5 maj 2022 22:13:01 (1 occurrences)
Last logged: 5 maj 2022 22:13:01

Error during setup of component zoneminder
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8a07ebf4f0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='zoneminder.local', port=80): Max retries exceeded with url: /zm/api/host/login.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8a07ebf4f0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zoneminder/__init__.py", line 78, in setup
    success = zm_client.login() and success
  File "/usr/local/lib/python3.9/site-packages/zoneminder/zm.py", line 53, in login
    req = requests.post(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='zoneminder.local', port=80): Max retries exceeded with url: /zm/api/host/login.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8a07ebf4f0>: Failed to establish a new connection: [Errno -3] Try again'))`

### What is the used version of the Supervisor?

2022.5.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.10.108

### What version of Home Assistant Core is installed?

2022.4.7 to 2022.5.1

### Steps to reproduce the issue

1. Upgrade Supervisor from 2022.4.0 to 2022.5.0
2. After update the connection to Zoneminder fails

### Anything in the Supervisor logs that might be useful for us?

```txt
No errors in Supervisor logs.
```

### Additional information

Rolling back VM snapshot to point before update Supervisor makes it work again.
Upgrade Supervisor from 2022.4.0 to 2022.5.0 on the working rolled back installation reproduce the same error.
...

**Comment by mdegat01** [comment]
I see the address you're trying to use is `zoneminder.local`. Do you run a local dns server by any chance? If so did you have a DNS rewrite entry in there for `zoneminder.local`? Or was your device broadcasting that name via mdns?

**Comment by AndersWestman** [comment]
I use Pi-hole as dns server and the adress zoneminder.local/zm is working to directly access Zoneminder in web browser.
The zoneminder integration works again with zoneminder.local if I roll back to Supervisor 2022.4, but not after update to 2022.5.

**Comment by AndersWestman** [comment]
Interesting, I changed the config and replaced my local adress zoneminder.local with the IP, and then the integration starts working again.
Looks like 2022.4 for some reason is able to handle zoneminder.local but 2022.5 is not?

**Comment by mdegat01** [comment]
So in 2022.5 [plugin-dns](https://github.com/home-assistant/plugin-dns) (which is what all containers managed by supervisor use for DNS) stopped trying to resolve mdns (`.local` names) and LLMNR (single-name hostnames without a TLD) queries itself. Instead it asks systemd-resolved on the host to answer those queries and returns whatever it tells us.

Systemd-resolved [refuses to forward multicast queries](https://github.com/systemd/systemd/blob/2afb2f4a9d6a497dfbe1983fbe1bac297a8dc52b/src/resolve/resolved-dns-scope.c#L797-L813) such as these because resolvers should never be the ones answering multicast queries. MDNS and LLMNR use a different system entirely to resolve queries and forwarding these types of queries to resolvers is considered a security risk as it risks leaking internal names to external resolvers.

So this won't work anymore. `.local` is reserved for mdns so the only way to use a `.local` name is to have your system broadcast its name properly via mdns. If you don't want to do that or its not possible then you'll have to use a different hostname. `.lan` or `.home.arpa` are common choices for LAN-internal TLD that aren't reserved for special use like `.local`

**Comment by AndersWestman** [comment]
Thank you for the detalied explanation.
I have misunderstand the domain naming that .local was a proper one to use in a local lan.
Just changing to zoneminder.lan works perfect.
Thanks again for clearing things out!
