### ISSUE TITLE
Failed upgrade from 7.4 to 7.6 failed to call service update home assistant

### ISSUE THREAD

**Issue by aelharda** [home-assistant/supervisor#3654]
### Describe the issue you are experiencing

Logs attached

### What is the used version of the Supervisor?

7.4

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.10.92-v8

### What version of Home Assistant Core is installed?

core-2022.5.5

### Steps to reproduce the issue

1.None
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:214
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: May 22, 2022, 4:24:04 PM (5 occurrences)
Last logged: 8:23:01 AM

[547571562432] Error updating Home Assistant Operating System: Unknown error, see supervisor
[547636286320] Error updating Home Assistant Operating System: Unknown error, see supervisor
[547568722800] Error updating Home Assistant Operating System: Unknown error, see supervisor
[547535241376] Error updating Home Assistant Operating System: Unknown error, see supervisor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 212, in async_install
    await async_update_os(self.hass, version)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 47, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Unknown error, see supervisor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 214, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Operating System: Unknown error, see supervisor
```

**Comment by mdegat01** [comment]
That's not the supervisor logs. Can you share the supervisor logs?
