### ISSUE TITLE
Can't update HA Supervisor from 2022.5.3 to 2022.6.2 

### ISSUE THREAD

**Issue by KaportsevIA** [home-assistant/supervisor#3716]
### Describe the issue you are experiencing

Can't update HomeAssistant Supervisor to 2022.6.2

Error in log:
`Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:256
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 13:52:20 (2 occurrences)
Last logged: 13:53:02

[140331326428208] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.06.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.06.2&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: Temporary failure in name resolution")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 254, in async_install
    await async_update_supervisor(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 47, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.06.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.06.2&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: Temporary failure in name resolution")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 256, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.06.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.06.2&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: Temporary failure in name resolution")`

### What is the used version of the Supervisor?

supervisor-2022.05.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

5.13.0-52-generic

### What version of Home Assistant Core is installed?

core-2022.6.7

### Steps to reproduce the issue

Just press "Install" in "Update" Window

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:256
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 13:52:20 (2 occurrences)
Last logged: 13:53:02

[140331326428208] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.06.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.06.2&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: Temporary failure in name resolution")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 254, in async_install
    await async_update_supervisor(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 47, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.06.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.06.2&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: Temporary failure in name resolution")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 256, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.06.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.06.2&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: Temporary failure in name resolution")
```

### Additional information

<html>
<body>

Операционная система хоста | Ubuntu 20.04.4 LTS
-- | --
Канал обновлений | stable
Версия Supervisor | supervisor-2022.05.3
Agent Version | 1.2.2
Версия Docker | 20.10.12

</body>
</html>

**Comment by derhappy** [comment]
I was able to update, but HA didn't start anymore after system reboot running Home Assistant Supervised.
I rolled back based on the description from a HA forum post and it's running again. 
Unfortunately I could not find any logs since nothing except the observer was starting. The observer/logs just answered with a 403 Forbidden.

**Comment by KaportsevIA** [comment]
Debian and Ubuntu are basically the same OS. HA is installed on Ubuntu in the same way as on Debian

**Comment by KaportsevIA** [comment]
Yes

**Comment by KaportsevIA** [comment]
error is:

> [139731797399536] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.06.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.06.2&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: **Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: Temporary failure in name resolution")**

**Comment by frenck** [comment]
> Get "[ghcr.io/v2](https://ghcr.io/v2/)": dial tcp: lookup ghcr.io: Temporary failure in name resolution

That is not an issue we can do anything about. Your system (OS) and Docker setup are not able to resolve the `ghcr.io` hostname and thus not able to download an update from the web.

Please make sure you are connected to the internet, check your network settings, and especially review your DNS setup.

On a Home Assistant Supervised installation, that part is managed by you, not by Home Assistant. 

Also, please note that Ubuntu is not supported by the Home Assistant project and will cause issues. Please consider migrating to Debian, as per our installation requirements.
