### ISSUE TITLE
Cant update Home Assistant Core 2022.8

### ISSUE THREAD

**Issue by Jmjm80** [home-assistant/supervisor#3772]
### Describe the issue you are experiencing

Im not able to update Home Assistant Core to the latest version, im getting the following error:

![ff569629df5a7f31d9941709e7e4454d7f303a0b](https://user-images.githubusercontent.com/65945284/182983898-a8fa6773-ab94-4153-98d6-7dedbde385f3.png)

![56aad621d2638f18cffdb2a8ba6bebe88a61f2ec](https://user-images.githubusercontent.com/65945284/182983912-bc7638e6-e0fc-43cf-8ecd-42402b1efeb0.png)

### What is the used version of the Supervisor?

Supervisor 2022.07.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

8.4

### What version of Home Assistant Core is installed?

2022.7.0

### Steps to reproduce the issue

1. Try to update to the lastest version
2. Get the error
![56aad621d2638f18cffdb2a8ba6bebe88a61f2ec](https://user-images.githubusercontent.com/65945284/182983912-bc7638e6-e0fc-43cf-8ecd-42402b1efeb0.png)

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:301
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:18:28 PM (42 occurrences)
Last logged: 9:51:50 PM

[547401423632] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
[547154054640] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
[547158786640] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
[547146893872] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
[546860983744] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 299, in async_install
    await async_update_core(self.hass, version=version, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: 'HomeAssistantCore.update' blocked from execution, no host internet connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 301, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
```

**Comment by pschneider87** [comment]
I have the same issue, but I'm already in 2022.8.0 and want to upgrade to 2022.8.1
Same error appears when trying to update any addon.

I can ping IPs and Hostnames in the terminal though

**Comment by mdegat01** [comment]
That means supervisor asked your host system if it has internet access and it told it no. Which means you will not be able to update Home Assistant (or anything really) as supervisor needs to be able to download updates to do that.

What is the output when you do `ha network info` in the CLI?

**Comment by webshaun** [comment]
It cleared itself.  After clicking install, it reset to show as if the install button hadn't been clicked yet, then you click install again to get the OP error message.  If you let it sit for a while, the update notification will go away.

**Comment by Jmjm80** [comment]
I had to restore i previous backup to fix the issue.

**Comment by Jaum3** [comment]
Hello

I've been into this problem for a week. For me, it has been on a fresh install and I've tried many ways but I can't get it to work...

When I type `ha network info` i get lots of internet information as an output... 

Can you help me please!

**Comment by kankadev** [comment]
Have the same problem.

```
[core-ssh ~]$ ha network info
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: false
interfaces:
- connected: true
  enabled: true
  interface: eth0
  ipv4:
    address:
    - 192.168.1.150/24
    gateway: 192.168.1.1
    method: static
    nameservers:
    - 8.8.8.8
    - 1.1.1.1
    ready: true
  ipv6:
    address:
    - fe80::2d69:478d:bde9:f391/64
    gateway: null
    method: auto
    nameservers: []
    ready: false
  primary: true
  type: ethernet
  vlan: null
  wifi: null
supervisor_internet: true
```

I restarted about ten times. I can't update HA and can't add custom github repositories.

**Comment by sttaelma** [comment]
i still have the issue with os 9.3 - fresh install in a VM. tried setting DNS to 8.8.8.8, still got the host_internet: false
please advise!

**Comment by WinManMC** [comment]
still got the host_internet: false
Please help !
