### ISSUE TITLE
supervisor doesn't restart node-red

### ISSUE THREAD

**Issue by vajonam** [home-assistant/supervisor#3812]
### Describe the issue you are experiencing

Supervisor doesn't restart the nodered addon after a crash.

```
19 Aug 09:18:58 - [red] Uncaught Exception:
19 Aug 09:18:58 - [error] TypeError: sendEvent.destination.node.receive is not a function
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (node:internal/timers:466:21)
    at process.topLevelDomainCallback (node:domain:152:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[09:18:58] WARNING: Node-RED crashed, halting add-on
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### What is the used version of the Supervisor?

Supervisor 2022.08.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

11.3

### What version of Home Assistant Core is installed?

2022.8.6

### Steps to reproduce the issue

Don;t really have steps to reproduce I am not able to reproduce the node-red error that crashes it.

```
19 Aug 09:18:58 - [red] Uncaught Exception:
19 Aug 09:18:58 - [error] TypeError: sendEvent.destination.node.receive is not a function
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (node:internal/timers:466:21)
    at process.topLevelDomainCallback (node:domain:152:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[09:18:58] WARNING: Node-RED crashed, halting add-on
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing that shows why it didn't restart.
```

### Additional information

I have watchdog enabled 

```
 "a0d7b954_nodered": {
      "options": {
        "certfile": "fullchain.pem",
        "credential_secret": "some_secret%H",
        "http_node": {
          "password": "",
          "username": ""
        },
        "http_static": {
          "password": "",
          "username": ""
        },
        "init_commands": [],
        "keyfile": "privkey.pem",
        "npm_packages": [],
        "ssl": true,
        "system_packages": [],
        "theme": "midnight-red",
        "log_level": "debug",
        "leave_front_door_open": true
      },
      "version": "13.3.2",
      "auto_update": false,
      "uuid": "some_uuid",
      "protected": true,
      "access_token": "some_token",
      "image": "ghcr.io/hassio-addons/node-red/amd64",
      "ingress_token": "some_token-KvZN6lBFTeSbms",
      "ingress_panel": true,
      "network": {
        "80/tcp": 1880
      },
      "watchdog": true,
      "boot": "auto"
    },


```

**Comment by vajonam** [comment]
@mdegat01 what does this mean for my installation? Does the addon need get rebuilt to correctly restart ?

**Comment by mdegat01** [comment]
No, nothing needs to be rebuilt. If you switch to the beta version of supervisor you should find the issue is fixed and you don't need to do anything. If you don't want to do that then next stable release of supervisor will include the fix. Until then if Node RED crashes then you'll have to manually restart it. Also consider submitting an issue to [Node RED](https://nodered.org/) if that happens as it seems unlikely something you do in your flows should be able to crash the entire application.

**Comment by vajonam** [comment]
Yup just moved to the latest supervisor thanks for that.  https://github.com/node-red/node-red/issues/3848 issue open and seeing which flow is causing an issue.
