### ISSUE TITLE
Static DNS entry lost from config after update to Supervisor 2022.09.1

### ISSUE THREAD

**Issue by GiveMeTheBits** [home-assistant/supervisor#3881]
### Describe the issue you are experiencing

I had a static IPV4 config in place prior the recent updates. After updating to Supervisor 2022.09.1, I began getting failures trying to update Add-ons. 

‘AddonManager.update’ blocked from execution, no host internet connection”.

I discovered that the DNS server in my IPv4 config had been removed. Adding it back in resolved the issue. 

### What is the used version of the Supervisor?

2022.09.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

9.0

### What version of Home Assistant Core is installed?

2022.9.5

### Steps to reproduce the issue

1. update to Supervisor 2022.09.1
2. try to use any function that relies on name resolution like updating an add-on
3.consider if it was you that messed it up... no, it was the update that caused it.

### Anything in the Supervisor logs that might be useful for us?

```txt
2022-09-20 09:58:46.377 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548244146016] Error updating Z-Wave JS to MQTT: 'AddonManager.update' blocked from execution, no host internet connection
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: 'AddonManager.update' blocked from execution, no host internet connection
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
await entity.async_install_with_progress(version, backup)
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
await self.async_install(version, backup)
File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Z-Wave JS to MQTT: 'AddonManager.update' blocked from execution, no host internet connection
```

**Comment by mdegat01** [comment]
Hm, that's strange. To clarify, did the method switch from static to auto or did it remain static but the DNS server was gone?

Also are you able to reproduce it by restarting supervisor (`ha su restart`) or rebooting the host?

**Comment by GiveMeTheBits** [comment]
The method remained static and the dns field was deleted. Dns entry still present after a server restart.
