### ISSUE TITLE
Error update 2022.11.1

### ISSUE THREAD

**Issue by zsgodor** [home-assistant/supervisor#3989]
### Describe the issue you are experiencing

I can't update Home Assistant Core 2022.11.1
My System is Debian Bullseye
Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:305
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2022. november 4. 19:23:30 (19 occurrences)
Last logged: 15:38:20

[140584190775824] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
[140584190775824] Error updating Home Assistant Core
[140583722200720] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
[140583944390112] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
[140583705630640] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 303, in async_install
    await async_update_core(self.hass, version=version, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: 'HomeAssistantCore.update' blocked from execution, no host internet connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 305, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, no host internet connection
```

### System Health information

I can't nothing here.

### Supervisor diagnostics

[config_entry-hassio-d8527cc8a2d724f1df44ded4deb50838.json.txt](https://github.com/home-assistant/supervisor/files/9946097/config_entry-hassio-d8527cc8a2d724f1df44ded4deb50838.json.txt)

**Comment by MarcinL1977** [comment]
I had a similar issue, which I managed to solve. Description below:

`nmcli g status` showed "portal" under CONNECTIVITY column. I am not using wifi for connection, but still, it seems it affected the connectivity check. I have commented out all lines in file /etc/NetworkManager/conf.d/20-connectivity.conf and rebooted the machine. After rebooting,  I could see "full" under CONNECTIVITY in `nmcli g status` output and all updates went fine.

**Comment by jgverweij** [comment]
Similar issure here.
2022.11.2 on HassOS VM on Proxmox

    "os_version": "5.15.74",
    "supervisor": "2022.10.2",
    "host_os": "Home Assistant OS 9.3",

`nmcli g status` shows `limited` for CONNECTIVITY 

No config file etc/NetworkManager/conf.d/20-connectivity.conf here

**Comment by jgverweij** [comment]
`ha refreshupdate` returns:

``ERRO[0000] Unexpected server response. Status code: 403``

Could that indicate something?

**Comment by kchiem** [comment]
I had to run: `nmcli connection up "Supervisor eth0"`
