### ISSUE TITLE
My hass Supervisor cant run when updata yesterday.

### ISSUE THREAD

**Issue by pisice** [home-assistant/supervisor#4125]
### Describe the issue you are experiencing

After I updated my Hass yesterday, my Supervisor has been rotating and cannot work，and Display hacs debugging error in integration.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/23545791/215945933-f74afd7c-3db1-4c3b-892f-50bd0e7b7994.png)
![image](https://user-images.githubusercontent.com/23545791/215946186-a56776b3-706a-4e34-a67d-9cd74a784522.png)

### Anything in the Supervisor logs that might be useful for us?

```txt
2023-02-01 11:46:28.610 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /supervisor/info - 
2023-02-01 11:46:28.611 ERROR (MainThread) [homeassistant.components.hassio.handler] /addons return code 500
2023-02-01 11:46:28.613 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons - 
2023-02-01 11:46:28.614 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2023-02-01 11:46:28.614 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store - 
2023-02-01 11:46:37.307 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2023-02-01 11:46:37.310 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 561, in _async_setup_hardware_integration
    if (os_info := get_os_info(hass)) is None:
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 319, in get_os_info
    return hass.data.get(DATA_OS_INFO)
AttributeError: 'datetime.datetime' object has no attribute 'data'
2023-02-01 11:46:37.310 WARNING (MainThread) [homeassistant.components.hassio] Can't read Supervisor data: 
2023-02-01 11:46:37.313 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 11:46:57.732 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 11:50:22.567 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 11:51:37.325 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2023-02-01 11:51:37.326 WARNING (MainThread) [homeassistant.components.hassio] Can't read Supervisor data: 
2023-02-01 11:51:37.326 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 11:53:34.982 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 11:56:37.336 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2023-02-01 11:56:37.340 WARNING (MainThread) [homeassistant.components.hassio] Can't read Supervisor data: 
2023-02-01 11:56:37.341 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 11:56:55.799 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 11:58:17.853 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 11:58:41.210 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/analytics/analytics.py", line 177, in send_analytics
    system_info = await async_get_system_info(self.hass)
  File "/usr/src/homeassistant/homeassistant/helpers/system_info.py", line 57, in async_get_system_info
    info_object["supervisor"] = info.get("supervisor")
AttributeError: 'NoneType' object has no attribute 'get'
2023-02-01 12:01:37.359 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2023-02-01 12:01:37.360 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 12:01:37.360 WARNING (MainThread) [homeassistant.components.hassio] Can't read Supervisor data: 
2023-02-01 12:01:38.326 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 12:03:01.018 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 12:03:01.018 DEBUG (MainThread) [homeassistant.components.hassio] Finished fetching hassio data in 0.008 seconds (success: False)
2023-02-01 12:06:21.709 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 12:06:21.710 DEBUG (MainThread) [homeassistant.components.hassio] Finished fetching hassio data in 0.006 seconds (success: False)
2023-02-01 12:06:37.379 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2023-02-01 12:06:37.381 WARNING (MainThread) [homeassistant.components.hassio] Can't read Supervisor data: 
2023-02-01 12:06:37.381 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 12:07:43.512 ERROR (MainThread) [homeassistant.components.hassio.handler] /supervisor/info return code 500
2023-02-01 12:07:43.512 DEBUG (MainThread) [homeassistant.components.hassio] Finished fetching hassio data in 0.005 seconds (success: False)
```

### System Health information

![2d52c145264d1e9f0d0a17ae1bf7285](https://user-images.githubusercontent.com/23545791/215946360-e1bba49a-bf3e-4889-a791-4bf2ecfe3aa4.png)

**Comment by pisice** [comment]
![image](https://user-images.githubusercontent.com/23545791/215964577-a9743a81-47a8-4c27-a92d-5fe64cb6e02f.png)
![image](https://user-images.githubusercontent.com/23545791/215964822-d5454ab5-1874-49e6-9241-24a6f1bfa86f.png)
![image](https://user-images.githubusercontent.com/23545791/215964943-a5fd810b-61e0-4533-b071-f398a7caf2de.png)

**Comment by Krzysztonek** [comment]
I'm not able to run Supervisor since its last update. 
Also `homeassistant.local:4357` is not accessible from the browser, no chance to even check the version of the supervisor. I'm totally stuck.
