### ISSUE TITLE
error updating addons

### ISSUE THREAD

**Issue by regevbr** [home-assistant/supervisor#4149]
### Describe the issue you are experiencing

When clicking the `Check for update` in the addon store section, an error comes up and asks to look in the supervisor logs
![image](https://user-images.githubusercontent.com/5775519/219335463-0f47806e-4349-475c-bf04-38f5a9fd5472.png)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.click the `Check for update` in the addon store section

### Anything in the Supervisor logs that might be useful for us?

```txt
`
[31m23-02-16 12:02:58 ERROR (MainThread) [aiohttp.server] Error handling request[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 138, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 204, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 102, in wrap_api
    msg_data = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/store.py", line 248, in addons_addon_changelog
    if not addon.with_changelog:
  File "/usr/src/supervisor/supervisor/addons/model.py", line 493, in with_changelog
    return self.path_changelog.exists()
  File "/usr/src/supervisor/supervisor/addons/model.py", line 558, in path_changelog
    return Path(self.path_location, "CHANGELOG.md")
  File "/usr/src/supervisor/supervisor/addons/model.py", line 543, in path_location
    return Path(self.data[ATTR_LOCATON])
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
KeyError: '5c53de3b_esphome'
```
```


### System Health information

## System Information

version | core-2023.2.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.30.1
Stage | running
Available Repositories | 1203
Downloaded Repositories | 44
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 5, 2023 at 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 228.5 GB
disk_used | 121.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.8.0), Home Assistant Google Drive Backup (0.110.1), MariaDB (2.5.2), Mosquitto broker (6.1.3), Node-RED (14.0.2), Node-RED Dashboard (1.3.0), Plex Media Server (3.2.1), Studio Code Server (5.5.2), Transmission (dev), Zigbee2MQTT (1.30.1-1), Glances (0.17.2), InfluxDB (4.5.0), Grafana (8.1.0), pigpio (1.5.2), ESPHome (2023.2.1), MQTT Explorer (browser-1.0.1), Matter Server (3.0.3), room-assistant (beta) (3.0.0-beta.5), Silicon Labs Multiprotocol (0.13.0), ESPHome (dev) (dev)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 31
views | 9
mode | storage

</details>

<details><summary>MiWifi</summary>

version | 2.9.0
-- | --
192.168.31.1 (R2350) | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 13, 2023 at 20:12
-- | --
current_recorder_run | February 16, 2023 at 11:57
estimated_db_size | 603.92 MiB
database_engine | mysql
database_version | 10.6.10

</details>

### Supervisor diagnostics

_No response_

### Additional information

_No response_

**Comment by regevbr** [comment]
Issue ia still relevant
