### ISSUE TITLE
Supervisor Can't Update

### ISSUE THREAD

**Issue by HomeSMARTGuy** [home-assistant/supervisor#4195]
### Describe the issue you are experiencing

My Home Assistant supervisor has become unhealthy after failing to install an update, 'ha supervisor update' command doesn't work either. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:260
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17 March 2023 at 17:25:33 (2 occurrences)
Last logged: 08:23:33

[139994386797552] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2023.03.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2023.03.1&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: device or resource busy")
[139993291695024] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2023.03.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2023.03.1&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: device or resource busy")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 258, in async_install
    await async_update_supervisor(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2023.03.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2023.03.1&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: device or resource busy")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 198, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 260, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2023.03.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2023.03.1&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: device or resource busy")
```

## System Information

version | core-2023.3.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.19.0-35-generic
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.30.1
Stage | running
Available Repositories | 1249
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 January 2018 at 00:00
relayer_connected | false
remote_enabled | true
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | null
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 22.04.2 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.3.0
docker_version | 23.0.1
disk_total | 1832.2 GB
disk_used | 28.4 GB
healthy | failed to load: Unhealthy
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), Terminal & SSH (9.6.1), Studio Code Server (5.5.3), Duck DNS (1.15.0), Mosquitto broker (6.1.3), Plex Media Server (3.2.1), AirCast (3.5.1), AdGuard Home (4.8.2), Matter Server (4.1.0), Zigbee2MQTT (1.30.2-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 13
views | 28
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8 March 2023 at 19:31
-- | --
current_recorder_run | 17 March 2023 at 17:24
estimated_db_size | 59.85 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Supervisor diagnostics

[config_entry-hassio-a0c8a0824972013fa56ce9ebe41d1d29.json.txt](https://github.com/home-assistant/supervisor/files/11007944/config_entry-hassio-a0c8a0824972013fa56ce9ebe41d1d29.json.txt)

**Comment by Gamma-Software** [comment]
I have the same issue

**Comment by mansondl** [comment]
Same issue.
