### ISSUE TITLE
Network Configuration: IP address checking not working

### ISSUE THREAD

**Issue by chrismanivong** [home-assistant/supervisor#4208]
### Describe the issue you are experiencing

When configuring additional network cards via GUI, an error occurs. Looking to the logs, it's noted that the given address doesn't look like an IPv4 / IPv6 address.

This was working in an earlier release but I cannot figure out when it was working last time.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Open Settings -> System -> Network
2. go to "configure network interface" 
3. select non-default network interface
4. switch to "manual"
5. insert ip address "192.168.10.254/24" or "192.168.10.254/255.255.255.0"
6. try to save
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-03-26 22:01:27 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 107, in __call__
    return self.type(v)
  File "/usr/local/lib/python3.10/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: None does not appear to be an IPv4 or IPv6 address
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 126, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 116, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/network.py", line 192, in interface_update
    body = await api_validate(SCHEMA_UPDATE, request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 151, in api_validate
    data_validated = schema(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 110, in __call__
    if not self.msg and Enum and issubclass(self.type, Enum):
TypeError: issubclass() arg 1 must be a class
```

### System Health information

N/A

### Supervisor diagnostics

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.3.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.03.2",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {},
  "integration_manifest": {
    "domain": "hassio",
    "name": "Home Assistant Supervisor",
    "codeowners": [
      "@home-assistant/supervisor"
    ],
    "dependencies": [
      "http"
    ],
    "documentation": "https://www.home-assistant.io/integrations/hassio",
    "iot_class": "local_polling",
    "quality_scale": "internal",
    "is_built_in": true
  },
  "data": {
    "coordinator_data": {
      "addons": {},
      "os": {
        "version": "9.5",
        "version_latest": "9.5",
        "update_available": false,
        "board": "ova",
        "boot": "A",
        "data_disk": "/dev/sda8"
      },
      "core": {
        "version": "2023.3.6",
        "version_latest": "2023.3.6",
        "update_available": false,
        "machine": "qemux86-64",
        "ip_address": "172.30.32.1",
        "arch": "amd64",
        "image": "ghcr.io/home-assistant/qemux86-64-homeassistant",
        "boot": true,
        "port": 8123,
        "ssl": false,
        "watchdog": true,
        "audio_input": null,
        "audio_output": null
      },
      "supervisor": {
        "version": "2023.03.2",
        "version_latest": "2023.03.2",
        "update_available": false,
        "channel": "stable",
        "arch": "amd64",
        "supported": true,
        "healthy": true,
        "ip_address": "172.30.32.2",
        "wait_boot": 5,
        "timezone": "Europe/Berlin",
        "logging": "info",
        "debug": false,
        "debug_block": false,
        "diagnostics": true,
        "auto_update": true,
        "addons": [],
        "addons_repositories": []
      }
    },
  }
}

### Additional information

Full Diagnostic data has been too long to post.

**Comment by chrismanivong** [comment]
@frenck This issue is still existing in latest HA core / supervisor / HA-OS release.
I'm able to reproduce this in any installation with more than 1 network interface card.

**Comment by chrismanivong** [comment]
Latest log:

`23-04-25 23:40:33 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 107, in __call__
    return self.type(v)
  File "/usr/local/lib/python3.10/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: None does not appear to be an IPv4 or IPv6 address
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 126, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 116, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/network.py", line 192, in interface_update
    body = await api_validate(SCHEMA_UPDATE, request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 151, in api_validate
    data_validated = schema(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 387, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 110, in __call__
    if not self.msg and Enum and issubclass(self.type, Enum):
TypeError: issubclass() arg 1 must be a class`

**Comment by chrismanivong** [comment]
With some more testing I have to add more information:

The error occurs only when setting up the non-primary interface without giving a gateway address. 
It doesn't occur when entering the interface address incl. netmask and a gateway address like 0.0.0.0.

It also doesn't occur when changing the interface address and deleting the field data of the gateway address.
