### ISSUE TITLE
Multiples error after upgrade Supervisor : ATTR_DATA_DISK: self.sys_os.datadisk.disk_used.id,

### ISSUE THREAD

**Issue by Verbalinsurection** [home-assistant/supervisor#4216]
### Describe the issue you are experiencing

Hello,
After updating Supervisor and restart, I receive a lot of error and can't access stor modules.
In Supervisor LOG : 
```23-03-30 00:56:02 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); transport: received unexpected content-type "text/plain; charset=utf-8"
23-03-30 00:56:03 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 126, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 116, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/os.py", line 66, in info
    ATTR_DATA_DISK: self.sys_os.datadisk.disk_used.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

And on Home Assistant : 
```2023-03-30 00:55:09.805 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/hassio/issues.py", line 157, in update
data = await self._client.get_resolution_info()
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: System is not ready with state: setup
2023-03-30 00:56:03.964 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500

2023-03-30 01:00:15.561 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/analytics/analytics.py", line 183, in send_analytics
system_info = await async_get_system_info(self.hass)
File "/usr/src/homeassistant/homeassistant/helpers/system_info.py", line 57, in async_get_system_info
info_object["supervisor"] = info.get("supervisor")
AttributeError: 'NoneType' object has no attribute 'get'
```

I have use "ha supervisor repair" without success.

Thank you

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

1. Update supervisor to 2023.03.3
2. Starting home assistant
3. Access to log or want to access module store

### Anything in the Supervisor logs that might be useful for us?

```txt
23-03-30 01:04:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-03-30 01:04:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-03-30 01:04:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-03-30 01:04:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
23-03-30 01:04:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/hassio repository
23-03-30 01:04:12 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); transport: received unexpected content-type "text/plain; charset=utf-8"
23-03-30 01:04:13 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
23-03-30 01:04:13 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
23-03-30 01:04:13 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 126, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 116, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/os.py", line 66, in info
    ATTR_DATA_DISK: self.sys_os.datadisk.disk_used.id,
AttributeError: 'NoneType' object has no attribute 'id'
23-03-30 01:04:43 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 126, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 116, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/os.py", line 66, in info
    ATTR_DATA_DISK: self.sys_os.datadisk.disk_used.id,
AttributeError: 'NoneType' object has no attribute 'id'
23-03-30 01:05:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-03-30 01:05:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/hassio repository
23-03-30 01:05:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-03-30 01:05:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
23-03-30 01:05:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-03-30 01:05:33 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-03-30 01:05:34 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); transport: received unexpected content-type "text/plain; charset=utf-8"
23-03-30 01:05:34 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
23-03-30 01:05:34 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
23-03-30 01:05:34 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 126, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 116, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/os.py", line 66, in info
    ATTR_DATA_DISK: self.sys_os.datadisk.disk_used.id,
AttributeError: 'NoneType' object has no attribute 'id'
23-03-30 01:05:40 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
```

## System Information

error | failed to load: unknown
-- | --

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1248
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 18 avril 2023 à 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | null
-- | --
update_channel | null
supervisor_version | supervisor-None
agent_version | null
docker_version | null
disk_total | None GB
disk_used | None GB
healthy | failed to load: Unhealthy
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 7
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23 mars 2023 à 16:46
-- | --
current_recorder_run | 30 mars 2023 à 00:44
estimated_db_size | 1982.47 MiB
database_engine | mysql
database_version | 10.6.10

</details>

### Supervisor diagnostics

2023-03-30 00:44:38.365 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-30 00:44:38.366 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-30 00:44:38.370 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration overwolfstatus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-30 00:44:38.371 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration next_rocket_launch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-30 00:44:43.601 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:44:45.531 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:45:17.080 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:45:29.032 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:45:50.489 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:46:31.938 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:47:53.428 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:49:14.946 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:49:43.641 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 560, in _async_setup_hardware_integration
    if (os_info := get_os_info(hass)) is None:
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 320, in get_os_info
    return hass.data.get(DATA_OS_INFO)
AttributeError: 'datetime.datetime' object has no attribute 'data'
2023-03-30 00:49:43.652 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:50:36.418 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:51:58.108 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:53:20.645 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:54:42.454 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:54:43.690 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:55:09.805 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/issues.py", line 157, in update
    data = await self._client.get_resolution_info()
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: System is not ready with state: setup
2023-03-30 00:56:03.964 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:57:25.491 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:58:00.987 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:58:00.989 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /os/info - 
2023-03-30 00:58:47.261 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 00:59:43.730 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 01:00:08.808 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 01:00:15.561 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/analytics/analytics.py", line 183, in send_analytics
    system_info = await async_get_system_info(self.hass)
  File "/usr/src/homeassistant/homeassistant/helpers/system_info.py", line 57, in async_get_system_info
    info_object["supervisor"] = info.get("supervisor")
AttributeError: 'NoneType' object has no attribute 'get'
2023-03-30 01:01:30.540 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 01:02:21.578 ERROR (MainThread) [homeassistant.components.system_health] Error fetching info
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 71, in get_integration_info
    data = await registration.info_callback(hass)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/system_health.py", line 17, in system_health_info
    info = await system_info.async_get_system_info(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/system_info.py", line 57, in async_get_system_info
    info_object["supervisor"] = info.get("supervisor")
AttributeError: 'NoneType' object has no attribute 'get'
2023-03-30 01:02:52.202 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 01:04:13.568 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 01:04:43.767 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 01:05:34.900 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 01:06:30.712 ERROR (MainThread) [homeassistant.components.system_health] Error fetching info
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 71, in get_integration_info
    data = await registration.info_callback(hass)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/system_health.py", line 17, in system_health_info
    info = await system_info.async_get_system_info(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/system_info.py", line 57, in async_get_system_info
    info_object["supervisor"] = info.get("supervisor")
AttributeError: 'NoneType' object has no attribute 'get'
2023-03-30 01:06:56.603 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 01:08:18.239 ERROR (MainThread) [homeassistant.components.hassio.handler] /os/info return code 500
2023-03-30 01:08:18.240 DEBUG (MainThread) [homeassistant.components.hassio] Finished fetching hassio data in 0.016 seconds (success: False)

**Comment by tpjanssen** [comment]
I'm having the exact same issue. Caused by this PR [#4202 ](https://github.com/home-assistant/supervisor/pull/4202).

**Comment by GSzabados** [comment]
It stops Supervisor to behave normally. Add on list does not load anymore. Backups does not load either. No hardware info, etc.
Updates are missing as well.

**Comment by chrismurt** [comment]
> It stops Supervisor to behave normally. Add on list does not load anymore. Backups does not load either. No hardware info, etc. Updates are missing as well.

Same symptoms, eg no addon list and no way to access backups from UI, same error in supervisor logs, traceback to same lines of code

**Comment by Nowray** [comment]
I have the same issue as well.

**Comment by NLeifsson** [comment]
Same problem here. 

Running Debian 11 with Home assistant supervised.  Home assistant ran an auto update of the supervisor to version 2023.03.3 and after that the supervisor wont start correctly. No addons page or backup page. 

Tried everything that the logs called for (fixing dbus issues etc) but nothing seems to work. 

Hoping for a fix on this!

**Comment by vtumi** [comment]
I have the same problem, is there any solution

**Comment by tangshxiao** [comment]
"I also encountered the same problem. Rollback to 2023.03.2 is normal, but addno cannot be used."

**Comment by robertiturnbull** [comment]
+1 same issue since the last update

**Comment by servervas** [comment]
Same issue. As a temporary solution:

docker exec -it hassio_supervisor sh
vi /usr/src/supervisor/supervisor/api/os.py

press "i"

change on 66 line: self.sys_os.datadisk.disk_used.id -> self.sys_os.datadisk.disk_used

press "esc"
print "wq" -> enter

exit

docker restart hassio_supervisor

**Comment by olijouve** [comment]
Thank you @servervas ! 
I confirm i can now update addons thanks to your instructions

**Comment by agners** [comment]
@Verbalinsurection which version of OS Agent are you using (`dpkg -l os-agent`)?

I can't reproduce the problem on a vanilla Supervised installation on Debian 11 bullseye.

**Comment by mariushosting** [comment]
Same issue on version 2023.03.3

**Comment by NEoKhajitt** [comment]
Had the same issue, i initially noticed it as my Grafana Dahsboard stopped working, unable to connect to the influxDB. not 100% how this was related to eachother, or if it was even related.
I tried to go to the addon page to see whats going on, but it was not loading.

Then looking at the logs i found a lot of `ERROR (MainThread) [aiohttp.server] Error handling request` in the supervisor logs, and the unable to get /os/info errors with the debug showing line 66 in `/usr/src/supervisor/supervisor/api/os.py`

I found this thread and followed @servervas solution instead of rolling back, I was then able to get to the addon page, which did not resolve my influxDB issue, but later discovered that the db name was missing from my condig (how that happened, i have no idea) but adding the db name (in my case "homeassistant") Grafana started pulling metrics again.

I also run HA on an unsupported setup:
OS: Ubuntu 20.04.1 LTS
Docker version 20.10.17, build 100c701
Home Assistant 2023.3.6
Supervisor 2023.03.3
Frontend 20230309.1 - latest

**Comment by Machaeon** [comment]
Had same issue. Fixed by installing os-agent.

**Comment by mariushosting** [comment]
> Had same issue. Fixed by installing os-agent.

Which one?

**Comment by Machaeon** [comment]
> > Had same issue. Fixed by installing os-agent.
> 
> Which one?

Latest from
https://github.com/home-assistant/os-agent/releases
