### ISSUE TITLE
 Core not automatically restarted after hanging

### ISSUE THREAD

**Issue by myhades** [home-assistant/supervisor#4265]
### Describe the issue you are experiencing

My core randomly hangs every 1-10 days, and based on the limited information I can found, core container should be automatically restarted in a home assistant os installation? After the core dies, a simple `ha core start` would do the trick and get it up and running.
My setup has gotten way too complex for me to diagnose the problem causing the core to hang, the best i can hope is that those hangs don't have much impact and core resumes quickly.
This issue was first posted in os sector and I was suggested to post it here, and I apologize for any inconvenience or confusion.
This problem has been noticed for a long time, and occurs more frequently lately, even with the latest core, os and supervisor.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Randomly occurs.

### Anything in the Supervisor logs that might be useful for us?

```txt
2023-04-27 04:47:14.990 WARNING (MainThread) [homeassistant.runner] Task could not be canceled and was still running after shutdown: <Task pending name='Task-1019819' coro=<WebSocketCommonProtocol.close_connection() running at /usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py:1312> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /usr/local/lib/python3.10/asyncio/tasks.py:864, Task.task_wakeup()]>>
2023-04-27 04:47:15.000 WARNING (MainThread) [homeassistant.runner] Task could not be canceled and was still running after shutdown: <Task pending name='Task-2023632' coro=<RequestHandler.start() running at /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:512> wait_for=<Task pending name='Task-2023633' coro=<RequestHandler._handle_request() running at /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:433> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup()]>>
2023-04-27 04:47:15.004 WARNING (MainThread) [homeassistant.runner] Task could not be canceled and was still running after shutdown: <Task pending name='Task-2023633' coro=<RequestHandler._handle_request() running at /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:433> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup()]>
2023-04-27 04:47:15.114 ERROR (MainThread) [homeassistant] Error doing job: an error occurred during closing of asynchronous generator <async_generator object _acquire at 0x7fcba4feb3c0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/runner.py", line 179, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    handle = heapq.heappop(self._scheduled)
RuntimeError: list changed size during iteration

During handling of the above exception, another exception occurred:

RuntimeError: aclose(): asynchronous generator is already running
2023-04-27 04:47:15.117 ERROR (MainThread) [homeassistant] Error doing job: an error occurred during closing of asynchronous generator <async_generator object _acquire at 0x7fcb9fbc4f40>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/runner.py", line 179, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    handle = heapq.heappop(self._scheduled)
RuntimeError: list changed size during iteration

During handling of the above exception, another exception occurred:

RuntimeError: aclose(): asynchronous generator is already running
2023-04-27 04:47:15.321 WARNING (Thread-10 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_8] is still running at shutdown: File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
2023-04-27 04:47:15.360 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.cuco_cp3a_c3c3_switch_4 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/runner.py", line 179, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    handle = heapq.heappop(self._scheduled)
RuntimeError: list changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/switch.py", line 94, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1474, in async_update
    await self.async_update_attrs(attrs, update_subs=True)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1080, in async_update_attrs
    return await self.hass.async_add_executor_job(
  File "/usr/src/homeassistant/homeassistant/core.py", line 555, in async_add_executor_job
    task = self.loop.run_in_executor(None, target, *args)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 814, in run_in_executor
    self._check_default_executor()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 519, in _check_default_executor
    raise RuntimeError('Executor shutdown has been called')
RuntimeError: Executor shutdown has been called
2023-04-27 04:47:15.493 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.cuco_cp3a_c3c3_switch_3 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/runner.py", line 179, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    handle = heapq.heappop(self._scheduled)
RuntimeError: list changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/switch.py", line 94, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1474, in async_update
    await self.async_update_attrs(attrs, update_subs=True)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1080, in async_update_attrs
    return await self.hass.async_add_executor_job(
  File "/usr/src/homeassistant/homeassistant/core.py", line 555, in async_add_executor_job
    task = self.loop.run_in_executor(None, target, *args)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 814, in run_in_executor
    self._check_default_executor()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 519, in _check_default_executor
    raise RuntimeError('Executor shutdown has been called')
RuntimeError: Executor shutdown has been called
2023-04-27 04:47:15.508 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.cuco_cp3a_c3c3_switch fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/runner.py", line 179, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    handle = heapq.heappop(self._scheduled)
RuntimeError: list changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/switch.py", line 94, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1478, in async_update
    await self.async_update_attrs({
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1080, in async_update_attrs
    return await self.hass.async_add_executor_job(
  File "/usr/src/homeassistant/homeassistant/core.py", line 555, in async_add_executor_job
    task = self.loop.run_in_executor(None, target, *args)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 814, in run_in_executor
    self._check_default_executor()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 519, in _check_default_executor
    raise RuntimeError('Executor shutdown has been called')
RuntimeError: Executor shutdown has been called
2023-04-27 04:47:15.730 WARNING (Thread-10 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_14] is still running at shutdown: File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/miio/click_common.py", line 184, in _wrap
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/miio/integrations/humidifier/deerma/airhumidifier_mjjsq.py", line 157, in status
    values = self.get_properties(properties, max_properties=1)
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.10/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
2023-04-27 04:47:15.784 WARNING (Thread-10 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_11] is still running at shutdown: File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 655, in get_properties_for_mapping
    return self.get_properties(
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.10/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
2023-04-27 04:47:15.767 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/runner.py", line 179, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    handle = heapq.heappop(self._scheduled)
RuntimeError: list changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 260, in _async_callback_delayed_write
    await self._async_handle_write_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 285, in _async_handle_write_data
    await self._async_write_data(self.path, data)
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 290, in _async_write_data
    await self.hass.async_add_executor_job(self._write_data, self.path, data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 555, in async_add_executor_job
    task = self.loop.run_in_executor(None, target, *args)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 814, in run_in_executor
    self._check_default_executor()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 519, in _check_default_executor
    raise RuntimeError('Executor shutdown has been called')
RuntimeError: Executor shutdown has been called
2023-04-27 04:47:15.867 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_11] is still running at shutdown: File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 655, in get_properties_for_mapping
    return self.get_properties(
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.10/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
2023-04-27 04:47:23.301 ERROR (DHCPWatcher) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/scapy/sendrecv.py", line 1254, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python3.10/site-packages/scapy/sessions.py", line 109, in on_packet_received
    result = self.prn(pkt)
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 450, in _handle_dhcp_packet
    self.process_client(ip_address, hostname, mac_address)
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 144, in process_client
    return run_callback_threadsafe(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 46, in run_callback_threadsafe
    loop.call_soon_threadsafe(run_callback)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 798, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

## System Information

version | core-2023.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.24
arch | x86_64
timezone | Asia/Shanghai
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1337
Downloaded Repositories | 49

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 30.8 GB
disk_used | 19.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AirCast (3.5.2), Studio Code Server (5.5.3), Samba share (10.0.1), Terminal & SSH (9.6.1), File editor (5.5.0), Node-RED (14.1.0), Rclone Backup (3.0.1), chrony (2.5.0), VNC Viewer (1.6.0), ESPHome (2023.3.0), Mosquitto broker (6.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 19
views | 50
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 17, 2023 at 2:08 PM
-- | --
current_recorder_run | April 27, 2023 at 8:18 AM
estimated_db_size | 1092.58 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | failed to load: timeout
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.7
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | false
-- | --
added_devices | 2

</details>

### Supervisor diagnostics

[config_entry-hassio-b5189d063f33cef5e59d35c06403d70a.json.txt](https://github.com/home-assistant/supervisor/files/11341300/config_entry-hassio-b5189d063f33cef5e59d35c06403d70a.json.txt)

### Additional information

![IMG_0373](https://user-images.githubusercontent.com/61046290/234740818-9c20e5b4-c1d7-428b-82b4-799c79181ff6.PNG)
`ha core restart` runs smoothly.
One thing to notice, host log time is 8 hours behind the supervisor, guess it's using utc time.
the hang occur roughly 8pm 4.26 utc and 4am 4.27 at my location.

**Comment by myhades** [comment]
Core hanged twice in the last month, similar error and on the latest version of os and supervisor
