### ISSUE TITLE
Supervisor update is broken 2023.04.1

### ISSUE THREAD

**Issue by physicalit** [home-assistant/supervisor#4266]
### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/759600/234906107-99f67312-a03e-4857-a761-cdb32e62a910.png)
As seen in the above image, the upgrade from 2023.04.0 to 2023.04.1 is not possible. it appears that the image is missing from the registry. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.Trying to update to latest version
2. ERROR
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.core
Source: components/hassio/update.py:260
First occurred: 5:37:17 PM (3 occurrences)
Last logged: 5:40:49 PM

Error executing service: <ServiceCall update.install (c:01GZ1J9S6ESAP8G1PFN80EP1HD): entity_id=['update.home_assistant_supervisor_update'], backup=False>
Error executing service: <ServiceCall update.install (c:01GZ1JEF1HJ9EQ1Y69NJ0530X3): entity_id=['update.home_assistant_supervisor_update'], backup=False>
Error executing service: <ServiceCall update.install (c:01GZ1JG83BRB3NJ6FN0V4S00ZD): entity_id=['update.home_assistant_supervisor_update'], backup=False>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 258, in async_install
    await async_update_supervisor(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.04.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2023.04.1&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-supervisor&platform=linux%2Farm64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: no such host")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 260, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.04.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2023.04.1&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-supervisor&platform=linux%2Farm64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: no such host")
```

## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Bucharest
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4898
Installed Version | 1.30.1
Stage | running
Available Repositories | 1271
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.0
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 109.3 GB
disk_used | 17.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), Glances (0.18.1), ESPHome (2023.3.2), File editor (5.5.0), Zigbee2MQTT (1.30.3-1), Mosquitto broker (6.2.0), eWeLink Smart Home (1.4.3), UniFi Network Application (2.6.0), rsync (1.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 3
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 5, 2023 at 6:39 PM
-- | --
current_recorder_run | April 27, 2023 at 5:32 PM
estimated_db_size | 8491.02 MiB
database_engine | mysql
database_version | 8.0.32

</details>

<details><summary>Sonoff</summary>

version | 3.4.0 (5406fa7)
-- | --
cloud_online | 4 / 6
local_online | 4 / 5

</details>

### Supervisor diagnostics

[config_entry-hassio-c9b49e571f2dfdb664afe3441f63b351.json.txt](https://github.com/home-assistant/supervisor/files/11345298/config_entry-hassio-c9b49e571f2dfdb664afe3441f63b351.json.txt)

**Comment by physicalit** [comment]
For some reason the dns server wasn't updating correctly from dhcp. 
I discovered by mistake the command `ha network` and was able to set it correctly (I found way too much misleading information on the forums). 
This should be documented on the supervisor update page!
