### ISSUE TITLE
can't update from 2023.05.2 to 2023.05.3

### ISSUE THREAD

**Issue by burne101** [home-assistant/supervisor#4297]
### Describe the issue you are experiencing

I'm trying to update. 

Starting the update seems to work, but after a while I am greeted by the old version.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. ha core update
2. ha core restart 
3. ha core info

After above, the current version remains unchanged and an update remain available.

### Anything in the Supervisor logs that might be useful for us?

```txt
Yes:

23-05-16 19:30:14 ERROR (SyncWorker_5) [supervisor.docker.interface]
 Can't install ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.5.3: 
404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.5.3/json: 
Not Found ("No such image: ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.5.3")
```

### System Health information

There are currently no repairs available

**Comment by whisdol** [comment]
I have the same issue - the update eventually fails, all/some? network connections reset (e.g. I notice MQTT devices disconnecting), then it comes back up as if nothing happened. Core does not reboot.

Had the issue when updating from 2023.4.x to 2023.5.2, and now again for 2023.5.2->2023.5.3. For the update to 2023.5.2, I fiddled with disabling the HAOS IPv6 setting because I had a feeling that was the point of failure. After enough fiddling[1], the update worked - now those have been reset to the default config and I'm facing the same issue again.

I'm also running HAOS.

My supervisor log only includes these errors:
```log
23-05-17 20:44:55 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2023.5.3
23-05-17 20:44:55 INFO (SyncWorker_1) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/qemux86-64-homeassistant:2023.5.2 to ghcr.io/home-assistant/qemux86-64-homeassistant:2023.5.3
23-05-17 20:44:55 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/qemux86-64-homeassistant with tag 2023.5.3.
23-05-17 20:49:37 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0b57708f70>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/
23-05-17 20:49:42 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0b5770bb20>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/
23-05-17 20:53:28 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/qemux86-64-homeassistant:2023.5.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/home-assistant/qemux86-64-homeassistant:2023.5.3/json: Not Found ("No such image: ghcr.io/home-assistant/qemux86-64-homeassistant:2023.5.3")
23-05-17 20:53:28 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed

```

[1]
The update worked after setting ipv6.method to `disabled` or `ignore`, although the settings did not stick after reboot.
`nmcli connection modify Supervisor\ enp0s3 ipv6.method disabled/ignore`
`nmcli connection up Supervisor\ enp0s3`
I had to disable IPv6 in the UI before via Settings > System > Network > IPv6: Disabled to fix HACS downloads.

**Comment by rzechu** [comment]
Same here UI updating very long and after restart nothing changes.
From cmd
```

pi@rpi4:~ $ ha core update
Command completed successfully.
pi@rpi4:~ $ ha core restart
Command completed successfully.
pi@rpi4:~ $ ha core info
arch: armv7
audio_input: None
audio_output: None
boot: true
image: ghcr.io/home-assistant/raspberrypi4-homeassistant
ip_address: 172.30.32.1
machine: raspberrypi4
port: 8123
ssl: true
update_available: true
version: 2023.4.1
version_latest: 2023.5.3
watchdog: true
pi@rpi4:~ $

```

**Comment by cptskippy** [comment]
I've been having the same issue.  I opened a bug in [/core](https://github.com/home-assistant/core/issues/92433).

Starting after the ESPHome 2023.3.2 release, updating of the ESPHome Add-On stopped working.  When I attempted to upgrade the ESPHome Add-on after ESPHome 2023.4.0 was released, it started returning an error.  I am able to uninstall/reinstall the Add-on but updating always fails.

The error in the Hosts log leads me to believe it's attempting to download a build for the wrong platform (ARMv6) and failing. I am at a loss on how to troubleshoot this further.

Below are the logs from the latest attempt to update the ESPHome Add-on.

**Home Assistant Core logs:**

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:34:54 PM (2 occurrences)
Last logged: 2:35:44 PM

[1704455400] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")
[1521728168] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 52, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 981, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")

```

**Supervisor Logs:**

```
23-05-03 14:34:05 INFO (SyncWorker_2) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/raspberrypi2-homeassistant:2023.4.6']
23-05-03 14:34:50 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 7efd0127
23-05-03 14:34:50 INFO (MainThread) [supervisor.backups.manager] Backing up 7efd0127 store Add-ons
23-05-03 14:34:50 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 5c53de3b_esphome
23-05-03 14:34:50 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 5c53de3b_esphome
23-05-03 14:34:51 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 7efd0127 completed
23-05-03 14:34:51 INFO (SyncWorker_0) [supervisor.docker.addon] Updating image ghcr.io/esphome/esphome-hassio:2023.4.2 to ghcr.io/esphome/esphome-hassio:2023.4.3
23-05-03 14:34:51 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/esphome/esphome-hassio with tag 2023.4.3.
23-05-03 14:34:53 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")

```

**Host Logs:**

```
May 03 21:34:53 homeassistant dockerd[473]: time="2023-05-03T21:34:53.828932024Z" level=info msg="Attempting next endpoint for pull after error: no matching manifest for linux/arm/v6 in the manifest list entries"
```

This is still happening of this morning with:

- ESPHome 2023.5.3
- Home Assistant 2023.5.3
- Supervisor 2023.04.1
- Operating System 10.1
- Frontend 20230503.3 - latest 

**Troubleshooting:**

Uninstalling and reinstalling ESPHome will update to the latest version however updates still fail.

Using the Advanced SSH & Web Terminal, you can in log into the HA instance and initiate a docker pull:

> docker pull ghcr.io/esphome/esphome-hassio:2023.5.1

After pulling the image manually, the update UI in HA will work.

**Comment by ColColonCleaner** [comment]
Having the same problem here. Stuck on 2023.5.2. Cant update to 2023.5.3 or 2023.5.4.

**Comment by cptskippy** [comment]
@burne101 are there any entries in your Hosts log following an attempt to update?

In addition to errors like you've provided, my Host logs has an error like this:

`May 25 16:49:11 homeassistant dockerd[472]: time="2023-05-25T16:49:11.432244045Z" level=info msg="Attempting next endpoint for pull after error: no matching manifest for linux/arm/v6 in the manifest list entries"`

**Comment by ColColonCleaner** [comment]
This issue is resolved for me as of 2023.6.0. Update of core went through and all integrations seem to be fine.

**Comment by Telain** [comment]
Unfortunately still working for me, and I don't see any errors in Core, Host, or supervisor logs.

**Comment by cptskippy** [comment]
Just tried to upgrade ESPHome to 2023.6.0 and received an error in Supervisor.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:44:51 AM (2 occurrences)
Last logged: 9:53:23 AM

[1502423792] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.6.0: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.6.0/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.6.0")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 52, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/esphome/esphome-hassio:2023.6.0: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.6.0/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.6.0")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.6.0: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.6.0/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.6.0")
```

**Comment by burne101** [comment]
Looking at the errors there are still missing images for certain architectures, and somebody at Nabu Casa needs to check the reporting of the automatic builds. Things go wrong:

404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.6.0/json: Not Found

and we end-users can't fix those issues.

**Comment by cptskippy** [comment]
Error was still happening with me after the latest updates.

**Comment by cptskippy** [comment]
Still getting the error updating from 2023.8.1 to 2023.8.2:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 5:25:55 PM (2 occurrences)
Last logged: 5:26:00 PM

    [1534109608] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.8.2: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.8.2/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.8.2")
    [1533163304] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.8.2: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.8.2/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.8.2")
```

**Comment by elecstix** [comment]
I have a similar issue when trying to update the supervisor.
RPi 4 HAOS
Reloaded from scratch, disabled IPV6. No change.

[547808679872] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.08.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.08.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.08.3")

Not sure what to try next. Unable to install SSH Terminal until Supervisor updated.

**Comment by phongtagia** [comment]
I have a similar issue when trying to update the supervisor from 2023.06.2 to 2023.09.2

Container Based

23-09-20 11:49:09 CRITICAL (MainThread) [supervisor.jobs] The following job conditions are ignored and will make the system unstable when they occur: {<JobCondition.HEALTHY: 'healthy'>}
23-09-20 11:49:09 WARNING (MainThread) [supervisor.jobs] 'PluginCli.update' blocked from execution, supervisor needs to be updated first
23-09-20 11:49:09 ERROR (MainThread) [supervisor.plugins.manager] Can't update cli to 2023.06.0, the Supervisor healthy could be compromised!

Not sure what to try next.
