### ISSUE TITLE
[OTBR] OpenThread Border Router 1.1.0 update proposal for incompatible architecture (Rpi3 32-bit) 

### ISSUE THREAD

**Issue by lboue** [home-assistant/supervisor#4307]
Hello,

I am running HA on a Raspberry Pi 3 (32-bit) and today, I got an **OpenThread Border Router 1.1.0** update proposal for incompatible architecture. 
```
1.1.0
Automatically flash firmware for Home Assistant SkyConnect and Yellow
Update serial port defaults to match latest firmware builds
```

So logically, the update fails:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:12:23 (3 occurrences)
Last logged: 09:34:09

[1527919232] Error updating OpenThread Border Router: Add-on 77f1785d_openthread_border_router not supported on this platform, supported architectures: aarch64, amd64
[1540298088] Error updating OpenThread Border Router: Add-on 77f1785d_openthread_border_router not supported on this platform, supported architectures: aarch64, amd64
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Add-on 77f1785d_openthread_border_router not supported on this platform, supported architectures: aarch64, amd64

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating OpenThread Border Router: Add-on 77f1785d_openthread_border_router not supported on this platform, supported architectures: aarch64, amd64
```

Isn't there a compatibility check before proposing this update?

Regards

**Comment by agners** [comment]
I've transferred this issue to Supervisor, since its the Supervisor which offers the update.

**Comment by lboue** [comment]
> I've transferred this issue to Supervisor, since its the Supervisor which offers the update.

Thanks
