### ISSUE TITLE
Dialog for Create Backup has no input field for Backup Name 

### ISSUE THREAD

**Issue by mscott370** [home-assistant/supervisor#4330]
### Describe the issue you are experiencing

After installation of  HA Supervisor 2023.05.0 I wanted to create a backup of the new HA environment and noticed that the pop-up panel which appears in the dialog Settings---System---Backups after pressing "CREATE BACKUP" no longer has an input field for entering the name of the backup file to be created.
![image](https://github.com/home-assistant/supervisor/assets/58113309/be354b01-0506-40a6-9661-bbd7ea15a912)
.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Invoke dialog for creating manual backup: HA Settings --- System --- Backups
2. Click on **"+ Create Backup"**
3. Next step is usually to enter Name for the Backup and select Backup Type, but the input field for entering the Name is missing.
4. The last backup i was able to create and specify the name was in HA OS 10.2 + Supervisor 2023.04.1 +  Core 2023.5.4. 
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-05-31 23:01:47 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-44038' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 160, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
23-05-31 23:01:47 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Set of Tasks/Futures is empty.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
23-05-31 23:02:06 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.05.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.5 GB
disk_used | 4.8 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Mosquitto broker (6.2.1), File editor (5.6.0), Let's Encrypt (4.12.8), Duck DNS (1.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 May 2023 at 21:36
-- | --
current_recorder_run | 31 May 2023 at 12:28
estimated_db_size | 216.14 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

### Supervisor diagnostics

[config_entry-hassio-4778d43c50fa18f1e7d9ce46f5739b0f.json.txt](https://github.com/home-assistant/supervisor/files/11618863/config_entry-hassio-4778d43c50fa18f1e7d9ce46f5739b0f.json.txt)

## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.05.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.5 GB
disk_used | 4.8 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Mosquitto broker (6.2.1), File editor (5.6.0), Let's Encrypt (4.12.8), Duck DNS (1.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 May 2023 at 21:36
-- | --
current_recorder_run | 31 May 2023 at 12:28
estimated_db_size | 216.14 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

**Comment by mscott370** [comment]
After installation of Supervisor 2023.06.0 the problem is no longer there. Presumably fixed by #4327.
Glad to see it fixed so fast!
