### ISSUE TITLE
ERROR (MainThread) [aiohttp.server] Error handling request

### ISSUE THREAD

**Issue by Sashik259** [home-assistant/supervisor#4362]
### Describe the issue you are experiencing

Error log in HA Supervisor
Start process takes a lot time

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

Error while starting HA
Start process takes a lot time

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-09 11:57:50 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-06-09 11:57:51 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-06-09 11:57:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
23-06-09 11:57:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-06-09 11:57:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-06-09 11:57:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/TECH7Fox/asterisk-hass-addons repository
23-06-09 11:57:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-06-09 11:57:53 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-06-09 11:57:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/store.py", line 178, in store_info
    ATTR_ADDONS: [
                 ^
  File "/usr/src/supervisor/supervisor/api/store.py", line 179, in <listcomp>
    self._generate_addon_information(self.sys_addons.store[addon])
  File "/usr/src/supervisor/supervisor/api/store.py", line 114, in _generate_addon_information
    ATTR_ADVANCED: addon.advanced,
                   ^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/model.py", line 227, in advanced
    return self.data[ATTR_ADVANCED]
           ^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'core_dnsmasq'
23-06-09 11:57:58 INFO (MainThread) [supervisor.store] Loading add-ons from store: 75 all - 0 new - 0 remove
23-06-09 11:57:58 INFO (MainThread) [supervisor.store] Loading add-ons from store: 75 all - 0 new - 0 remove
23-06-09 11:58:22 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
```

## System Information

version | core-2023.6.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.3
os_name | Linux
os_version | 6.1.19-v8+
arch | aarch64
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.1
agent_version | 1.4.1
docker_version | 23.0.2
disk_total | 113.1 GB
disk_used | 17.7 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.1), Zigbee2MQTT (1.31.2-1), File editor (5.6.0), ESPHome (2023.5.5), Studio Code Server (5.6.1), Samba share (10.0.2), Asterisk (4.0.4), motionEye (0.18.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 30, 2023 at 6:31 AM
-- | --
current_recorder_run | June 9, 2023 at 11:57 AM
estimated_db_size | 1395.14 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by viny182** [comment]
same here

**Comment by alexbelgium** [comment]
`KeyError: 'core_dnsmasq'`
