### ISSUE TITLE
Switchbot Intergration Issue

### ISSUE THREAD

**Issue by TH3xR34P3R** [home-assistant/supervisor#4498]
### Describe the issue you are experiencing

![e857abd9ffbae7b4cce8ab0e949a68cbdde16173](https://github.com/home-assistant/supervisor/assets/5105021/9d1738d1-598a-436b-a721-02d6300103f1)
![2444b1a1cb1d4501d5eba27eabdd71a5cfb18c7d](https://github.com/home-assistant/supervisor/assets/5105021/9c0183ce-95d1-4584-8932-6a941636fa8d)
![37194dc8685b2407664d8016f19c688b2e84a175](https://github.com/home-assistant/supervisor/assets/5105021/58b726a1-3276-469f-bc23-a960b4cde893)

As per the screenshots I have the bot added and its showing the option to use the momentary as well as its in the attributes but I get the error shown in the second screenshot when trying to use it through HA, I am wondering if there is a fix for this or there is something specific I need to do to get it to work properly.

I have made a thread here on the issue as well in the main forums but have not had any replies on it: https://community.home-assistant.io/t/switchbot-bot-actions/600846

It also states the password is incorrect for the bot in the logs but it is correct when I was adding it so not sure what is going on there.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Once added via the integration just click or tap on the on/off states in the actions for the bot and there is no response other than the error.

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/switchbot/entity.py:107
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:14:08 PM (1 occurrences)
Last logged: 8:14:08 PM

[139622127291456] bytearray index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switchbot/entity.py", line 107, in async_turn_off
    self._last_run_success = bool(await self._device.turn_off())
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/switchbot/devices/device.py", line 97, in _async_update_after_operation_wrap
    await self.update()
  File "/usr/local/lib/python3.11/site-packages/switchbot/devices/device.py", line 557, in update
    if info := await self.get_basic_info():
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/switchbot/devices/bot.py", line 104, in get_basic_info
    "battery": _data[1],
               ~~~~~^^^
IndexError: bytearray index out of range
```

## System Information

version | core-2023.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1266
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 6.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Mosquitto broker (6.2.1), VLC (0.2.0), Matter Server (4.9.0), Spotify Connect (0.12.4), Studio Code Server (5.10.1), File editor (5.6.0), Silicon Labs Multiprotocol (2.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 2
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 9, 2023 at 8:00 PM
-- | --
current_recorder_run | August 20, 2023 at 6:00 PM
estimated_db_size | 75.97 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by TH3xR34P3R** [comment]
Readded it with redoing the password and it started to work this time on the latest build, will reopen if issues occur in future builds.
