### ISSUE TITLE
Supervisor becomes unresponsive. API calls fail. Overall system degradation 

### ISSUE THREAD

**Issue by jasonhnz** [home-assistant/supervisor#4530]
### Describe the issue you are experiencing

Various features of HA supervisor are not functional. Backups do not show and I am unable to create backups in the UI. (clicking the button does nothing) 

Looking in the logs, there are various supervisor errors relating to API call issues, not being able to communicate with the API (which is why I believe the UI is failing) and other supervisor errors in CORE and supervisor log. 

Existing integrations are working (Zigbee etc..) however supervisor aspects are not.

Anecdotally, issues in the UI were noticed after one of the latest point releases for 2023.08. [3] or [4]. My CPU has been been higher over the last 3-4 days since those releases with random peaks up up to 90% for short spikes. Looking over the last week, CPU % was about 8-12% where this has gone up to about 20% now. 

No new integrations, or add-ons. Only updates applied was to the ring-mqtt add on for a point release as well as a node_red update. Both appear to be working fine but the only change I personally have made to the system.   

Running on Raspberry PI.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Restart HA or the host
2. Logs emit errors
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DOCKER_CONFIG/ContextType.SYSTEM
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-09-07 09:08:44 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-09-07 09:09:47 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-07 09:40:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DOCKER_CONFIG/ContextType.SYSTEM
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-09-07 10:08:44 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-09-07 10:10:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-09-07 10:16:10 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-09-07 10:22:40 INFO (SyncWorker_5) [supervisor.docker.manager] Restarting homeassistant
23-09-07 10:22:40 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
23-09-07 10:22:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-09-07 10:22:50 INFO (MainThread) [supervisor.host.info] Updating local host information
23-09-07 10:22:51 INFO (MainThread) [supervisor.host.services] Updating service information
23-09-07 10:22:51 INFO (MainThread) [supervisor.host.network] Updating local network information
23-09-07 10:22:52 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-09-07 10:22:52 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-09-07 10:22:53 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-09-07 10:23:00 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant
23-09-07 10:23:01 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-09-07 10:23:02 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-09-07 10:23:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
23-09-07 10:23:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/tsightler/ring-mqtt-ha-addon repository
23-09-07 10:23:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-09-07 10:23:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-09-07 10:23:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-09-07 10:23:06 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-09-07 10:23:12 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove
23-09-07 10:23:12 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove
23-09-07 10:24:13 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-09-07 10:24:13 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-09-07 10:24:13 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0b6b945_nodered
23-09-07 10:24:18 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-09-07 10:26:17 INFO (MainThread) [supervisor.backups.manager] Found 579 backup files
23-09-07 10:32:10 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 26f74a14
23-09-07 10:32:10 INFO (MainThread) [supervisor.backups.manager] Backing up 26f74a14 store Add-ons
23-09-07 10:32:10 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 15d21743_samba_backup
23-09-07 10:32:10 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 15d21743_samba_backup
23-09-07 10:32:10 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 26f74a14 completed
23-09-07 10:32:11 INFO (MainThread) [supervisor.backups.manager] Found 580 backup files
23-09-07 10:32:39 INFO (MainThread) [supervisor.backups.manager] Found 580 backup files
23-09-07 10:35:25 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
23-09-07 10:36:38 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from 03cabcc9_ring_mqtt
23-09-07 10:36:38 WARNING (MainThread) [supervisor.misc.tasks] Watchdog/Application found a problem with observer plugin!
23-09-07 10:36:38 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: 
23-09-07 10:36:38 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot write to closing transport
23-09-07 10:36:38 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-09-07 10:37:11 INFO (SyncWorker_0) [supervisor.docker.manager] Stopping hassio_observer application
23-09-07 10:37:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-09-07 10:37:12 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0b6b945_nodered
23-09-07 10:37:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-09-07 10:37:12 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning hassio_observer application
23-09-07 10:37:12 WARNING (MainThread) [supervisor.plugins.base] Watchdog found observer plugin failed, restarting...
23-09-07 10:37:12 INFO (MainThread) [supervisor.plugins.observer] Starting observer plugin
23-09-07 10:37:12 ERROR (MainThread) [supervisor.plugins.observer] Can't start observer plugin
23-09-07 10:37:12 ERROR (MainThread) [supervisor.plugins.base] Watchdog restart of observer plugin failed!
23-09-07 10:37:12 INFO (MainThread) [supervisor.plugins.observer] Starting observer plugin
23-09-07 10:37:14 INFO (MainThread) [supervisor.docker.observer] Starting Observer ghcr.io/home-assistant/aarch64-hassio-observer with version 2023.06.0 - 172.30.32.6
```

## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4949
Installed Version | 1.32.1
Stage | running
Available Repositories | 1290
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | [removed]
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | false
remote_server | ap-southeast-1-1.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 457.7 GB
disk_used | 209.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.11.0), File editor (5.6.0), Samba share (10.0.2), Terminal & SSH (9.7.1), Node-RED (14.4.5), deCONZ (6.20.0), Mosquitto broker (6.2.1), Ring-MQTT with Video Streaming (5.6.2), Samba Backup (5.2.0), Vaultwarden (Bitwarden) (0.19.4), SQLite Web (3.9.2), Studio Code Server (5.10.1), Grafana (8.2.1), Piper (1.3.2), Whisper (1.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 9
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 6, 2023 at 6:52 AM
-- | --
current_recorder_run | September 7, 2023 at 10:23 AM
estimated_db_size | 1356.00 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Additional information

Relevant CORE logs re supervisor (occur after reboot) 

Logger: homeassistant.components.hassio
Source: helpers/update_coordinator.py:229
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:28:29 AM (1 occurrences)
Last logged: 10:28:29 AM

Error fetching hassio data: Error on Supervisor API:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:536
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:33:14 AM (1 occurrences)
Last logged: 10:33:14 AM

Can't read Supervisor data:

Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:49
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:28:29 AM (14 occurrences)
Last logged: 10:33:39 AM

Timeout on /os/info request
Timeout on /core/stats request
Timeout on /supervisor/info request
Timeout on /info request
Timeout on /supervisor/stats request
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:130
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:26:27 AM (6 occurrences)
Last logged: 10:34:14 AM

Failed to to call /backups/reload -
Failed to to call /host/info -
Failed to to call /backups -
Failed to to call /addons -

**Comment by jasonhnz** [comment]
Have stopped and restarted HAOS after stopping the ring-mqtt add-on. 

On reboot, trying to view backups, supervisior logs show the following.

23-09-07 11:03:51 INFO (MainThread) [supervisor.backups.manager] Found 580 backup files
23-09-07 11:03:53 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-31623' coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:462> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 505, in start
    request = self._request_factory(message, payload, self, writer, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 446, in _make_request
    return _cls(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_request.py", line 811, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_request.py", line 188, in __init__
    assert transport is not None
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by jasonhnz** [comment]
Closing.... I'm not sure how this could effect it, but I removed the network storage I had setup to my NAS (but not selected in backup - was set to data disk) and this has resolved the issue. The backups loaded immediately (~5 sec) after removing the network storage. I rebooted and visited the logs again and previous issues reported had gone. ?  Happy to have stable system again.
