### ISSUE TITLE
Ingress for Add-ons broken after update to 2023.9.0

### ISSUE THREAD

**Issue by chrisx8** [home-assistant/supervisor#4547]
### Describe the issue you are experiencing

After updating to Home Assistant 2023.9.0, Ingress for all Add-ons seems to be broken. I can no longer open any Add-ons from Home Assistant UI. The UI presents me an "500 Internal Server Error" and inside the supervisor logs a bunch of exceptions is thrown. Reverting back to Home Assistant 2023.8.4 resolves the issues.

Related: https://github.com/home-assistant/core/issues/99811. Some troubleshooting were done and it seems that there might be a Supervisor issue:

> It seems that connection.user.id is not None, and the user_id attribute is being set properly, but Ingress breaks when user_id is set.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Install an Add-on with Ingress, like `core-ssh`
2. Click "Open Web UI" on the Add-on page
3. See error:
```
500 Internal Server Error
Server got itself in trouble
```

### Anything in the Supervisor logs that might be useful for us?

```txt
23-09-10 17:49:05 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 220, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/ingress.py", line 141, in handler
    return await self._handle_request(request, addon, path, session_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/ingress.py", line 217, in _handle_request
    async with self.sys_websession.request(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 558, in _request
    resp = await req.send(conn)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 670, in send
    await writer.write_headers(status_line, self.headers)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 129, in write_headers
    buf = _serialize_headers(status_line, headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None
```

### System Health information

Host Operating System | Home Assistant OS 10.5
-- | --
Update Channel | stable
Supervisor Version | supervisor-2023.08.3
Agent Version | 1.5.1
Docker Version | 23.0.6
Disk Total | 30.8 GB
Disk Used | 4.5 GB
Healthy | true
Supported | true
Board | ova
Supervisor API | ok
Version API | ok
Installed Add-ons | NGINX Home Assistant SSL proxy (3.5.0), Terminal & SSH (9.7.1), Mosquitto broker (6.3.1), Zigbee2MQTT (1.33.0-1)

### Supervisor diagnostics

[config_entry-hassio-dded8081695934f67215bb713aae4677.json.txt](https://github.com/home-assistant/supervisor/files/12570707/config_entry-hassio-dded8081695934f67215bb713aae4677.json.txt)

**Comment by chrisx8** [comment]
Ahh I found the issue. I'm using [Command Line Authentication](https://www.home-assistant.io/docs/authentication/providers/#command-line) for HA Core, which means my account's username is `None`. This causes Supervisor to fail.

I created a user with the default [Home Assistant Auth Provider](https://www.home-assistant.io/docs/authentication/providers/#home-assistant-auth-provider), and there is no issue if I use this user.
