### ISSUE TITLE
Unable to update (later install) Advanced SSH

### ISSUE THREAD

**Issue by lcbester** [home-assistant/supervisor#4758]
### Describe the issue you are experiencing

I suffered a power failure while updating Advanced SSH to 17.0.0.

After system restarted, I tried the update again, it failed again.

I removed 16.0.0.2 and restarted HA
I then tried to do a fresh install of Advanced SSH, and it failed.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Steps to reproduce
Unsure

Try a power failure while updating, I am not sure it is related though.

### Anything in the Supervisor logs that might be useful for us?

```txt
Can't install ghcr.io/hassio-addons/ssh/aarch64:17.0.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/ssh/aarch64:17.0.0/json: Not Found ("No such image: ghcr.io/hassio-addons/ssh/aarch64:17.0.0")
```

## System Information

version | core-2023.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.58-haos-raspi
arch | aarch64
timezone | Africa/Johannesburg
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1420
Downloaded Repositories | 28

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 234.3 GB
disk_used | 29.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (16.0.2), motionEye (0.19.1), Node-RED (16.0.2), Sunsynk Inverter Add-on (2022.11.29-0.2.5), eWeLink Smart Home (1.4.3), Duck DNS (1.15.0), Mosquitto broker (6.4.0), Google Assistant SDK (2.5.0), File editor (5.7.0), Whatsapp (1.3.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 24
-- | --
resources | 15
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 3, 2023 at 10:21
-- | --
current_recorder_run | December 9, 2023 at 08:23
estimated_db_size | 1211.59 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.3 (a8c6d45)
-- | --
cloud_online | 4 / 14
local_online | 2 / 2
debug | failed to load: 

</details>

### Supervisor diagnostics

[config_entry-hassio-748a13fbeae54fae2c7a847806d489fe.json.txt](https://github.com/home-assistant/supervisor/files/13634099/config_entry-hassio-748a13fbeae54fae2c7a847806d489fe.json.txt)

**Comment by lcbester** [comment]
Updated Core to 2023.12.3 and tried update again - still not working.  Full logs below


Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 2:18:04 PM (1 occurrences)
Last logged: 2:18:04 PM

[547950613824] Error updating Advanced SSH & Web Terminal: Can't install ghcr.io/hassio-addons/ssh/aarch64:17.0.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/ssh/aarch64:17.0.0/json: Not Found ("No such image: ghcr.io/hassio-addons/ssh/aarch64:17.0.0")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/hassio-addons/ssh/aarch64:17.0.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/ssh/aarch64:17.0.0/json: Not Found ("No such image: ghcr.io/hassio-addons/ssh/aarch64:17.0.0")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Advanced SSH & Web Terminal: Can't install ghcr.io/hassio-addons/ssh/aarch64:17.0.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/ssh/aarch64:17.0.0/json: Not Found ("No such image: ghcr.io/hassio-addons/ssh/aarch64:17.0.0")
