### ISSUE TITLE
Error updating Home Assistant Supervisor: Abort update because of an issue with AppArmor: Can't fetch AppArmor profile https://version.home-assistant.io/apparmor_beta.txt: Timeout

### ISSUE THREAD

**Issue by TICHIEM** [home-assistant/supervisor#4765]
### Describe the issue you are experiencing

Error updating Home Assistant Supervisor: Abort update because of an issue with AppArmor: Can't fetch AppArmor profile https://version.home-assistant.io/apparmor_beta.txt: Timeout

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.Error updating Home Assistant Supervisor: Abort update because of an issue with AppArmor: Can't fetch AppArmor profile https://version.home-assistant.io/apparmor_beta.txt: Timeout
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:53:00 AM (3 occurrences)
Last logged: 2:00:19 AM

[140456319542208] Error updating Home Assistant Supervisor: Abort update because of an issue with AppArmor: Can't fetch AppArmor profile https://version.home-assistant.io/apparmor_beta.txt: Timeout
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 258, in async_install
    await async_update_supervisor(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Abort update because of an issue with AppArmor: Can't fetch AppArmor profile https://version.home-assistant.io/apparmor_beta.txt: Timeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 260, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Abort update because of an issue with AppArmor: Can't fetch AppArmor profile https://version.home-assistant.io/apparmor_beta.txt: Timeout
```

### System Health information

.

**Comment by TICHIEM** [comment]
managed to fix the issue by changing the usb port where i had connected the ethernet adapter. seems its network related
