### ISSUE TITLE
ESPHome Dev addon triggers raising RuntimeError when checking ingress_port

### ISSUE THREAD

**Issue by bdraco** [home-assistant/supervisor#4807]
### Describe the issue you are experiencing

<img width="503" alt="Screenshot 2024-01-09 at 1 27 19 PM" src="https://github.com/home-assistant/supervisor/assets/663432/a199bd36-6523-4b65-92e5-82d6f86abe15">

looks like this started happening after https://github.com/home-assistant/supervisor/commit/883e54f98941398e0dcc84b11d93012658d106bd

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. open esphome dev addon
2. click rebuild
3. wait for rebuild
4. try to enter the addon, issue will likely occur

Workaround: rebooting the host will get back to a working state

### Anything in the Supervisor logs that might be useful for us?

```txt
[31m24-01-09 13:20:48 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 186, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 202, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 269, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 456, in addons_addon_info
    return await api_addons.info(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/addons.py", line 253, in info
    ATTR_INGRESS_PORT: addon.ingress_port,
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 401, in ingress_port
    raise RuntimeError(f"No port set for add-on {self.slug}")
RuntimeError: No port set for add-on 5c53de3b_esphome-dev[0m
```
```


### System Health information

n/a

### Supervisor diagnostics

_No response_

### Additional information

_No response_

**Comment by bdraco** [comment]
I haven't had a chance to dig into what causes this yet but I didn't want to forget to document it since it was also reported on ESPHome discord

**Comment by agners** [comment]
We've changed from setting that particular port in the getter "on request" to setting it ahead of time (when installing/updating the add-on). During the review there was a concern if we'd cover all code paths, and it seems we did not :cry:
