### ISSUE TITLE
Host log does not work

### ISSUE THREAD

**Issue by DChe47** [home-assistant/supervisor#4871]
### Describe the issue you are experiencing

I found problems in the Host Log like these:
```
Nov 03 21:19:28 homeassistant systemd-journal-gatewayd[18665]: microhttpd: Setting TCP_NODELAY option to ON state failed: Operation not supported
Nov 03 21:19:28 homeassistant systemd-journal-gatewayd[18665]: microhttpd: Setting TCP_CORK option to OFF state failed: Operation not supported
Nov 03 21:19:28 homeassistant systemd-journal-gatewayd[18665]: microhttpd: Failed to push the data from buffers to the network. Client may experience some de>
Nov 03 21:19:28 homeassistant systemd-journal-gatewayd[18665]: microhttpd: Setting TCP_NODELAY option to ON state failed: Operation not supported
Nov 03 21:19:28 homeassistant systemd-journal-gatewayd[18665]: microhttpd: Setting TCP_CORK option to OFF state failed: Operation not supported
Nov 03 21:19:28 homeassistant systemd-journal-gatewayd[18665]: microhttpd: Failed to push the data from buffers to the network. Client may experience some de>
````
(I found this here): [https://github.com/home-assistant/supervised-installer/issues/247](url)

I did as it recommended:
`sudo rm -rf /run/systemd-journal-gatewayd.sock
sudo touch /run/systemd-journal-gatewayd.sock
sudo reboot`

And after that I don't have Host Log at all.
If I run: `sudo systemctl status systemd-journal-gatewayd.service`
then there is such a problem:
```
● systemd-journal-gatewayd.service - Journal Gateway Service
     Loaded: loaded (/lib/systemd/system/systemd-journal-gatewayd.service; indirect; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2024-02-02 20:05:07 MSK; 8s ago
TriggeredBy: ● systemd-journal-gatewayd.socket
       Docs: man:systemd-journal-gatewayd(8)
    Process: 582977 ExecStart=/lib/systemd/systemd-journal-gatewayd (code=exited, status=1/FAILURE)
   Main PID: 582977 (code=exited, status=1/FAILURE)

фев 02 20:05:07 ha-master systemd[1]: Started Journal Gateway Service.
фев 02 20:05:07 ha-master systemd-journal-gatewayd[582977]: Can't listen on more than one socket.
фев 02 20:05:07 ha-master systemd[1]: systemd-journal-gatewayd.service: Main process exited, code=exited, status=1/FAILURE
фев 02 20:05:07 ha-master systemd[1]: systemd-journal-gatewayd.service: Failed with result 'exit-code'.
```
I don't know Debian very well yet, please help me fix this problem.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

I run this to fix problems in the Host Log:
`sudo rm -rf /run/systemd-journal-gatewayd.sock
sudo touch /run/systemd-journal-gatewayd.sock
sudo reboot`

### Anything in the Supervisor logs that might be useful for us?

```txt
24-02-02 18:12:46 INFO (MainThread) [supervisor.host.manager] Host information reload completed
24-02-02 18:20:46 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
24-02-02 18:35:46 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
24-02-02 18:36:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
24-02-02 18:50:46 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
24-02-02 19:05:22 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
24-02-02 19:05:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
24-02-02 19:05:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
24-02-02 19:05:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.check] System checks complete
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
24-02-02 19:05:23 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
24-02-02 19:05:46 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
24-02-02 19:06:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
24-02-02 19:07:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
24-02-02 19:07:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
24-02-02 19:07:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
24-02-02 19:07:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
24-02-02 19:07:47 INFO (MainThread) [supervisor.store] Loading add-ons from store: 80 all - 0 new - 0 remove
24-02-02 19:07:47 INFO (MainThread) [supervisor.store] Loading add-ons from store: 80 all - 0 new - 0 remove
24-02-02 19:20:46 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
24-02-02 19:35:46 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
24-02-02 19:36:32 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
24-02-02 19:50:46 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
24-02-02 20:03:48 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1412, in _create_connection
    _, proto = await self._loop.create_unix_connection(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 259, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 636, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/aiohttp.py", line 139, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 115, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/aiohttp.py", line 129, in sentry_app_handle
    response = await old_handle(self, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 186, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 202, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 269, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 189, in advanced_logs
    async with self.sys_host.logs.journald_logs(
  File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/host/logs.py", line 148, in journald_logs
    async with session.get(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1418, in _create_connection
    raise UnixClientConnectorError(self.path, req.connection_key, exc) from exc
aiohttp.client_exceptions.UnixClientConnectorError: Cannot connect to unix socket /run/systemd-journal-gatewayd.sock ssl:default [Connection refused]
```

## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.10.0-27-amd64
arch | x86_64
timezone | Europe/Moscow
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.5.1
docker_version | 25.0.1
disk_total | 233.7 GB
disk_used | 64.5 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.2-1), Studio Code Server (5.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 5 января 2024 г. в 16:07
-- | --
current_recorder_run | 28 января 2024 г. в 22:04
estimated_db_size | 686.53 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

[config_entry-hassio-67fd06ff2af0b3eba4d5ca7e9e12884d.json.txt](https://github.com/home-assistant/supervisor/files/14143577/config_entry-hassio-67fd06ff2af0b3eba4d5ca7e9e12884d.json.txt)

**Comment by DChe47** [comment]
I fix it.

**Comment by DChe47** [comment]
I fix it by recovery /etc/systemd/system/systemd-journal-gatewayd.socket.d and repeat:
sudo rm /run/systemd-journal-gatewayd.sock
sudo touch /run/systemd-journal-gatewayd.sock
sudo reboot
