### ISSUE TITLE
Add-ons stopped auto updating

### ISSUE THREAD

**Issue by mateuszdrab** [home-assistant/supervisor#4896]
### Describe the issue you are experiencing

I've recently noticed that addons are not auto updating on my various instances of Home Assistant.

I've found the below error in supervisor's logs which started on the 8th of Feb.

I'd like to understand if this is a supervisor bug or perhaps some of my custom repositories changed something which results in supervisor breaking.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Have addons with auto-updates enabled
Latest supervisor installed

### Anything in the Supervisor logs that might be useful for us?

```txt
24-02-15 10:05:30 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1411288' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 304, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 109, in _update_addons
    if utcnow() + timedelta(days=1) > addon.latest_version_timestamp:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 317, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
```

## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1405
Downloaded Repositories | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 53.4 GB
disk_used | 34.5 GB
healthy | true
supported | failed to load: Unsupported
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Let's Encrypt (5.0.15), Studio Code Server (5.15.0), TasmoAdmin (0.29.1), Node-RED (17.0.7), Mosquitto broker (6.4.0), Samba share (12.3.0), SQLite Web (4.1.2), AirCast (4.2.0), Advanced SSH & Web Terminal (17.1.0), Prometheus Node Exporter (0.8.2), ESPHome (2023.12.9), Matter Server (5.1.2), Whisper (1.0.2), Piper (1.4.0), Promtail (edge), Zigbee2MQTT (1.35.3-1), openWakeWord (1.8.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 19
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 22, 2023 at 14:52
-- | --
current_recorder_run | February 10, 2024 at 01:55
estimated_db_size | 10648.73 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Additional information

Supervisor shows as unsupported due to the Portainer agent running. 
This has been the case for a year or so and never was an issue - I can however; remove it to see if it helps.
Bearing the above error, I don't think it is a purpose introduced limitation due to the unsupported state but a bug in the code most likely.

**Comment by mateuszdrab** [comment]
Hi @agners 

Thanks for the fix, whilst the error does not show any more - addon updates are still not working.

Please see the referenced issue
