### ISSUE TITLE
ODROID N2+ WLAN/BT dongle doesn't work after updating to 12.1

### ISSUE THREAD

**Issue by aambroze** [home-assistant/supervisor#4977]
### Describe the issue you are experiencing

RTL8821CU wasn't working properly on HA OS in 12.0 due to transition to in-tree drivers.

Device itself is an official ODROID USB WIFI/BT Dongle meant to work with ODROID N2+ / HA BLUE.

This change was reverted in https://github.com/home-assistant/operating-system/pull/3225 and included in HA OS 12.1 release.

After updating to HA OS 12.1 WLAN adapter now shows in HA OS but OS is unable to configure it due to some errors in Supervisor. I've reported the issue in https://github.com/home-assistant/operating-system/issues/3255 and was instructed to report the problem here.

<img width="280" alt="image" src="https://github.com/home-assistant/supervisor/assets/48318169/81823bae-ec6e-49e4-bebd-a1a2f0688141">

<img width="433" alt="image" src="https://github.com/home-assistant/supervisor/assets/48318169/dea9063e-a9a5-4524-bbea-23b6dd19667b">

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Have ODROID WIFI/BT Dongle (or any dongle incorporating RTL8821CU)
2. Update 11.5 to 12.1
3. WLAN isn't functional anymore.

### Anything in the Supervisor logs that might be useful for us?

```txt
24-03-22 17:32:33 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
24-03-22 17:32:33 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
24-03-22 17:32:33 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_ssh
24-03-22 17:32:33 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_ssh
24-03-22 17:32:38 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
24-03-22 17:33:03 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/wlan0/update access from core_ssh
24-03-22 17:33:03 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 189, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 205, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 272, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 283, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 63, in wrap_api
    answer = await method(api, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/network.py", line 222, in interface_update
    await asyncio.shield(self.sys_host.network.apply_changes(interface))
  File "/usr/src/supervisor/supervisor/host/network.py", line 221, in apply_changes
    settings = get_connection_from_interface(interface, self.sys_dbus.network)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/dbus/network/setting/generate.py", line 141, in get_connection_from_interface
    "ssid": Variant("ay", interface.wifi.ssid.encode("UTF-8")),
                          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ssid'
```

## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | aarch64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4946
Installed Version | 1.34.0
Stage | running
Available Repositories | 1401
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 56.6 GB
disk_used | 6.9 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), Terminal & SSH (9.10.0), Cloudflared (5.1.6), Home Assistant Google Drive Backup (0.112.1), File editor (5.8.0), Mosquitto broker (6.4.0), Zigbee2MQTT (1.36.0-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 2
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 14 marca 2024 o 14:57
-- | --
current_recorder_run | 22 marca 2024 o 17:32
estimated_db_size | 40.30 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Supervisor diagnostics

[config_entry-hassio-8302e49fdefff51c8551e0885c7aa39f.json](https://github.com/home-assistant/supervisor/files/14725904/config_entry-hassio-8302e49fdefff51c8551e0885c7aa39f.json)

**Comment by agners** [comment]
The network configuration has no WiFi mode/SSID/authentication information, that is why that stack trace is caused.

Granted, Supervisor should handle this a bit more gracefully and send back an appropriate error.

But when passing WiFi information (`--wifi-auth`, ` --wifi-mode`, ` --wifi-psk` and ` --wifi-ssid`), things should work again.

**Comment by aambroze** [comment]
I’ll try.

Even if that’s the case and it’s about providing proper network details and not graceful response…

Is it expected that my network details can be wiped during update from 11.5 to 12.1?  Maybe that’s my actual issue ?

**Comment by aambroze** [comment]
@agners 
Thank you for suggestion.

I've connected using Ethernet and successfully enabled and connected to WiFi.

This leaves us with two issues:
- very ungraceful Supervisor behavior (crash/500 instead of simple information about required params),
- updating HAOS from 11.5 to 12.1 wipes WLAN details.

I'll redact my report to reflect the first issue. Where should I report second one?

**Comment by agners** [comment]
> * updating HAOS from 11.5 to 12.1 wipes WLAN details.
> 
> 
> I'll redact my report to reflect the first issue. Where should I report second one?

This would go to the [Home Assistant Operating System repository](https://github.com/home-assistant/operating-system/).
