### ISSUE TITLE
Unable to view supervisor (or addon) logs when running in devcontainer

### ISSUE THREAD

**Issue by lildude** [home-assistant/supervisor#5021]
### Describe the issue you are experiencing

Attempting to view any of the logs within the devcontainer fails with `Failed to get supervisor logs, No systemd-journal-gatewayd Unix socket available`:

![Failed to get supervisor logs, No systemd-journal-gatewayd Unix socket available](https://github.com/home-assistant/supervisor/assets/627280/5740ea3d-1a65-4473-8bda-a9b34704ff85)

I first noticed this when my addon devcontainer suddenly started reporting this error and then discovered opening this repo's devcontainer experiences the same issue.

After a lot of digging and debugging, https://github.com/home-assistant/supervisor/pull/4963 appears to be the PR that introduced the changes that "broke" the ability to view the logs when running in the devcontainer. Checking out the commit before, 0e0fadd7, and following the repro steps "fixes" the issue.

Forcing the addon container to use supervisor version `2024.03.1.dev1803` in `/etc/supervisor_scripts/common` within the addon devcontainer resolves the issue too.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

1. Clone https://github.com/home-assistant/supervisor to your system
2. Open in VSCode
3. Accept the prompt to re-open in a container
4. Start the supervisor by running the "Run Supervisor" task
5. Open 0.0.0.0:9123 in your browser and configure as normal
6. Go to Settings -> System -> Logs -> Supervisor
7. 💥 

### Anything in the Supervisor logs that might be useful for us?

```
2024-04-17 11:18:25.410 WARNING (MainThread) [supervisor.resolution.evaluations.base] Systemd journal is not working correctly or inaccessible (more-info: https://www.home-assistant.io/more-info/unsupported/systemd_journal)
2024-04-17 11:18:25.411 WARNING (MainThread) [supervisor.resolution.evaluations.base] NetworkManager is not correctly configured (more-info: https://www.home-assistant.io/more-info/unsupported/network_manager)
2024-04-17 11:18:25.412 WARNING (MainThread) [supervisor.resolution.evaluations.base] Docker cgroup version 2 is not supported! {'1'} (more-info: https://www.home-assistant.io/more-info/unsupported/cgroup_version)
2024-04-17 11:18:25.413 WARNING (MainThread) [supervisor.resolution.evaluations.base] Systemd is not correctly working (more-info: https://www.home-assistant.io/more-info/unsupported/systemd)
2024-04-17 11:18:25.415 WARNING (MainThread) [supervisor.resolution.evaluations.base] Detected unsupported OS: None (more-info: https://www.home-assistant.io/more-info/unsupported/os)
2024-04-17 11:18:25.416 WARNING (MainThread) [supervisor.resolution.evaluations.base] Systemd-Resolved is required for DNS in Home Assistant. (more-info: https://www.home-assistant.io/more-info/unsupported/systemd_resolved)
[...]
2024-04-17 11:18:25.425 WARNING (MainThread) [supervisor.core] System running in a unsupported environment!
[...]
2024-04-17 11:21:07.926 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
```

The warnings have never caused a problem in the past.

### System Health information

I'd expect this information to be the same for everyone using a devcontainer, but here it is anyway...

## System Information

version | core-2024.5.0.dev202404170214
-- | --
installation_type | Home Assistant Supervised
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.5.0-15-generic
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | null
-- | --
update_channel | dev
supervisor_version | supervisor-99.9.9dev
agent_version | 1.5.1
docker_version | 26.0.0
disk_total | 57.1 GB
disk_used | 17.6 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17 April 2024 at 10:19
-- | --
current_recorder_run | 17 April 2024 at 11:19
estimated_db_size | 0.18 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Supervisor diagnostics

I'd expect this information to be the same for everyone using a devcontainer, but here it is anyway...

[config_entry-hassio-aeaf2659651912a2e24f178a0de34d7d.json](https://github.com/home-assistant/supervisor/files/15009580/config_entry-hassio-aeaf2659651912a2e24f178a0de34d7d.json)

/cc @sairon as the author of https://github.com/home-assistant/supervisor/pull/4963

**Comment by sairon** [comment]
Thanks for the concise report and sorry for the inconvenience caused. Getting logs in Devcontainer is something we forgot about when implementing the new logging source. A warning sign should have been the Host logs, which have never worked in Devcontainer (yet no one cared there), and also the warning message about Systemd journal unavailable during Supervisor startup. Because this is rather an edge case, I have highlighted the necessity of having the journal gateway working in https://github.com/home-assistant/home-assistant.io/pull/32356

Anyway, I don't dispute it is handy to have an easy way to access logs when developing add-ons, so a fallback should be used also there. In fact, there **is** fallback implemented for the Supervisor logs but it doesn't work. It took me a while to figure out what's going but when `supervisor.api.host.APIHost.advanced_logs` is called, the error raised in the function implementation is actually caught only in the code of `api_process_raw` decorator but not in the `get_supervisor_logs` handler within `supervisor.api.RestAPI` which should use the fallback then. There is even a test case that tests that if the advanced logging backend fails, the Docker backend is used instead, but that case gives a false positive result - still need to figure out what's going on there - but it's been a long day here, so I'll have a look at it tomorrow.

It should be possible to fix this fairly easy, and it also helped to discover a more serious bug, so thanks again for reporting the issue.

**Comment by agners** [comment]
With #5022 merged, this should be addressed.

**Comment by lildude** [comment]
Confirmed. I can view all logs in a devcontainer with the latest image. Thanks.

**Comment by lildude** [comment]
Cancel that. The addon logs are still not available and show he same error as before. 

The spervisor log now reports:

```
2024-04-26 09:19:32.641 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-04-26 09:19:32.641 ERROR (MainThread) [supervisor.api] Failed to get supervisor logs using advanced_logs API
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 404, in get_supervisor_logs
    return await self._api_host.advanced_logs_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 207, in advanced_logs_handler
    async with self.sys_host.logs.journald_logs(
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/host/logs.py", line 143, in journald_logs
    raise HostNotSupportedError(
supervisor.exceptions.HostNotSupportedError: No systemd-journal-gatewayd Unix socket available
2024-04-26 09:19:32.809 DEBUG (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from Home Assistant
2024-04-26 09:19:32.810 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-04-26 09:19:32.810 ERROR (MainThread) [supervisor.api] Failed to get supervisor logs using advanced_logs API
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 404, in get_supervisor_logs
    return await self._api_host.advanced_logs_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 207, in advanced_logs_handler
    async with self.sys_host.logs.journald_logs(
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/host/logs.py", line 143, in journald_logs
    raise HostNotSupportedError(
supervisor.exceptions.HostNotSupportedError: No systemd-journal-gatewayd Unix socket available
```

@sairon @agners want a new issue or will you reopen this one?

**Comment by agners** [comment]
As per #5040, we still print the stack trace in this case, but it should fallback to the Docker logs.

@sairon these stack traces can confuse during development. maybe we could turn it into a warning in this case instead? :thinking:

**Comment by kloodhu** [comment]
I have the exact same error message, and all addon shows the "No systemd-journal-gatewayd Unix socket available" message when i try to open the Log page.

**Comment by dxmnkd316** [comment]
Had the same issue after the latest Supervisor was pushed.  Was on Raspbian 11 running Supervised (don't judge).  Finally migrating to HAOS solved the issue for me.  Obviously that's not always feasible depending on individual needs, but it was enough of a problem to make me finally take the effort to migrate.

**Comment by tpjanssen** [comment]
I'm having the same issue as @lildude , with same traces:

```
2024-05-02 12:46:45.323 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-02 12:46:55.183 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-02 12:46:55.183 ERROR (MainThread) [supervisor.api] Failed to get supervisor logs using advanced_logs API
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 404, in get_supervisor_logs
    return await self._api_host.advanced_logs_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 207, in advanced_logs_handler
    async with self.sys_host.logs.journald_logs(
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/host/logs.py", line 143, in journald_logs
    raise HostNotSupportedError(
supervisor.exceptions.HostNotSupportedError: No systemd-journal-gatewayd Unix socket available
2024-05-02 12:46:55.791 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-02 12:46:55.791 ERROR (MainThread) [supervisor.api] Failed to get supervisor logs using advanced_logs API
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 404, in get_supervisor_logs
    return await self._api_host.advanced_logs_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 207, in advanced_logs_handler
    async with self.sys_host.logs.journald_logs(
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/host/logs.py", line 143, in journald_logs
    raise HostNotSupportedError(
supervisor.exceptions.HostNotSupportedError: No systemd-journal-gatewayd Unix socket available
```

**Comment by lmagyar** [comment]
Same error, I've tried HA add-on + devcontainer the first time on Windows 11, WSL2, Ubuntu 24.04, Docker Desktop 4.30.0

I've followed the instructions [here](https://developers.home-assistant.io/docs/add-ons/testing/)

I've developed add-on for years on real HW, this is the first time I'm trying this on devcontainer. Total newbie in devcontainer.

Unsupported system:
- Operating System
- Network Manager issues
- Content-trust check disabled
- Systemd-Resolved issues
- Systemd Journal issues
- AppArmor issues
- Docker misconfigured
- Systemd issues

## System Information

version | core-2024.6.0.dev202405070218
-- | --
installation_type | Home Assistant Supervised
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.15.146.1-microsoft-standard-WSL2
arch | x86_64
timezone | Europe/Budapest
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | null
-- | --
update_channel | dev
supervisor_version | supervisor-2024.05.1.dev0705
agent_version | 1.5.1
docker_version | 26.1.0
disk_total | 1006.9 GB
disk_used | 5.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | [BETA] In-memory MariaDB (2.7.1.1-rc07)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 7, 2024 at 6:00 PM
-- | --
current_recorder_run | May 7, 2024 at 8:00 PM
estimated_db_size | 0.19 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by sunshine-hass** [comment]
I also encountered the same problem since May, the CPU is aarch64

**Comment by dunxd** [comment]
I'm getting this in Supervisor 2024.06.2.dev2103.  I would really like to be able to get access to the logs for the add-on I am developing in a devcontainer.
