### ISSUE TITLE
No systemd-journal-gatewayd Unix socket available

### ISSUE THREAD

**Issue by Destroyer061090** [home-assistant/supervisor#5056]
### Describe the issue you are experiencing

after updating supervisor at latest version all the logs of addons has following error:
"Impossibile ottenere i registri del componente aggiuntivo, No systemd-journal-gatewayd Unix socket available"

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-05-03 12:45:01.906 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:5000 ssl:default [Connect call failed ('172.30.33.1', 5000)]
2024-05-03 12:45:10.484 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-03 12:45:13.809 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-03 12:45:14.855 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-03 12:45:28.934 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-03 12:45:44.295 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:5000 ssl:default [Connect call failed ('172.30.33.1', 5000)]
2024-05-03 12:45:46.580 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:5000 ssl:default [Connect call failed ('172.30.33.1', 5000)]
2024-05-03 12:47:17.651 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 12:50:31.108 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-05-03 12:50:31.494 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
2024-05-03 12:50:31.523 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-05-03 12:51:39.664 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 257
2024-05-03 12:51:39.669 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_vscode closed
2024-05-03 12:52:17.669 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 12:57:17.657 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 12:57:19.415 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
2024-05-03 13:02:17.752 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:03:19.680 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-03 13:07:17.762 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:12:17.744 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:12:19.417 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
2024-05-03 13:17:17.664 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:22:17.642 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:27:17.638 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:27:19.311 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-05-03 13:27:19.311 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-05-03 13:27:19.311 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
2024-05-03 13:27:19.311 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-05-03 13:27:19.313 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-05-03 13:27:19.352 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-05-03 13:27:19.352 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-05-03 13:27:19.352 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-05-03 13:27:19.419 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
2024-05-03 13:27:21.520 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-05-03 13:27:21.521 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-05-03 13:27:21.521 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-05-03 13:27:21.522 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-05-03 13:27:21.525 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-05-03 13:27:21.525 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-05-03 13:27:21.660 ERROR (MainThread) [supervisor.resolution.evaluations.container] Found image in unhealthy image list 'portainer/portainer-ce' on the host
2024-05-03 13:27:22.524 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-05-03 13:27:22.524 CRITICAL (MainThread) [supervisor.jobs] The following job conditions are ignored and will make the system unstable when they occur: {<JobCondition.HEALTHY: 'healthy'>}
2024-05-03 13:27:22.524 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-05-03 13:27:22.525 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-05-03 13:32:17.646 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:33:19.973 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-03 13:37:17.639 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:38:32.836 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_a0d7b954_nodered application
2024-05-03 13:38:35.548 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-03 13:38:43.117 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/amd64 with version 17.0.12
2024-05-03 13:42:17.639 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:42:19.421 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
2024-05-03 13:47:17.644 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:47:30.141 INFO (SyncWorker_5) [supervisor.docker.manager] Restarting homeassistant
2024-05-03 13:47:30.748 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for f4f71350_ewelink_smart_home_slug closed
2024-05-03 13:47:30.753 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for f4f71350_ewelink_smart_home_slug closed
2024-05-03 13:47:57.416 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
2024-05-03 13:48:18.607 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-05-03 13:48:18.723 ERROR (MainThread) [supervisor.resolution.evaluations.container] Found image in unhealthy image list 'portainer/portainer-ce' on the host
2024-05-03 13:48:18.864 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-05-03 13:48:18.925 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:48:22.516 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to NOT_RUNNING
2024-05-03 13:49:28.701 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to STARTING
2024-05-03 13:49:38.746 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to RUNNING
2024-05-03 13:49:38.749 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
2024-05-03 13:49:56.149 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-03 13:51:30.898 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-05-03 13:51:31.089 INFO (MainThread) [supervisor.api.proxy] WebSocket access from f4f71350_ewelink_smart_home_slug
2024-05-03 13:51:31.100 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-05-03 13:53:19.282 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:54:43.037 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-05-03 13:54:44.056 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-03 13:55:53.900 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-03 13:55:53.900 ERROR (MainThread) [supervisor.api] Failed to get supervisor logs using advanced_logs API
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 404, in get_supervisor_logs
    return await self._api_host.advanced_logs_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 207, in advanced_logs_handler
    async with self.sys_host.logs.journald_logs(
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/host/logs.py", line 143, in journald_logs
    raise HostNotSupportedError(
supervisor.exceptions.HostNotSupportedError: No systemd-journal-gatewayd Unix socket available
2024-05-03 13:55:54.206 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-05-03 13:55:54.206 ERROR (MainThread) [supervisor.api] Failed to get supervisor logs using advanced_logs API
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 404, in get_supervisor_logs
    return await self._api_host.advanced_logs_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 207, in advanced_logs_handler
    async with self.sys_host.logs.journald_logs(
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/host/logs.py", line 143, in journald_logs
    raise HostNotSupportedError(
supervisor.exceptions.HostNotSupportedError: No systemd-journal-gatewayd Unix socket available
```

### System Health information

Non ci sono riparazioni disponibili al momento

**Comment by golddragon007** [comment]
https://www.home-assistant.io/more-info/unsupported/systemd_journal

I had same, but after an update, it was resolved.

**Comment by Destroyer061090** [comment]
I'm not able to run apt-get command because i'm running it on docker. The command sudo or apt-get is not found :-(

**Comment by golddragon007** [comment]
It needs to be available on the operating system (Rasbian) also I just realised later that I did not fix it, I have to update the system to Bookworm (Debian 12?) because of the dependency bumps that they introduced.

**Comment by Destroyer061090** [comment]
I gues mine it's Alpine based... i don't know how to confirm it...

**Comment by agners** [comment]
@Destroyer061090 systemd-journal-gatewayd is meant to run on the host system, not inside the Supervisor container.

Check and make sure you have installed the latest requirements of the Supervisor: https://github.com/home-assistant/supervised-installer?tab=readme-ov-file#installation

Also make sure that you have the latest version of the Supervisor installer deb package installed. The updated Supervisor scripts take care of forwarding the necessary Unix socket into the container (specifically, [this line in the Supervisor start script](https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/usr/sbin/hassio-supervisor#L93)).

**Comment by lmagyar** [comment]
Same error, I've tried HA add-on + devcontainer the first time on Windows 11, WSL2, Ubuntu 24.04, Docker Desktop 4.30.0

I've followed the instructions [here](https://developers.home-assistant.io/docs/add-ons/testing/)

I've developed add-ons for years on real HW, this is the first time I'm trying this on devcontainer. Total newbie in devcontainer.

Unsupported system:
- Operating System
- Network Manager issues
- Content-trust check disabled
- Systemd-Resolved issues
- Systemd Journal issues
- AppArmor issues
- Docker misconfigured
- Systemd issues

## System Information

version | core-2024.6.0.dev202405070218
-- | --
installation_type | Home Assistant Supervised
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.15.146.1-microsoft-standard-WSL2
arch | x86_64
timezone | Europe/Budapest
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | null
-- | --
update_channel | dev
supervisor_version | supervisor-2024.05.1.dev0705
agent_version | 1.5.1
docker_version | 26.1.0
disk_total | 1006.9 GB
disk_used | 5.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | [BETA] In-memory MariaDB (2.7.1.1-rc07)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 7, 2024 at 6:00 PM
-- | --
current_recorder_run | May 7, 2024 at 8:00 PM
estimated_db_size | 0.19 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by mmb25** [comment]
Did anyone got this fixed? I am considering reinstalling my supervisor, but would like to avoid it.

**Comment by cociweb** [comment]
I bet this commit has the side effect: https://github.com/home-assistant/supervisor/commit/a894c4589eed3c3ac03370d9d74284c1a6f4086b

all the addons and hassio_containers lost their printouts in HA. (Fortunatelly docker logs XXX still visible but it is annoying....)

**Comment by alexandrezia** [comment]
I run homeassistant supervisor (and let it controls all other homeassistant containers, addons, etc) in a synology.
it does not have systemd-journal-gatewayd and there's no way to install it (if you want to keep it stock)
now the only way to see the logs is through  terminal `docker logs ...`
it's not the end of the world, but it's annoying indeed, the way it was before was working, so can't just be a config toggle to enable it back?

**Comment by DavidFFerreira** [comment]
im wth that probleme....and zigbee2mqtt dont star cause of that

**Comment by 2lifehd** [comment]
> im wth that probleme....and zigbee2mqtt dont star cause of that

A similar problem. Zigbee2mqtt stopped working

**Comment by perseus177** [comment]
Any update please ? Please fix it....

**Comment by agners** [comment]
For those folks who use Supservised installation, make sure you have all the per-requisits installed. Those also got updated over time, specifically make sure `systemd-journal-remote` is installed and started.

See: https://github.com/home-assistant/supervised-installer?tab=readme-ov-file#installation

Note that Supervisor requires either HAOS or Debian 12 (as stated in [ADR0014](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md)).

So running the Supervised directly on a DSM installation likely doesn't give access to systemd-journald via `systemd-journal-remote` hence this error appears. But this won't be addressed as this is not a supported operating environment for the Supervisor. Consider using HAOS in a virtual machine or a pure container installation.

As for the development environment, this is considered an unsupported installation by default. We can't simulate a full Supervised environment in a container. So this is how things behave currently.

**Comment by bokub** [comment]
> As for the development environment, this is considered an unsupported installation by default. We can't simulate a full Supervised environment in a container. So this is how things behave currently.

As an Add-on developer, how am I supposed to test my add-on if I can't even access the logs?

**Comment by cmgrayb** [comment]
> As for the development environment, this is considered an unsupported installation by default. We can't simulate a full Supervised environment in a container. So this is how things behave currently.

@agners can you please elaborate on why this will not be fixed?  This is home assistant's dev container, which is recommended [by the documentation](https://developers.home-assistant.io/docs/add-ons/testing/) for performing local testing of add-ons, which is unable to read add-on logs, because of a change made to the supervisor without considering the overall landscape and you're telling your developers that not only is the recommendation not supported, but that it's not ever going to work again?  Why is this still the recommended local testing method then?  It sounds to me like containerized local testing just got deprecated without being documented as such or announced.

**Comment by alexandrezia** [comment]
My point is, 
I have a Synology NAS which in my opinion is way more reliable to run HA than any raspberryPI or other similar solution that relies on a single SDCard as storage.
I want to run it containerized because is more efficient, les resource consuming than virtual machine option I have in Synology, because I already run several other containers for different things.
I know how to keep HA in synology docker on supervisor mode along with my other containers, and it's running flawless even if keeps raising issues regarding my host OS is not an "homologated one".
Every time a modification in HA is made in the opposite direction makes me sad, it feels like one day it will not run in my setup anymore.
This for exemple, you could simply put a config attribute to read the addon logs the old way and not have all this impact

**Comment by cociweb** [comment]
Yep, agreed. Supervised is going on a wrong way....

**Comment by michalk-k** [comment]
Guys, I have the same with core installation. So it's not supervised related issue.

**Comment by Leezy03** [comment]
> I'm not able to run apt-get command because i'm running it on docker. The command sudo or apt-get is not found :-(

Hi, did you fixed this problem?
