### ISSUE TITLE
Reolink integration. update

### ISSUE THREAD

**Issue by cvandingelen** [home-assistant/supervisor#5195]
### Describe the issue you are experiencing

Home assistant tells me there's an update available for the reolink cameras, but when I do the update I get an error.

![image](https://github.com/user-attachments/assets/4efbd47a-f984-4fbc-80ab-0de1f6b9227e)
Screenshot above shows there is an update. Screenshot below the error.
![image](https://github.com/user-attachments/assets/7c51ac14-3ed4-4b9d-840a-10962a94cba9)

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Go to settings 
2. Update 
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:53:21 (8 occurrences)
Last logged: 22:00:21

[281472257418736] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/google_assistant_sdk/init.py", line 125, in send_text_command
command_response_list = await async_send_text_commands(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/google_assistant_sdk/helpers.py", line 82, in async_send_text_commands
resp = await hass.async_add_executor_job(assistant.assist, command)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/gassist_text/textinput.py", line 125, in assist
for resp in self.assistant.Assist(iter_assist_requests(), self.deadline):
File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 541, in next
return self._next()
^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 967, in _next
raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
status = StatusCode.RESOURCE_EXHAUSTED
details = "Quota exceeded for quota metric 'embedded-assistant-prod/converse_requests' and limit 'ConverseRequestsPerDayPerProject' of service 'embeddedassistant.googleapis.com' for consumer 'project_number:1025529926150'."
debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.17.10:443 {grpc_message:"Quota exceeded for quota metric 'embedded-assistant-prod/converse_requests' and limit 'ConverseRequestsPerDayPerProject' of service 'embeddedassistant.googleapis.com' for consumer 'project_number:1025529926150'.", grpc_status:8, created_time:"2024-07-20T21:53:21.550374631+02:00"}"

`
```

### System Health information

There are currently no repairs available

**Comment by cvandingelen** [comment]
Still the same problem

**Comment by agners** [comment]
Firmware update for Reolink is not implemented in Supervisor but in Home Assistant Core. So you have to report it at https://github.com/home-assistant/core.
