### ISSUE TITLE
HA crashing with error message

### ISSUE THREAD

**Issue by Aaroneisele55** [home-assistant/supervisor#5251]
### Describe the issue you are experiencing

My HA instance is constantly restarting for no obvious reason, there is always the same error in the logs....

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

I don't know yet

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-08-15 11:18:59.196 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1478284' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
```

## System Information

version | core-2024.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | pending
GitHub Web | pending
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1389
Downloaded Repositories | 50

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | pending
can_reach_cloud_auth | pending
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 916.2 GB
disk_used | 70.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | pending
installed_addons | Advanced SSH & Web Terminal (18.0.0), File editor (5.8.0), Mosquitto broker (6.4.1), ESPHome (2024.7.3), Node-RED (18.0.5), Matter Server (6.4.1), MQTT Explorer (browser-1.0.3), Studio Code Server (5.15.0), Tailscale with features (0.20.0.3), Samba share (12.3.2), Piper (1.5.2), Whisper (2.1.2), Home Assistant Google Drive Backup (0.112.1), USBIP Mounter (1.1.0), Warema Bridge (dev), Matterbridge (2.6.2-117), WeeWX (0.111)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 25
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6. August 2024 um 18:06
-- | --
current_recorder_run | 14. August 2024 um 15:27
estimated_db_size | 1230.10 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Supervisor diagnostics

[config_entry-hassio-ea955f2b3a95c8928dfb15177bff44af.json](https://github.com/user-attachments/files/16623925/config_entry-hassio-ea955f2b3a95c8928dfb15177bff44af.json)

**Comment by mdegat01** [comment]
Sorry what exactly is crashing? The log you shared just shows that Supervisor is repeatedly trying to bring an addon back online and failing to do so. Which means some addon you have definitely has an issue though its not clear which one from the log.

Is that what is crashing, an addon? Or is something else crashing as well?

**Comment by Aaroneisele55** [comment]
> Sorry what exactly is crashing? The log you shared just shows that Supervisor is repeatedly trying to bring an addon back online and failing to do so. Which means some addon you have definitely has an issue though its not clear which one from the log.
> 
> Is that what is crashing, an addon? Or is something else crashing as well?

My Hone Assistant is becoming unavailable (no network access, no automations running, etc.) at seemingly random times, then comes back online after ~5 minutes...
How could I diagnose such an issue because I can only access the logs in the UI back to the last restart...

**Comment by agners** [comment]
> How could I diagnose such an issue because I can only access the logs in the UI back to the last restart...

You can use the console to access logs older than that, e.g. to get the logs of Supervisor from a previous boot.
```
ha supervisor logs --boot -1 
```

It could be that the Supervisor deems the Core as non-responsive and restarts it. Can you share the full Supervisor logs?

Also can you try starting HA in safe mode? Settings -> System -> Top right power icon -> Advanced Options -> Restart Home Assistant in safe mode. This is mostly to check if a custom component causes issues.

**Comment by Aaroneisele55** [comment]
> > How could I diagnose such an issue because I can only access the logs in the UI back to the last restart...
> 
> You can use the console to access logs older than that, e.g. to get the logs of Supervisor from a previous boot.
> ```
> ha supervisor logs --boot -1 
> ```
> 
> It could be that the Supervisor deems the Core as non-responsive and restarts it. Can you share the full Supervisor logs?
> 
> Also can you try starting HA in safe mode? Settings -> System -> Top right power icon -> Advanced Options -> Restart Home Assistant in safe mode. This is mostly to check if a custom component causes issues.
> 

I ran the command and here are my logs:

```
~ # ha supervisor logs --boot -1
2024-08-17 10:48:41.615 INFO (MainThread) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-mosquitto with tag 6.4.1.
2024-08-17 10:48:43.079 INFO (MainThread) [supervisor.addons.manager] Add-on 'core_mosquitto' successfully installed
2024-08-17 10:48:50.117 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_core_mosquitto application
2024-08-17 10:48:52.105 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.4.1
2024-08-17 10:48:58.870 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'aaron'
2024-08-17 10:48:59.212 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'addons'
2024-08-17 10:48:59.367 INFO (MainThread) [supervisor.discovery] Sending discovery to Home Assistant mqtt from core_mosquitto
2024-08-17 10:48:59.447 INFO (MainThread) [supervisor.discovery] Discovery bb0ff69b267241e6b70fdef7a553a4ed message send
2024-08-17 10:48:59.623 INFO (MainThread) [supervisor.auth] Successful login for 'aaron'
2024-08-17 10:48:59.651 WARNING (MainThread) [supervisor.auth] Unauthorized login for 'addons'
2024-08-17 10:49:00.327 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
2024-08-17 10:49:27.746 INFO (SyncWorker_6) [supervisor.docker.manager] Stopping addon_core_mosquitto application
2024-08-17 10:49:32.039 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_core_mosquitto application
2024-08-17 10:49:32.067 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
2024-08-17 10:49:32.083 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_core_mosquitto application
2024-08-17 10:49:32.272 ERROR (SyncWorker_7) [supervisor.docker.manager] Can't create container from addon_core_mosquitto: 409 Client Error for http+docker://localhost/v1.45/containers/create?name=addon_core_mosquitto: Conflict ("Conflict. The container name "/addon_core_mosquitto" is already in use by container "b210f179dd01e0434772afff4e87d8a2aed5a29e6f4db31d13fbd24e4e147cd2". You have to remove (or rename) that container to be able to reuse that name.")
2024-08-17 10:49:33.406 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.4.1
2024-08-17 10:49:35.651 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /addons/self/options/config
2024-08-17 10:49:39.568 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /auth
2024-08-17 10:49:40.997 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /auth
2024-08-17 10:49:40.482 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /discovery
2024-08-17 10:49:40.957 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /services/mqtt
2024-08-17 10:49:46.417 WARNING (MainThread) [supervisor.addons.addon] core_mosquitto is already running!
2024-08-17 10:50:41.807 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_a0d7b954_emqx application
2024-08-17 10:50:42.043 INFO (SyncWorker_5) [supervisor.docker.manager] Removing image ghcr.io/hassio-addons/emqx/aarch64 with latest
2024-08-17 10:50:42.155 INFO (SyncWorker_5) [supervisor.docker.manager] Removing image ghcr.io/hassio-addons/emqx/aarch64 with 0.6.2
2024-08-17 10:50:43.867 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/a0d7b954_emqx
2024-08-17 10:50:44.066 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for a0d7b954_emqx
2024-08-17 10:50:44.222 INFO (MainThread) [supervisor.addons.manager] Add-on 'a0d7b954_emqx' successfully removed
2024-08-17 10:51:02.045 INFO (MainThread) [supervisor.host.control] Initialize host reboot using logind
2024-08-17 10:51:02.055 INFO (MainThread) [supervisor.addons.manager] Phase 'application' stopping 7 add-ons
2024-08-17 10:51:02.084 INFO (SyncWorker_7) [supervisor.docker.manager] Stopping addon_core_configurator application
2024-08-17 10:51:07.274 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_core_configurator application
2024-08-17 10:51:07.669 INFO (SyncWorker_6) [supervisor.docker.manager] Stopping addon_a0d7b954_nodered application
2024-08-17 10:51:09.654 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_nodered closed
2024-08-17 10:51:16.661 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_a0d7b954_nodered application
2024-08-17 10:51:16.991 INFO (SyncWorker_7) [supervisor.docker.manager] Stopping addon_9cf1ea8f_mqtt_explorer application
2024-08-17 10:51:17.647 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_9cf1ea8f_mqtt_explorer application
2024-08-17 10:51:17.725 INFO (SyncWorker_5) [supervisor.docker.manager] Stopping addon_core_piper application
2024-08-17 10:51:22.143 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_core_piper application
2024-08-17 10:51:22.389 INFO (SyncWorker_3) [supervisor.docker.manager] Stopping addon_core_whisper application
2024-08-17 10:51:26.375 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning addon_core_whisper application
2024-08-17 10:51:26.523 INFO (SyncWorker_6) [supervisor.docker.manager] Stopping addon_cebe7a76_hassio_google_drive_backup application
2024-08-17 10:51:30.183 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_cebe7a76_hassio_google_drive_backup application
2024-08-17 10:51:30.313 INFO (SyncWorker_7) [supervisor.docker.manager] Stopping addon_a1b84aa7_matterbridge application
2024-08-17 10:51:31.491 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 257
2024-08-17 10:51:31.494 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a1b84aa7_matterbridge closed
2024-08-17 10:51:33.753 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_a1b84aa7_matterbridge application
2024-08-17 10:51:33.841 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping homeassistant application
2024-08-17 10:52:54.311 INFO (MainThread) [supervisor.addons.manager] Phase 'services' stopping 7 add-ons
2024-08-17 10:52:54.399 INFO (SyncWorker_2) [supervisor.docker.manager] Stopping addon_a0d7b954_ssh application
2024-08-17 10:52:58.449 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_a0d7b954_ssh application
2024-08-17 10:52:58.609 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping addon_5c53de3b_esphome application
2024-08-17 10:53:03.862 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_5c53de3b_esphome application
2024-08-17 10:53:03.981 INFO (SyncWorker_0) [supervisor.docker.manager] Stopping addon_core_matter_server application
2024-08-17 10:53:14.378 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-08-17 10:53:14.507 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping addon_a0d7b954_vscode application
2024-08-17 10:53:21.269 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_a0d7b954_vscode application
2024-08-17 10:53:21.452 INFO (SyncWorker_2) [supervisor.docker.manager] Stopping addon_09716aab_tailscale application
2024-08-17 10:53:26.527 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_09716aab_tailscale application
2024-08-17 10:53:26.643 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping addon_core_samba application
2024-08-17 10:53:30.573 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_core_samba application
2024-08-17 10:53:30.712 INFO (SyncWorker_0) [supervisor.docker.manager] Stopping addon_d0531868_warema-bridge application
2024-08-17 10:53:31.760 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning addon_d0531868_warema-bridge application
2024-08-17 10:53:31.822 INFO (MainThread) [supervisor.addons.manager] Phase 'system' stopping 1 add-ons
2024-08-17 10:53:31.842 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping addon_core_mosquitto application
2024-08-17 10:53:36.482 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_core_mosquitto application
2024-08-17 10:53:36.504 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
2024-08-17 10:53:36.513 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_core_mosquitto application
2024-08-17 10:53:36.849 INFO (MainThread) [supervisor.addons.manager] Phase 'initialize' stopping 0 add-ons
2024-08-17 10:53:36.855 INFO (MainThread) [supervisor.plugins.cli] Stopping cli plugin
2024-08-17 10:53:36.884 INFO (SyncWorker_5) [supervisor.docker.manager] Stopping hassio_cli application
2024-08-17 10:53:38.188 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.4.1
2024-08-17 10:53:40.624 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning hassio_cli application
2024-08-17 10:53:40.696 INFO (MainThread) [supervisor.plugins.dns] Stopping CoreDNS plugin
2024-08-17 10:53:40.718 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping hassio_dns application
2024-08-17 10:53:44.787 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning hassio_dns application
2024-08-17 10:53:44.864 INFO (MainThread) [supervisor.plugins.audio] Stopping Audio plugin
2024-08-17 10:53:44.882 INFO (SyncWorker_2) [supervisor.docker.manager] Stopping hassio_audio application
2024-08-17 10:53:49.281 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning hassio_audio application
2024-08-17 10:53:49.364 INFO (MainThread) [supervisor.plugins.multicast] Stopping Multicast plugin
2024-08-17 10:53:49.380 INFO (SyncWorker_3) [supervisor.docker.manager] Stopping hassio_multicast application
2024-08-17 10:53:53.045 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning hassio_multicast application
s6-rc: info: service legacy-services: stopping
2024-08-17 10:53:53.560 INFO (MainThread) [supervisor.misc.scheduler] Shutting down scheduled tasks
2024-08-17 10:53:53.572 INFO (MainThread) [supervisor.docker.monitor] Stopped docker events monitor
2024-08-17 10:53:53.577 INFO (MainThread) [supervisor.api] Stopping API on 172.30.32.2
2024-08-17 10:53:53.597 INFO (MainThread) [supervisor.hardware.monitor] Stopped Supervisor hardware monitor
[08:53:53] INFO: Watchdog restart after closing
2024-08-17 10:53:53.705 INFO (MainThread) [supervisor.dbus.manager] Closed conection to system D-Bus.
2024-08-17 10:53:53.724 INFO (MainThread) [supervisor.core] Supervisor is down - 0
2024-08-17 10:53:53.735 INFO (MainThread) [__main__] Closing Supervisor
[08:53:57] WARNING: Halt Supervisor
[08:53:57] INFO: Supervisor restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
