### ISSUE TITLE
Can't restore influxdb partial backup due to "Not a gzipped file (b'\xa7d')" error

### ISSUE THREAD

**Issue by maurolemos** [home-assistant/supervisor#5266]
### Describe the issue you are experiencing

I'm trying to restore an influxdb backup which is around 2GB and the partial restore is crashing with

```
"Not a gzipped file (b'\xa7d')" error
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. perform partial backup for influxdb
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-08-22 10:35:44.726 INFO (MainThread) [supervisor.store] Loading add-ons from store: 86 all - 0 new - 0 remove
2024-08-22 10:35:44.727 INFO (MainThread) [supervisor.backups.manager] Restore ba4cea30 starting stage addons
2024-08-22 10:40:39.844 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Not a gzipped file (b'\xa7d')
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 303, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1244, in restore
    await self.sys_run_in_executor(_extract_tarfile)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1237, in _extract_tarfile
    backup.extractall(
  File "/usr/local/lib/python3.12/tarfile.py", line 2269, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/local/lib/python3.12/tarfile.py", line 2336, in _extract_one
    self._handle_fatal_error(e)
  File "/usr/local/lib/python3.12/tarfile.py", line 2332, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/local/lib/python3.12/tarfile.py", line 2415, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/lib/python3.12/tarfile.py", line 2469, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/local/lib/python3.12/tarfile.py", line 257, in copyfileobj
    buf = src.read(remainder)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/gzip.py", line 324, in read
    return self._buffer.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^^
gzip.BadGzipFile: Not a gzipped file (b'\xa7d')
```

## System Information

version | core-2024.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | armv7l
timezone | Europe/Lisbon
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4794
Installed Version | 1.34.0
Stage | running
Available Repositories | 1384
Downloaded Repositories | 14

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 109.3 GB
disk_used | 8.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Grafana (10.0.0), Advanced SSH & Web Terminal (18.0.0), Home Assistant Google Drive Backup (0.112.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 5
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 18 August 2024 at 04:15
-- | --
current_recorder_run | 22 August 2024 at 10:31
estimated_db_size | 293.35 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 5 / 5
local_online | 0 / 0

</details>

### Supervisor diagnostics

[config_entry-hassio-9b8b7cf0599c15b59ded9d28492b0fee.json](https://github.com/user-attachments/files/16708774/config_entry-hassio-9b8b7cf0599c15b59ded9d28492b0fee.json)

### Additional information

Backup was performed with 

```
  "supervisor_version": "2024.08.0",
```

And now I'm trying to restore with the same version so not sure what the problem is

**Comment by maurolemos** [comment]
Ran a little script to extract the influxdb tar.gz file that is contained in the backup

```
    with tarfile.open(file_path, 'r:gz') as tar:
        tar.extractall(path=extract_path)
```

And the file is correctly extracted in the rpi3 using hass cli
