### ISSUE TITLE
Cannot update CORE or Supervisor RPi 3b+

### ISSUE THREAD

**Issue by juancameijeiras** [home-assistant/supervisor#5355]
### Describe the issue you are experiencing

I am running HAOS on a RPi 3b+, it has successfully updated to Core 2024.10.1, Supervisor 2024.10.0, Operating System 13.1, 
 Frontend 20241002.2 but cannot update further, I have tried rebooting the whole device without success. Upon checking the logs, it gives me this info (full logs attached):

2024-10-15 17:54:37.427 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2")
2024-10-15 17:54:37.441 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2")
[supervisor_2024-10-15T16-03-43.769Z.log](https://github.com/user-attachments/files/17381445/supervisor_2024-10-15T16-03-43.769Z.log)

The device has enough space available, CPU is not running hot or high, power is ok 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Tried installing by calling the service
2. Restarted HA
3. Rebooted device
...

### Anything in the Supervisor logs that might be useful for us?

```txt
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docker/api/image.py", line 251, in inspect_image
    return self._result(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/supervisor.py", line 196, in update
    await self.instance.install(
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 312, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 304, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/docker/interface.py", line 277, in install
    raise DockerError(
supervisor.exceptions.DockerError: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 312, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 304, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 149, in _update_supervisor
    await self.sys_supervisor.update()
  File "/usr/src/supervisor/supervisor/supervisor.py", line 207, in update
    raise SupervisorUpdateError(
supervisor.exceptions.SupervisorUpdateError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2")
2024-10-15 16:55:26.267 INFO (MainThread) [supervisor.misc.tasks] Found new Supervisor version 2024.10.2, updating
2024-10-15 16:55:26.267 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt
2024-10-15 16:55:26.719 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
2024-10-15 16:55:27.602 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.10.2
2024-10-15 16:55:27.604 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-supervisor with tag 2024.10.2.
2024-10-15 16:56:55.992 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-10-15 16:56:56.993 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-10-15 16:56:56.994 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-10-15 16:56:56.997 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-10-15 16:57:06.061 INFO (MainThread) [supervisor.jobs] 'CheckAddonPwned.run_check' blocked from execution, no supervisor internet connection
2024-10-15 16:57:06.062 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-10-15 16:57:06.066 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-10-15 16:57:17.053 INFO (MainThread) [supervisor.jobs] 'CheckDNSServerIPv6.run_check' blocked from execution, no supervisor internet connection
2024-10-15 16:57:17.054 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-10-15 16:57:28.054 INFO (MainThread) [supervisor.jobs] 'CheckDNSServer.run_check' blocked from execution, no supervisor internet connection
2024-10-15 16:57:28.055 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-10-15 16:57:28.056 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-10-15 16:57:28.057 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-10-15 16:57:28.058 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-10-15 16:57:28.059 ERROR (MainThread) [supervisor.resolution.check] Error during processing trust: Another job is running for job group container_hassio_supervisor
2024-10-15 16:57:28.060 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-10-15 16:57:28.060 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-10-15 16:57:29.189 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-10-15 16:57:29.191 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-10-15 16:57:29.191 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-10-15 16:59:06.142 INFO (MainThread) [supervisor.jobs] 'Tasks._reload_store' blocked from execution, supervisor needs to be updated first
2024-10-15 16:59:07.229 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-10-15 16:59:17.429 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-10-15 16:59:19.830 INFO (MainThread) [supervisor.host.services] Updating service information
2024-10-15 16:59:19.864 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-10-15 16:59:20.789 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-10-15 16:59:20.978 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-10-15 16:59:42.677 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2")
2024-10-15 16:59:42.678 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2")
2024-10-15 17:29:07.846 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-10-15 17:50:45.092 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt
2024-10-15 17:50:45.897 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
2024-10-15 17:50:46.763 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2024.10.2
2024-10-15 17:50:46.764 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-supervisor with tag 2024.10.2.
2024-10-15 17:54:37.427 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2")
2024-10-15 17:54:37.441 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.10.2")
2024-10-15 17:57:29.216 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-10-15 17:57:29.217 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-10-15 17:57:29.217 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-10-15 17:57:29.220 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-10-15 17:57:30.347 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-10-15 17:57:30.351 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-10-15 17:57:30.353 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-10-15 17:57:30.355 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-10-15 17:57:30.356 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-10-15 17:57:30.357 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-10-15 17:57:30.357 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-10-15 17:57:30.625 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-10-15 17:57:30.626 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-10-15 17:57:31.892 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-10-15 17:57:31.893 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-10-15 17:57:31.894 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-10-15 17:58:20.555 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-10-15 17:59:08.539 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

### System Health information

<h2 id="title" class="mdc-dialog__title" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-headline6-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-headline6-font-size, 1.25rem); line-height: var(--mdc-typography-headline6-line-height, 2rem); font-weight: var(--mdc-typography-headline6-font-weight,500); letter-spacing: var(--mdc-typography-headline6-letter-spacing, .0125em); text-decoration: var(--mdc-typography-headline6-text-decoration,inherit); text-transform: var(--mdc-typography-headline6-text-transform,inherit); display: block; position: relative; flex-shrink: 0; box-sizing: border-box; margin: 0px 0px 1px; padding: 24px 24px 0px; color: var(--mdc-dialog-heading-ink-color,rgba(0,0,0,.87));"><div class="header_title" style="position: relative; padding-right: 40px; padding-inline-end: 40px; padding-inline-start: initial; direction: var(--direction);"><span style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; display: block;">System information</span><ha-icon-button dialogaction="close" class="header_button" style="display: inline-block; outline: 0px; position: absolute; right: -12px; top: -12px; text-decoration: none; color: inherit; inset-inline-start: initial; inset-inline-end: -12px; direction: var(--direction);"><mwc-icon-button title="Close" style="display: inline-block; outline: 0px; --mdc-ripple-color: currentcolor; -webkit-tap-highlight-color: transparent; vertical-align: top; --mdc-theme-on-primary: currentColor; --mdc-theme-text-disabled-on-light: var(--disabled-text-color);"><button class="mdc-icon-button mdc-icon-button--display-flex" aria-label="Close" style="font-size: 24px; width: var(--mdc-icon-button-size,48px); height: var(--mdc-icon-button-size,48px); padding: calc((var(--mdc-icon-button-size,48px) - var(--mdc-icon-size,24px))/ 2); display: inline-flex; position: relative; box-sizing: border-box; border: none; outline: 0px; background-color: transparent; fill: currentcolor; color: inherit; text-decoration: none; cursor: pointer; user-select: none; z-index: 0; overflow: visible; align-items: center; justify-content: center; vertical-align: top;"><span><slot><ha-svg-icon style="display: block; align-items: center; justify-content: center; position: relative; vertical-align: middle; fill: var(--icon-primary-color,currentcolor); width: var(--mdc-icon-size,24px); height: var(--mdc-icon-size,24px);"><svg preserveAspectRatio="xMidYMid meet" focusable="false" role="img" aria-hidden="true" viewBox="0 0 24 24"><g><path class="primary-path" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></g></svg></ha-svg-icon></slot></span></button></mwc-icon-button></ha-icon-button></div></h2><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: 14px; line-height: var(--mdc-typography-body1-line-height, 1.5rem); font-weight: 400; letter-spacing: var(--mdc-typography-body1-letter-spacing, .03125em); text-decoration-line: ; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-transform: none; flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: rgb(33, 33, 33); padding: var(--dialog-content-padding,24px); position: var(--dialog-content-position,relative); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;"><slot id="contentSlot" style="margin-top: 0px; margin-bottom: 0px;"><div><div>
Version | core-2024.10.1
-- | --
Installation type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual environment | false
Python version | 3.12.4
Operating system family | Linux
Operating system version | 6.6.31-haos-raspi
CPU architecture | aarch64
Timezone | Europe/Stockholm
Configuration directory | /config

</div><div><h3>Core metrics</h3><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 537px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding-top: 8px; padding-bottom: 8px; padding-left: 0px; padding-inline: 0px 16px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading"><span slot="heading">Processor usage</span></slot><div class="secondary" style="white-space: normal; display: block; padding-top: 4px; font-family: var(
          --mdc-typography-body2-font-family,
          var(--mdc-typography-font-family, Roboto, sans-serif)
        ); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size, .875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; padding-inline-end: 4px; padding-inline-start: initial; flex-shrink: 0;"><div style="direction: ltr; text-align: var(--float-start);">1.7<span> </span>%</div></span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="1.7%"></rect></g></svg></ha-bar></div></slot></div></div></div><div class="content" style="display: var(--settings-row-content-display,flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 537px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding-top: 8px; padding-bottom: 8px; padding-left: 0px; padding-inline: 0px 16px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading"><span slot="heading">Memory usage</span></slot><div class="secondary" style="white-space: normal; display: block; padding-top: 4px; font-family: var(
          --mdc-typography-body2-font-family,
          var(--mdc-typography-font-family, Roboto, sans-serif)
        ); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size, .875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; padding-inline-end: 4px; padding-inline-start: initial; flex-shrink: 0;"><div style="direction: ltr; text-align: var(--float-start);">33.6<span> </span>%</div></span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="33.6%"></rect></g></svg></ha-bar></div></slot></div></div></div><div class="content" style="display: var(--settings-row-content-display,flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><h3>Supervisor metrics</h3><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 537px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding-top: 8px; padding-bottom: 8px; padding-left: 0px; padding-inline: 0px 16px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading"><span slot="heading">Processor usage</span></slot><div class="secondary" style="white-space: normal; display: block; padding-top: 4px; font-family: var(
          --mdc-typography-body2-font-family,
          var(--mdc-typography-font-family, Roboto, sans-serif)
        ); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size, .875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; padding-inline-end: 4px; padding-inline-start: initial; flex-shrink: 0;"><div style="direction: ltr; text-align: var(--float-start);">0<span> </span>%</div></span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="0%"></rect></g></svg></ha-bar></div></slot></div></div></div><div class="content" style="display: var(--settings-row-content-display,flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 537px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding-top: 8px; padding-bottom: 8px; padding-left: 0px; padding-inline: 0px 16px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading"><span slot="heading">Memory usage</span></slot><div class="secondary" style="white-space: normal; display: block; padding-top: 4px; font-family: var(
          --mdc-typography-body2-font-family,
          var(--mdc-typography-font-family, Roboto, sans-serif)
        ); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size, .875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; padding-inline-end: 4px; padding-inline-start: initial; flex-shrink: 0;"><div style="direction: ltr; text-align: var(--float-start);">8.9<span> </span>%</div></span></div></slot></div></div></div></ha-settings-row></ha-metric></div></div></slot></div>

### Supervisor diagnostics

[config_entry-hassio-01J8YNS9KPRRNRZWNH189GDHBT.json](https://github.com/user-attachments/files/17381493/config_entry-hassio-01J8YNS9KPRRNRZWNH189GDHBT.json)

**Comment by juancameijeiras** [comment]
The rpi was on wifi, I switched it to LAN and could do all updates without issue
