### ISSUE TITLE
 [homeassistant.components.matter] Failed to get the Matter Server add-on info

### ISSUE THREAD

**Issue by isaacyew** [home-assistant/supervisor#5368]
### Describe the issue you are experiencing

Unable to add Matter (beta) add-on. It returns with error `Failed to get Matter Server add-on info.`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. goto Settings
2. goto Devices and services
3. Add integration
4. Find and select Matter (BETA)
5. Tick "Use the official Matter Server Supervisor add-on"
6. Click "Submit, then it returns with error: `Failed to get Matter Server add-on info.`

### Anything in the Supervisor logs that might be useful for us?

```txt
[32m2024-10-23 15:21:31.049 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system[0m
[32m2024-10-23 15:21:31.049 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon[0m
[32m2024-10-23 15:21:31.049 INFO (MainThread) [supervisor.jobs] 'CheckAddonPwned.run_check' blocked from execution, no supervisor internet connection[0m
[32m2024-10-23 15:21:31.049 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system[0m
[32m2024-10-23 15:21:31.050 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system[0m
[32m2024-10-23 15:21:31.050 INFO (MainThread) [supervisor.resolution.module] Create new suggestion create_full_backup - system / None[0m
[32m2024-10-23 15:21:31.050 INFO (MainThread) [supervisor.resolution.module] Create new issue no_current_backup - system / None[0m
[32m2024-10-23 15:21:31.050 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system[0m
[32m2024-10-23 15:21:31.050 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server[0m
[32m2024-10-23 15:21:31.050 INFO (MainThread) [supervisor.jobs] 'CheckDNSServerIPv6.run_check' blocked from execution, no supervisor internet connection[0m
[32m2024-10-23 15:21:31.050 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor[0m
[32m2024-10-23 15:21:31.053 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system[0m
[32m2024-10-23 15:21:31.053 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core[0m
[32m2024-10-23 15:21:31.053 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server[0m
[32m2024-10-23 15:21:31.053 INFO (MainThread) [supervisor.jobs] 'CheckDNSServer.run_check' blocked from execution, no supervisor internet connection[0m
[32m2024-10-23 15:21:31.053 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m2024-10-23 15:21:31.053 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m2024-10-23 15:21:31.060 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m2024-10-23 15:21:31.064 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m2024-10-23 15:21:31.127 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m2024-10-23 15:21:31.131 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m
[32m2024-10-23 15:21:31.147 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m2024-10-23 15:21:31.147 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running[0m
[33m2024-10-23 15:21:31.147 WARNING (MainThread) [supervisor.jobs] 'FixupStoreExecuteReload.process_fixup' blocked from execution, no supervisor internet connection[0m
[32m2024-10-23 15:21:31.147 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m2024-10-23 15:22:10.536 INFO (MainThread) [supervisor.plugins.dns] Restarting CoreDNS plugin[0m
[32m2024-10-23 15:22:10.538 INFO (SyncWorker_0) [supervisor.docker.manager] Restarting hassio_dns[0m
[33m2024-10-23 15:22:11.943 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection[0m
[33m2024-10-23 15:22:11.944 WARNING (MainThread) [supervisor.homeassistant.core] Error on Home Assistant installation. Retrying in 30sec[0m
[32m2024-10-23 15:22:43.044 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m2024-10-23 15:22:43.246 INFO (MainThread) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/generic-x86-64-homeassistant:landingpage to ghcr.io/home-assistant/generic-x86-64-homeassistant:2024.10.3[0m
[32m2024-10-23 15:22:43.246 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/generic-x86-64-homeassistant with tag 2024.10.3.[0m
[32m2024-10-23 15:23:22.635 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning homeassistant application[0m
[32m2024-10-23 15:23:22.641 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant docker now installed[0m
[32m2024-10-23 15:23:22.645 INFO (MainThread) [supervisor.homeassistant.core] Starting Home Assistant[0m
[32m2024-10-23 15:23:22.650 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse[0m
[32m2024-10-23 15:23:23.414 INFO (MainThread) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/generic-x86-64-homeassistant with version 2024.10.3[0m
[32m2024-10-23 15:23:23.414 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready[0m
[32m2024-10-23 15:23:26.121 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m2024-10-23 15:23:26.148 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m2024-10-23 15:23:28.424 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m2024-10-23 15:23:28.425 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='RUNNING', offline_db_migration=False)[0m
[32m2024-10-23 15:23:28.425 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance[0m
[32m2024-10-23 15:23:28.440 INFO (SyncWorker_0) [supervisor.docker.manager] Cleanup images: ['ghcr.io/home-assistant/generic-x86-64-homeassistant:landingpage'][0m
[32m2024-10-23 23:24:39.208 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m2024-10-23 23:24:39.247 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m2024-10-23 23:24:45.186 INFO (MainThread) [supervisor.utils.sentry] Initializing Supervisor Sentry[0m
[32m2024-10-23 23:24:45.209 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m2024-10-23 23:24:45.242 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m2024-10-23 23:42:55.602 INFO (MainThread) [supervisor.host.control] Set hostname HomeAssistant[0m
[31m2024-10-23 23:43:18.726 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-3344' coro=<DBus.sync_property_changes.<locals>.sync_property_change() done, defined at /usr/src/supervisor/supervisor/utils/dbus.py:233> exception=DBusInterfaceMethodError('Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/3”')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 251, in sync_property_change
    await update(changed)
  File "/usr/src/supervisor/supervisor/dbus/network/interface.py", line 160, in update
    await self.connection.connect(self.dbus.bus)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 96, in connect
    await super().connect(bus)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 50, in connect
    await self.initialize(await DBus.connect(bus, self.bus_name, self.object_path))
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 108, in initialize
    await self.update()
  File "/usr/src/supervisor/supervisor/dbus/network/connection.py", line 118, in update
    await super().update(changed)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 128, in update
    self.properties = await self.dbus.get_properties(self.properties_interface)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 221, in get_properties
    return await self.properties.call_get_all(interface)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 122, in call_dbus
    raise DBus.from_dbus_error(err) from None
supervisor.exceptions.DBusInterfaceMethodError: Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/3”[0m
[31m2024-10-23 23:43:24.746 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-3408' coro=<DBus.sync_property_changes.<locals>.sync_property_change() done, defined at /usr/src/supervisor/supervisor/utils/dbus.py:233> exception=DBusInterfaceMethodError('Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/4”')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 251, in sync_property_change
    await update(changed)
  File "/usr/src/supervisor/supervisor/dbus/network/interface.py", line 160, in update
    await self.connection.connect(self.dbus.bus)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 96, in connect
    await super().connect(bus)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 50, in connect
    await self.initialize(await DBus.connect(bus, self.bus_name, self.object_path))
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 108, in initialize
    await self.update()
  File "/usr/src/supervisor/supervisor/dbus/network/connection.py", line 118, in update
    await super().update(changed)
  File "/usr/src/supervisor/supervisor/dbus/interface.py", line 128, in update
    self.properties = await self.dbus.get_properties(self.properties_interface)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 221, in get_properties
    return await self.properties.call_get_all(interface)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 122, in call_dbus
    raise DBus.from_dbus_error(err) from None
supervisor.exceptions.DBusInterfaceMethodError: Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/4”[0m
[32m2024-10-23 23:53:32.119 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m2024-10-24 00:06:27.957 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
```

## System Information

version | core-2024.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Asia/Kuala_Lumpur
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 234.0 GB
disk_used | 5.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | false
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 23, 2024 at 3:23 PM
-- | --
current_recorder_run | October 23, 2024 at 11:23 PM
estimated_db_size | 0.23 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Supervisor diagnostics

[config_entry-hassio-01JAWZKHBKE2KKRRK2Q78AJ4WK.json](https://github.com/user-attachments/files/17495398/config_entry-hassio-01JAWZKHBKE2KKRRK2Q78AJ4WK.json)

### Additional information

2024-10-23 15:28:54.342 ERROR (MainThread) [homeassistant.components.matter] Failed to get the Matter Server add-on info: Addon core_matter_server with version latest does not exist in the store
2024-10-23 15:28:56.390 ERROR (MainThread) [homeassistant.components.matter] Failed to get the Matter Server add-on info: Addon core_matter_server with version latest does not exist in the store
2024-10-23 15:28:56.446 ERROR (MainThread) [homeassistant.components.matter] Failed to get the Matter Server add-on info: Addon core_matter_server with version latest does not exist in the store
2024-10-23 15:28:56.554 ERROR (MainThread) [homeassistant.components.matter] Failed to get the Matter Server add-on info: Addon core_matter_server with version latest does not exist in the store
2024-10-23 15:28:56.631 ERROR (MainThread) [homeassistant.components.matter] Failed to get the Matter Server add-on info: Addon core_matter_server with version latest does not exist in the store
2024-10-23 15:28:56.707 ERROR (MainThread) [homeassistant.components.matter] Failed to get the Matter Server add-on info: Addon core_matter_server with version latest does not exist in the store
2024-10-23 15:31:59.338 WARNING (SyncWorker_55) [pychromecast.controllers] PLAY command requested but no session is active.
2024-10-23 15:31:59.341 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140361055171008] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 100, in wrapper
    return_value = func(self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 558, in media_play
    media_controller.play()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/media.py", line 630, in play
    response_handler.wait_response()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/response_handler.py", line 57, in wait_response
    raise RequestFailed(self._request)
pychromecast.error.RequestFailed: Failed to execute play.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 826, in async_media_play
    await self.hass.async_add_executor_job(self.media_play)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 102, in wrapper
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: CastMediaPlayerEntity.media_play Failed: Failed to execute play.
2024-10-23 15:43:18.727 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /network/interface/wlp0s20f3/update - Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/3”
2024-10-23 15:43:24.747 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /network/interface/wlp0s20f3/update - Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/4”
2024-10-23 16:11:46.596 ERROR (MainThread) [homeassistant.components.matter] Failed to get the Matter Server add-on info: Addon core_matter_server with version latest does not exist in the store
2024-10-23 16:11:53.327 ERROR (MainThread) [homeassistant.components.matter] Failed to get the Matter Server add-on info: Addon core_matter_server with version latest does not exist in the store

**Comment by isaacyew** [comment]
a 4th time reboot fixes the issue.
