### ISSUE TITLE
List of boots (for logs) empty on a system which was up for a longer period of time

### ISSUE THREAD

**Issue by agners** [home-assistant/supervisor#5389]
### Describe the issue you are experiencing

After a system has been running for a longer period of time, and services generated many log entries, the list of boot does not return any boot id:

```
# ha host logs boots
boots: {}
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Generate lots of logs
2. Let the system run for a long(er) period of time
3. Observe no boot entries

### Anything in the Supervisor logs that might be useful for us?

```txt
When using frontend trying to fetch latest logs

2024-11-04 09:46:45.909 ERROR (MainThread) [supervisor.api] Failed to get supervisor logs using advanced_logs API
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/host.py", line 188, in _get_boot_id
    return await self.sys_host.logs.get_boot_id(offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/host/logs.py", line 87, in get_boot_id
    raise ValueError(f"Logs only contain {len(boot_ids)} boots")
ValueError: Logs only contain 0 boots
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 403, in get_supervisor_logs
    return await self._api_host.advanced_logs_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 209, in advanced_logs_handler
    params[PARAM_BOOT_ID] = await self._get_boot_id(
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 190, in _get_boot_id
    raise APIError() from err
supervisor.exceptions.APIError
```

## System Information

version | core-2024.12.0.dev202411040232
-- | --
installation_type | Home Assistant OS
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Prague
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2.dev20241007
-- | --
update_channel | dev
supervisor_version | supervisor-2024.11.0.dev0403
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 114.8 GB
disk_used | 54.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.15.0), deCONZ (7.0.0), Mosquitto broker (6.4.1), Network UPS Tools (0.13.2), EMQX (0.7.1), Silicon Labs Flasher (0.3.0), ESPHome (2024.10.0), File editor (5.8.0), motionEye (0.21.0), Dnsmasq (1.8.1), RPC Shutdown (2.5), NGINX Home Assistant SSL proxy (3.11.0), Let's Encrypt (5.2.3), Studio Code Server (5.17.2), Glances (0.21.1), MariaDB (2.7.1), RaspberryMatic CCU (3.79.6.20241031), Uptime Kuma (0.12.4), SQLite Web (4.2.2), chrony (4.0.1), Matter Server (6.6.0), Advanced SSH & Web Terminal (19.0.0), Git pull (7.14.1), OpenThread Border Router (2.11.1), Node-RED (18.1.1), CHIP Tool (0.4.0), VLC (0.3.0), TellStick (2.2.0), Remote API proxy (1.3.0), NGINX Home Assistant SSL proxy (local) (3.10.0), Matter Server (local) (6.4.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 21, 2024 at 11:05 AM
-- | --
current_recorder_run | November 4, 2024 at 9:18 AM
estimated_db_size | 48.55 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

**Comment by agners** [comment]
The reason seems to be that the log entry we use to detect the system boot is no longer present in the systemd-journald:

From https://github.com/home-assistant/supervisor/blob/2024.10.4/supervisor/host/logs.py#L36-L40, message `b07a249cd024414a82dd00cd181378ff` is used to detect the boot. Using journalctl shows that this message is indeed missing:
```
# journalctl MESSAGE_ID=b07a249cd024414a82dd00cd181378ff
-- No entries --
``` 

Probably best work around is to just fetch the last log entry and extract the boot id from there if the list of boots is empty :thinking:

**Comment by Anto79-ops** [comment]
maybe i can close my issue here, it seems to be the same?

https://github.com/home-assistant/supervisor/issues/5381
