### ISSUE TITLE
My supervisor stop working several times

### ISSUE THREAD

**Issue by bmdadu** [home-assistant/supervisor#5448]
### Describe the issue you are experiencing

Supervisor stoped working several times..I cant not reboot and I cant not acces logs unless I unplug my intel nuc system...all my add ons crash when supervisor îs down..including deconz

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?
Last
Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
There are no logs
```

### System Health information

No repairs shown

**Comment by primudo** [comment]
Same here on my side since the the 2024.11.3 desaster 😑 

After Supervisor 2024.11.4 I can now load all the addons, but unfortunately my system is not accessible ca. 2-4 times a day - only a reboot of the proxmox virtual machine helps - sometimes 2 reboots are needed. 
When comparing the history of some frozen data with the time in the logs I can see for Supervisor several errors **"Timeout on call http://172.30.32.1:8123/api/core/state"**

Here the full log in case that helps:
2024-11-24 21:34:53.309 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:34:59.300 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:34:59.300 ERROR (MainThread) [supervisor.misc.tasks] Watchdog missed 2 Home Assistant Core API responses in a row. Restarting Home Assistant Core!
2024-11-24 21:34:59.304 INFO (SyncWorker_2) [supervisor.docker.manager] Restarting homeassistant
2024-11-24 21:35:02.300 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:35:02.300 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:35:34.945 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:35:53.310 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:36:05.304 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:36:05.304 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:36:39.560 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:37:24.298 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:37:43.354 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:37:55.297 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:37:55.298 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:38:26.300 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:38:44.843 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:38:57.301 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:38:57.301 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:39:02.476 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
2024-11-24 21:39:02.476 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34955' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-11-24 21:39:02.479 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34956' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-11-24 21:39:02.479 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34957' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-11-24 21:39:02.481 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34958' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-11-24 21:39:02.482 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34959' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-11-24 21:39:02.484 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34960' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-11-24 21:39:02.485 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34961' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-11-24 21:39:02.486 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34971' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-11-24 21:39:02.488 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34972' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-11-24 21:39:02.490 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: Cannot connect to host 172.30.32.1:8123 ssl:False [Connect call failed ('172.30.32.1', 8123)]
2024-11-24 21:39:02.497 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: Cannot connect to host 172.30.32.1:8123 ssl:False [Connect call failed ('172.30.32.1', 8123)]
2024-11-24 21:39:02.498 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:39:02.634 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
2024-11-24 21:39:05.786 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-11-24 21:39:05.898 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-11-24 21:39:07.641 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-24 21:39:07.646 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='NOT_RUNNING', offline_db_migration=False)
2024-11-24 21:39:48.308 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:39:49.166 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:39:53.302 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:40:19.318 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:40:19.319 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:40:24.298 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:40:49.816 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:40:53.296 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:41:00.302 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:41:20.312 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:41:20.312 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:41:36.310 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:41:49.925 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:41:53.300 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:42:12.310 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:42:20.300 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:42:20.300 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:42:48.320 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:42:50.509 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:42:53.300 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:43:21.323 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:43:21.323 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:43:24.298 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:43:52.309 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:43:53.297 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:44:00.299 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:44:23.314 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:44:23.314 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:44:36.302 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:44:52.397 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:44:54.300 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:45:12.309 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:45:23.303 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:45:23.303 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:45:48.302 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:45:53.954 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:45:54.297 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:46:24.297 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:46:24.298 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:46:24.298 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:46:54.304 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:46:54.461 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:47:00.297 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:47:25.298 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:47:25.299 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:47:36.308 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:47:54.310 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:47:57.414 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:48:12.306 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:48:28.301 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:48:28.301 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:48:48.316 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:48:54.297 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:48:59.448 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:49:24.298 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:49:30.297 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:49:30.298 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:49:54.314 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:50:00.151 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'username'
2024-11-24 21:50:00.298 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:50:30.304 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-24 21:50:30.304 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-11-24 21:50:36.303 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
s6-rc: info: service legacy-services: stopping
2024-11-24 21:50:38.476 INFO (MainThread) [supervisor.misc.scheduler] Shutting down scheduled tasks
2024-11-24 21:50:38.477 INFO (MainThread) [supervisor.docker.monitor] Stopped docker events monitor
[20:50:38] INFO: Watchdog restart after closing
s6-svwait: fatal: timed out
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
2024-11-24 21:50:48.482 WARNING (MainThread) [supervisor.core] Stage 1: Force Shutdown!

**Comment by sysofwan** [comment]
+1 having the same issue. I only notice it when I am actively using add-ons.

**Comment by primudo** [comment]
Solved topic for me with Upgrade to 2024.12

**Comment by jackchoui** [comment]
I am on  2024.12 with rpi5 and have same issue. It is daily.

**Comment by andarotajo** [comment]
same problem here with the latest versions respectively

**Comment by FlexxFR** [comment]
This happens for me on 2025.1 as well.


```

2025-01-11 17:31:16.593 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt_user_grott'
2025-01-11 17:31:34.280 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2025-01-11 17:31:34.280 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2025-01-11 17:31:37.594 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt_user_grott'
2025-01-11 17:31:39.275 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/hassio_auth.
2025-01-11 17:31:39.275 ERROR (MainThread) [supervisor.auth] Can't request auth on Home Assistant!
2025-01-11 17:31:39.275 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-15551' coro=<Auth._backend_login() done, defined at /usr/src/supervisor/supervisor/auth.py:98> exception=AuthError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/auth.py", line 123, in _backend_login
    raise AuthError()
supervisor.exceptions.AuthError
2025-01-11 17:31:46.277 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2025-01-11 17:31:47.275 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2025-01-11 17:31:47.276 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2025-01-11 17:32:08.280 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2025-01-11 17:32:08.280 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2025-01-11 17:32:14.599 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt_user_grott'
2025-01-11 17:32:23.336 INFO (MainThread) [supervisor.auth] Successful login for 'mqtt_user_grott'
```

Sometimes it misses two in a row and restart:


```
2025-01-10 18:54:36.855 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt_user_grott'
2025-01-10 18:54:46.573 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2025-01-10 18:55:07.575 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2025-01-10 18:55:07.575 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2025-01-10 18:55:09.570 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2025-01-10 18:55:09.570 ERROR (MainThread) [supervisor.misc.tasks] Watchdog missed 2 Home Assistant Core API responses in a row. Restarting Home Assistant Core!
2025-01-10 18:55:09.576 INFO (SyncWorker_2) [supervisor.docker.manager] Restarting homeassistant
```


Meanwhile mqtt logs the following:
I'm not sure if this is the "cause of" or the "consequence from"

```
2025-01-11 17:30:41: New connection from 192.168.2.210:37495 on port 1883.
2025-01-11 17:30:41: Bad socket read/write on client automatic: Unknown error.
time="2025-01-11T17:30:46+01:00" level=error msg="POST error: Post \"http://127.0.0.1:80/authentication\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2025-01-11T17:30:46+01:00" level=error msg="Post \"http://127.0.0.1:80/authentication\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
2025-01-11 17:30:47: New connection from 192.168.2.210:42941 on port 1883.
2025-01-11 17:30:47: Bad socket read/write on client automatic: Unknown error.
2025-01-11 17:30:52: New connection from 172.30.32.2:41784 on port 1883.
time="2025-01-11T17:30:52+01:00" level=error msg="POST error: Post \"http://127.0.0.1:80/authentication\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2025-01-11T17:30:52+01:00" level=error msg="Post \"http://127.0.0.1:80/authentication\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
2025-01-11 17:30:52: Client <unknown> closed its connection.
```
