### ISSUE TITLE
Error during setup of components hassio

### ISSUE THREAD

**Issue by Witek1974** [home-assistant/supervisor#5496]
### Describe the issue you are experiencing

Home Assistant starts with error 'Error during setup of components hassio' message in notifications.
I don't see addons option in setting menu, can't update home assistant to newer version etc.
[home-assistant_2024-12-18T14-50-58.069Z.log](https://github.com/user-attachments/files/18184279/home-assistant_2024-12-18T14-50-58.069Z.log)

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

I'm not sure why it happened.
I tried today to update one of node-red packages, node-red-contrib-home-assistant-websocket to version 0.74.2.

### Anything in the Supervisor logs that might be useful for us?

```txt
Rejestrator: homeassistant.setup
Źródło: setup.py:416
Pierwsze zdarzenie: 15:38:19 (1 zdarzenia)
Ostatnio zalogowany: 15:38:19

Error during setup of component hassio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 517, in async_setup
    await update_info_task
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 462, in update_info_data
    ) = await asyncio.gather(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 61, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 369, in send_command
    return await response.json(encoding="utf-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1295, in json
    return loads(stripped.decode(encoding))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 44, in json_loads
    return orjson.loads(__obj)  # type:ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected control character in string: line 1 column 487 (char 486)
```

## System Information

version | core-2024.11.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.0-28-amd64
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1500
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12 grudnia 2024 13:07
-- | --
current_recorder_run | 18 grudnia 2024 15:38
estimated_db_size | 4340.25 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by Witek1974** [comment]
root@HA:~# ha supervisor logs
2024-12-18 15:22:18.025 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-12-18 15:23:34.383 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-12-18 15:24:53.782 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
2024-12-18 15:35:11.439 INFO (SyncWorker_2) [supervisor.docker.manager] Stopping homeassistant application
2024-12-18 15:35:11.610 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_nodered closed
2024-12-18 15:35:11.630 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_nodered closed
2024-12-18 15:35:53.048 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning homeassistant application
2024-12-18 15:35:53.589 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse
2024-12-18 15:35:54.223 INFO (MainThread) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/qemux86-64-homeassistant with version 2024.11.2
2024-12-18 15:35:54.223 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
2024-12-18 15:36:22.582 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-12-18 15:36:23.096 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-12-18 15:36:24.354 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='NOT_RUNNING', offline_db_migration=False)
2024-12-18 15:36:48.868 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'homeassistant'
2024-12-18 15:36:48.879 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
2024-12-18 15:36:49.718 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='STARTING', offline_db_migration=False)
2024-12-18 15:36:55.702 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='RUNNING', offline_db_migration=False)
2024-12-18 15:36:55.702 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
2024-12-18 15:36:57.562 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-12-18 15:36:57.581 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
2024-12-18 15:36:57.711 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-12-18 15:36:57.718 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
2024-12-18 15:36:57.873 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-12-18 15:36:58.007 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-12-18 15:37:18.201 INFO (SyncWorker_0) [supervisor.docker.manager] Restarting homeassistant
2024-12-18 15:37:18.742 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-34728' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-12-18 15:37:18.771 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_nodered closed
2024-12-18 15:37:18.781 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_nodered closed
2024-12-18 15:38:02.372 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
2024-12-18 15:38:06.053 INFO (SyncWorker_3) [supervisor.docker.manager] Runing command 'python3 -m homeassistant -c /config --script check_config' on ghcr.io/home-assistant/qemux86-64-homeassistant
2024-12-18 15:38:19.325 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-12-18 15:38:20.773 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-12-18 15:38:22.522 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='NOT_RUNNING', offline_db_migration=False)
2024-12-18 15:38:42.960 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='STARTING', offline_db_migration=False)
2024-12-18 15:38:46.715 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-12-18 15:38:46.729 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
2024-12-18 15:38:46.764 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-12-18 15:38:46.784 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
2024-12-18 15:38:47.204 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-12-18 15:38:47.205 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-12-18 15:38:49.530 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='RUNNING', offline_db_migration=False)
2024-12-18 15:38:49.531 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
2024-12-18 15:39:53.784 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
2024-12-18 15:39:58.628 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.628 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.628 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.629 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.629 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.629 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.629 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.629 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.629 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.629 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.629 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:39:58.630 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)
2024-12-18 15:40:09.701 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
2024-12-18 15:40:09.701 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
2024-12-18 15:47:20.231 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant config is valid
2024-12-18 15:52:35.735 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
2024-12-18 15:52:35.735 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
2024-12-18 15:53:43.470 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-12-18 15:54:53.786 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
2024-12-18 16:05:23.020 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-12-18 16:05:23.138 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-12-18 16:05:23.764 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-12-18 16:07:00.956 INFO (MainThread) [supervisor.core] Starting repair of Supervisor Environment
2024-12-18 16:07:00.957 INFO (SyncWorker_3) [supervisor.docker.manager] Prune stale containers
2024-12-18 16:07:00.967 INFO (SyncWorker_3) [supervisor.docker.manager] Prune stale images
2024-12-18 16:07:20.591 INFO (SyncWorker_3) [supervisor.docker.manager] Prune stale builds
2024-12-18 16:07:20.618 INFO (SyncWorker_3) [supervisor.docker.manager] Prune stale volumes
2024-12-18 16:07:20.634 INFO (SyncWorker_3) [supervisor.docker.manager] Prune stale networks
2024-12-18 16:07:20.649 INFO (SyncWorker_3) [supervisor.docker.manager] Fix stale container on hassio network
2024-12-18 16:07:20.764 INFO (SyncWorker_3) [supervisor.docker.manager] Fix stale container on host network
2024-12-18 16:07:21.006 INFO (MainThread) [supervisor.addons.manager] Found 1 add-ons to repair
2024-12-18 16:07:21.006 INFO (MainThread) [supervisor.addons.manager] Repairing for add-on: 45df7312_zigbee2mqtt
2024-12-18 16:07:21.007 INFO (MainThread) [supervisor.docker.interface] Downloading docker image zigbee2mqtt/zigbee2mqtt-amd64 with tag 1.41.0-1.
2024-12-18 16:07:22.421 INFO (MainThread) [supervisor.supervisor] Repairing Supervisor 2024.12.0
2024-12-18 16:07:22.513 INFO (MainThread) [supervisor.core] Finished repair of Supervisor Environment
2024-12-18 16:07:34.602 INFO (SyncWorker_3) [supervisor.docker.manager] Restarting homeassistant
2024-12-18 16:07:34.806 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_nodered closed
2024-12-18 16:07:34.816 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_nodered closed
2024-12-18 16:07:47.031 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
root@HA:~# ^C
