### ISSUE TITLE
Cannot shutdown Home Assistant Green gracefully

### ISSUE THREAD

**Issue by jhol-byte** [home-assistant/supervisor#5516]
### Describe the issue you are experiencing

I wanted to restart my Home Assistant Green device (complete system restart) which didn't work as I lost connection to HA but connection didn't come back. After hard re-start I checked if I can gracefully shutdown the complete system with the result that the device didn't turn off, the shutdown could not finish successfully. Again I had to do a hard re-start to retrieve the logs, see details below.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Go to "Restart Home Assistant" and choose "Shutdown system"
2. Wait and have a look at the "Home Assistant Green" system LEDs
3. Connection from App not possible any longer -> this is expected
4. LEDs don't go off for several minutes, meaning shutdown doesn't finish completely -> this is **not** expected
5. press hardware button of "Home Assistant Green" for 12 sec to do a hard shutdown
6. power on again and retrieve supervisor log, see below

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-12-30 15:26:40.274 INFO (MainThread) [supervisor.host.control] Initialize host power off logind
2024-12-30 15:26:40.277 INFO (MainThread) [supervisor.addons.manager] Phase 'application' stopping 5 add-ons
2024-12-30 15:26:40.295 INFO (SyncWorker_7) [supervisor.docker.manager] Stopping addon_core_configurator application
2024-12-30 15:26:44.017 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_core_configurator application
2024-12-30 15:26:44.085 INFO (SyncWorker_3) [supervisor.docker.manager] Stopping addon_a0d7b954_sqlite-web application
2024-12-30 15:26:47.972 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning addon_a0d7b954_sqlite-web application
2024-12-30 15:26:48.038 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping addon_core_nginx_proxy application
2024-12-30 15:26:52.156 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_core_nginx_proxy application
2024-12-30 15:26:52.217 INFO (SyncWorker_5) [supervisor.docker.manager] Stopping addon_424ccef4_crowdsec application
2024-12-30 15:26:55.783 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_424ccef4_crowdsec application
2024-12-30 15:26:55.847 INFO (SyncWorker_7) [supervisor.docker.manager] Stopping addon_424ccef4_crowdsec-firewall-bouncer application
2024-12-30 15:27:19.921 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_424ccef4_crowdsec-firewall-bouncer application
2024-12-30 15:27:31.974 INFO (SyncWorker_2) [supervisor.docker.manager] Stopping homeassistant application
2024-12-30 15:28:05.966 INFO (MainThread) [supervisor.addons.manager] Phase 'services' stopping 3 add-ons
2024-12-30 15:28:05.981 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping addon_core_openthread_border_router application
2024-12-30 15:28:30.057 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_core_openthread_border_router application
2024-12-30 15:28:42.111 INFO (SyncWorker_0) [supervisor.docker.manager] Stopping addon_core_matter_server application
2024-12-30 15:29:06.181 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-12-30 15:29:18.235 INFO (SyncWorker_6) [supervisor.docker.manager] Stopping addon_core_ssh application
[31m2024-12-30 15:36:52.402 ERROR (MainThread) [supervisor.api] Failed to get supervisor logs using advanced_logs API
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_proto.py", line 92, in connection_lost
    uncompleted = self._parser.feed_eof()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 508, in aiohttp._http_parser.HttpParser.feed_eof
aiohttp.http_exceptions.TransferEncodingError: 400, message:
  Not enough data for satisfy transfer length header.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/__init__.py", line 403, in get_supervisor_logs
    return await self._api_host.advanced_logs_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/host.py", line 257, in advanced_logs_handler
    async for cursor, line in journal_logs_reader(resp, log_formatter):
  File "/usr/src/supervisor/supervisor/utils/systemd_journal.py", line 80, in journal_logs_reader
    line = await resp.content.readuntil(b"\n")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 383, in readuntil
    await self._wait("readuntil")
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 344, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
s6-rc: info: service legacy-services: stopping
2024-12-30 15:36:53.002 INFO (MainThread) [supervisor.misc.scheduler] Shutting down scheduled tasks
2024-12-30 15:36:53.006 INFO (MainThread) [supervisor.docker.monitor] Stopped docker events monitor
[14:36:53] INFO: Watchdog restart after closing
2024-12-30 15:36:58.013 INFO (MainThread) [supervisor.api] Stopping API on 172.30.32.2
2024-12-30 15:36:58.022 INFO (MainThread) [supervisor.hardware.monitor] Stopped Supervisor hardware monitor
2024-12-30 15:36:58.034 INFO (MainThread) [supervisor.dbus.manager] Closed conection to system D-Bus.
2024-12-30 15:36:58.040 INFO (MainThread) [supervisor.core] Supervisor is down - 0
2024-12-30 15:36:58.044 INFO (MainThread) [__main__] Closing Supervisor
s6-svwait: fatal: timed out
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/udev.sh
[14:39:09] INFO: Using udev information from host
cont-init: info: /etc/cont-init.d/udev.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun supervisor (no readiness notification)
services-up: info: copying legacy longrun watchdog (no readiness notification)
s6-rc: info: service legacy-services successfully started
[14:39:09] INFO: Starting local supervisor watchdog...
2024-12-30 14:39:14.409 INFO (MainThread) [__main__] Initializing Supervisor setup
2024-12-30 14:39:14.662 INFO (MainThread) [supervisor.utils.sentry] Initializing Supervisor Sentry
2024-12-30 15:39:14.684 INFO (MainThread) [supervisor.bootstrap] Setting up coresys for machine: green
2024-12-30 15:39:14.700 INFO (MainThread) [supervisor.docker.supervisor] Attaching to Supervisor ghcr.io/home-assistant/aarch64-hassio-supervisor with version 2024.12.0
2024-12-30 15:39:14.748 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state initialize
2024-12-30 15:39:14.755 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-12-30 15:39:14.757 INFO (MainThread) [__main__] Setting up Supervisor
2024-12-30 15:39:14.927 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
2024-12-30 15:39:15.199 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
2024-12-30 15:39:15.208 INFO (MainThread) [supervisor.dbus.manager] Connected to system D-Bus.
2024-12-30 15:39:15.209 INFO (MainThread) [supervisor.dbus.agent] Load dbus interface io.hass.os
2024-12-30 15:39:15.211 INFO (MainThread) [supervisor.dbus.hostname] Load dbus interface org.freedesktop.hostname1
2024-12-30 15:39:15.214 INFO (MainThread) [supervisor.dbus.logind] Load dbus interface org.freedesktop.login1
2024-12-30 15:39:15.216 INFO (MainThread) [supervisor.dbus.network] Load dbus interface org.freedesktop.NetworkManager
2024-12-30 15:39:15.218 INFO (MainThread) [supervisor.dbus.rauc] Load dbus interface de.pengutronix.rauc
2024-12-30 15:39:15.221 INFO (MainThread) [supervisor.dbus.resolved] Load dbus interface org.freedesktop.resolve1
2024-12-30 15:39:15.223 INFO (MainThread) [supervisor.dbus.systemd] Load dbus interface org.freedesktop.systemd1
2024-12-30 15:39:15.225 INFO (MainThread) [supervisor.dbus.timedate] Load dbus interface org.freedesktop.timedate1
2024-12-30 15:39:15.798 INFO (MainThread) [supervisor.host.services] Updating service information
2024-12-30 15:39:16.005 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
[33m2024-12-30 15:39:16.018 WARNING (SyncWorker_0) [supervisor.host.sound] Can't update PulseAudio data: Failed to connect to pulseaudio server
2024-12-30 15:39:16.352 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-12-30 15:39:16.478 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
2024-12-30 15:39:16.501 INFO (MainThread) [supervisor.mounts.manager] Initializing all user-configured mounts
2024-12-30 15:39:17.611 INFO (MainThread) [supervisor.docker.monitor] Started docker events monitor
2024-12-30 15:39:17.613 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-12-30 15:39:17.719 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-cli with version 2024.09.0
2024-12-30 15:39:17.749 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
2024-12-30 15:39:17.766 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning hassio_cli application
2024-12-30 15:39:18.727 INFO (MainThread) [supervisor.docker.cli] Starting CLI ghcr.io/home-assistant/aarch64-hassio-cli with version 2024.09.0 - 172.30.32.5
2024-12-30 15:39:18.771 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-dns with version 2024.12.0
2024-12-30 15:39:18.816 INFO (MainThread) [supervisor.plugins.dns] Starting CoreDNS plugin
2024-12-30 15:39:18.836 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning hassio_dns application
2024-12-30 15:39:19.706 INFO (MainThread) [supervisor.docker.dns] Starting DNS ghcr.io/home-assistant/aarch64-hassio-dns with version 2024.12.0 - 172.30.32.3
2024-12-30 15:39:19.711 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
2024-12-30 15:39:19.739 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-audio with version 2023.12.0
2024-12-30 15:39:19.782 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
2024-12-30 15:39:19.829 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning hassio_audio application
2024-12-30 15:39:20.953 INFO (MainThread) [supervisor.docker.audio] Starting Audio ghcr.io/home-assistant/aarch64-hassio-audio with version 2023.12.0 - 172.30.32.4
2024-12-30 15:39:20.967 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-observer with version 2023.06.0
2024-12-30 15:39:21.011 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-multicast with version 2024.03.0
2024-12-30 15:39:21.040 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin
2024-12-30 15:39:21.059 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning hassio_multicast application
2024-12-30 15:39:21.641 INFO (MainThread) [supervisor.docker.multicast] Starting Multicast ghcr.io/home-assistant/aarch64-hassio-multicast with version 2024.03.0 - Host
2024-12-30 15:39:21.658 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 1 Home Assistant secrets
2024-12-30 15:39:21.692 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/green-homeassistant with version 2024.12.5
2024-12-30 15:39:21.832 INFO (MainThread) [supervisor.os.manager] Detect Home Assistant Operating System 14.1 / BootSlot B
2024-12-30 15:39:23.427 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/5c53de3b repository
2024-12-30 15:39:23.430 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/d5369777 repository
2024-12-30 15:39:23.432 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/424ccef4 repository
2024-12-30 15:39:23.436 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
2024-12-30 15:39:23.442 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
2024-12-30 15:39:23.449 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/cb646a50 repository
2024-12-30 15:39:25.100 INFO (MainThread) [supervisor.store] Loading add-ons from store: 83 all - 83 new - 0 remove
2024-12-30 15:39:25.298 INFO (MainThread) [supervisor.addons.manager] Found 10 installed add-ons
2024-12-30 15:39:25.347 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-matter-server with version 6.6.1
2024-12-30 15:39:25.412 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-configurator with version 5.8.0
2024-12-30 15:39:25.417 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-otbr with version 2.12.2
2024-12-30 15:39:25.423 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-ssh with version 9.16.0
2024-12-30 15:39:25.428 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/hacs/aarch64-addon-get with version 1.3.1
2024-12-30 15:39:25.468 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/sqlite-web/aarch64 with version 4.3.0
2024-12-30 15:39:25.491 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/crowdsecurity/aarch64-addon-crowdsec with version 1.6.4
2024-12-30 15:39:25.494 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-letsencrypt with version 5.2.10
2024-12-30 15:39:25.496 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer with version v0.0.31
2024-12-30 15:39:25.528 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-nginx_proxy with version 3.11.1
2024-12-30 15:39:26.033 INFO (MainThread) [supervisor.backups.manager] Found 16 backup files
2024-12-30 15:39:26.634 INFO (MainThread) [supervisor.discovery] Loaded 2 messages
2024-12-30 15:39:26.635 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
2024-12-30 15:39:26.635 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state setup
2024-12-30 15:39:26.636 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-12-30 15:39:26.637 INFO (MainThread) [supervisor.resolution.checks.base] Run check for detached_addon_removed/addon
2024-12-30 15:39:26.637 INFO (MainThread) [supervisor.resolution.checks.base] Run check for detached_addon_missing/addon
2024-12-30 15:39:26.638 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-12-30 15:39:26.638 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-12-30 15:39:26.638 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state setup
2024-12-30 15:39:26.639 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-12-30 15:39:26.641 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - setup
2024-12-30 15:39:26.647 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state setup
2024-12-30 15:39:26.648 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-12-30 15:39:26.656 INFO (MainThread) [__main__] Running Supervisor
2024-12-30 15:39:26.695 INFO (MainThread) [supervisor.os.manager] Rauc: slot B - activated slot kernel.1, marked slot kernel.1 as good
2024-12-30 15:39:26.727 INFO (MainThread) [supervisor.addons.manager] Phase 'initialize' starting 0 add-ons
2024-12-30 15:39:26.734 INFO (MainThread) [supervisor.addons.manager] Phase 'system' starting 0 add-ons
2024-12-30 15:39:26.735 INFO (MainThread) [supervisor.addons.manager] Phase 'services' starting 3 add-ons
2024-12-30 15:39:26.810 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_core_openthread_border_router application
2024-12-30 15:39:27.307 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-otbr with version 2.12.2
2024-12-30 15:39:27.417 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-12-30 15:39:27.978 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-matter-server with version 6.6.1
2024-12-30 15:39:28.077 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning addon_core_ssh application
2024-12-30 15:39:29.275 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-ssh with version 9.16.0
2024-12-30 15:39:34.296 INFO (MainThread) [supervisor.core] Start Home Assistant Core
2024-12-30 15:39:34.356 INFO (SyncWorker_0) [supervisor.docker.manager] Starting homeassistant
2024-12-30 15:39:34.777 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
2024-12-30 15:39:44.032 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_matter_server
2024-12-30 15:39:47.565 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_openthread_border_router
2024-12-30 15:39:54.379 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state startup
2024-12-30 15:39:54.380 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-12-30 15:39:54.898 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-12-30 15:39:54.915 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='NOT_RUNNING', offline_db_migration=False)
2024-12-30 15:40:00.653 INFO (MainThread) [supervisor.discovery] Sending discovery to Home Assistant otbr from core_openthread_border_router
2024-12-30 15:40:00.687 INFO (MainThread) [supervisor.discovery] Discovery c6a91e6cfff6452c9f6967f5698725c6 message ignore
2024-12-30 15:40:52.407 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='RUNNING', offline_db_migration=False)
2024-12-30 15:40:52.408 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
2024-12-30 15:40:52.410 INFO (MainThread) [supervisor.addons.manager] Phase 'application' starting 5 add-ons
2024-12-30 15:40:53.518 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-configurator with version 5.8.0
2024-12-30 15:40:54.747 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/sqlite-web/aarch64 with version 4.3.0
2024-12-30 15:40:56.489 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-nginx_proxy with version 3.11.1
2024-12-30 15:40:57.207 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_nginx_proxy
2024-12-30 15:40:58.216 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/crowdsecurity/aarch64-addon-crowdsec with version 1.6.4
2024-12-30 15:40:58.352 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_424ccef4_crowdsec-firewall-bouncer application
2024-12-30 15:40:59.319 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/crowdsecurity/aarch64-addon-crowdsec-firewall-bouncer with version v0.0.31
2024-12-30 15:41:23.814 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
2024-12-30 15:41:23.817 INFO (MainThread) [supervisor.core] Supervisor is up and running
2024-12-30 15:41:23.818 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-12-30 15:41:23.821 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-12-30 15:41:23.824 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-12-30 15:41:23.825 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-12-30 15:41:23.827 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
2024-12-30 15:41:23.828 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-12-30 15:41:23.831 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-12-30 15:41:23.875 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-12-30 15:41:23.917 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-12-30 15:41:23.953 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-12-30 15:41:23.963 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-12-30 15:41:23.964 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-12-30 15:41:23.965 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-12-30 15:41:23.966 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-12-30 15:41:23.966 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-12-30 15:41:23.967 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-12-30 15:41:25.282 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-12-30 15:41:25.284 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-12-30 15:41:25.285 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-12-30 15:41:25.474 INFO (MainThread) [supervisor.host.services] Updating service information
2024-12-30 15:41:25.493 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-12-30 15:41:25.838 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-12-30 15:41:25.868 INFO (MainThread) [supervisor.host.manager] Host information reload completed
```

## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.66-haos
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1493
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 27.8 GB
disk_used | 7.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | green
supervisor_api | ok
version_api | ok
installed_addons | OpenThread Border Router (2.12.2), Matter Server (6.6.1), File editor (5.8.0), SQLite Web (4.3.0), Terminal & SSH (9.16.0), Get HACS (1.3.1), Let's Encrypt (5.2.10), NGINX Home Assistant SSL proxy (3.11.1), Crowdsec (1.6.4), Crowdsec Firewall Bouncer (v0.0.31)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 6
views | 24
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23. November 2024 um 12:36
-- | --
current_recorder_run | 30. Dezember 2024 um 15:39
estimated_db_size | 75.41 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Supervisor diagnostics

[config_entry-hassio-01J7DPFZAJRRNRZWNH189GDHBT.json](https://github.com/user-attachments/files/18275604/config_entry-hassio-01J7DPFZAJRRNRZWNH189GDHBT.json)

**Comment by agners** [comment]
I guess you are worried about this error in particular?
```
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
```

This probably happened because you were looking at the (live) logs during shutdown. It seems there is a situation where logs are just incomming, when the system starts to shutdown, raising that error. It is not really concerning though.

@sairon maybe we need to think about how to cleanly shutdown the advanced logging to prevent such exceptions :thinking:

**Comment by jhol-byte** [comment]
Hi, my problem is not about what is in the log (I only thought it would help to find the root cause), but that I literally cannot shutdown my system, it just won't turn off.

**Comment by nathang21** [comment]
I'm having a similar issue on my Home Assistant Blue, I am also unable to restart gracefully without forcibly killing the power. 

The supervisor initiates the shutdown process as expected, but get stuck seemingly shutting down the addons, however the logs all stop at some point so it's hard to know what to trust.

Core itself does not appear to be shutdown, as I can still access my Core instance via Nabu Casa cloud & localhost, but most of the admin pages (along with the CLI) return errors related to system is in state shutdown, or supervisor not loaded. 

Here is all I could grab from the Supervisor logs before it handed:

```
2025-01-09 20:08:37.631 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs/follow access from a0d7b954_ssh
2025-01-09 20:08:53.975 INFO (MainThread) [supervisor.api.middleware.security] /host/options access from a0d7b954_ssh
2025-01-09 20:08:57.986 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh
2025-01-09 20:09:06.220 INFO (MainThread) [supervisor.api.middleware.security] /host/reboot access from a0d7b954_ssh
2025-01-09 20:09:06.227 INFO (MainThread) [supervisor.host.control] Initialize host reboot using logind
2025-01-09 20:09:06.229 INFO (MainThread) [supervisor.addons.manager] Phase 'application' stopping 9 add-ons
2025-01-09 20:09:06.258 INFO (SyncWorker_3) [supervisor.docker.manager] Stopping addon_cebe7a76_hassio_google_drive_backup application
2025-01-09 20:09:07.344 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning addon_cebe7a76_hassio_google_drive_backup application
2025-01-09 20:09:07.439 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping addon_db21ed7f_filebrowser application
2025-01-09 20:09:07.786 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_db21ed7f_filebrowser application
2025-01-09 20:09:07.834 INFO (SyncWorker_9) [supervisor.docker.manager] Stopping addon_45df7312_zigbee2mqtt application
2025-01-09 20:09:17.239 INFO (SyncWorker_9) [supervisor.docker.manager] Cleaning addon_45df7312_zigbee2mqtt application
2025-01-09 20:09:17.270 INFO (SyncWorker_6) [supervisor.docker.manager] Stopping addon_9b13b3f4_rtl433 application
2025-01-09 20:09:21.711 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_9b13b3f4_rtl433 application
2025-01-09 20:09:21.782 INFO (SyncWorker_5) [supervisor.docker.manager] Stopping addon_d4d25933_tailscale application
2025-01-09 20:09:26.025 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_d4d25933_tailscale application
2025-01-09 20:09:26.097 INFO (SyncWorker_3) [supervisor.docker.manager] Stopping addon_db21ed7f_sponsorblockcast application
2025-01-09 20:09:36.256 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning addon_db21ed7f_sponsorblockcast application
2025-01-09 20:09:36.302 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping addon_424ccef4_crowdsec application
2025-01-09 20:09:39.772 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_424ccef4_crowdsec application
2025-01-09 20:09:39.828 INFO (SyncWorker_9) [supervisor.docker.manager] Stopping addon_424ccef4_crowdsec-firewall-bouncer application
2025-01-09 20:10:03.880 INFO (SyncWorker_9) [supervisor.docker.manager] Cleaning addon_424ccef4_crowdsec-firewall-bouncer application
2025-01-09 20:10:15.922 INFO (SyncWorker_6) [supervisor.docker.manager] Stopping addon_6a9d607a_beszel_agent_dev application
```

**Comment by jhol-byte** [comment]
Today I wanted to update to HA Operating System 14.2. As this tries to do a complete automatic restart, my system was stuck again and I had to do a hard power off/on manually.

**Comment by jhol-byte** [comment]
I don't know what exactly changed, but complete shutdown or complete restart work again. 

My current setup:

## System Information

version | core-2025.1.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.1
os_name | Linux
os_version | 6.6.73-haos
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.5
Stage | running
Available Repositories | 1511
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 27.8 GB
disk_used | 7.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | green
supervisor_api | ok
version_api | ok
installed_addons | OpenThread Border Router (2.13.0), Matter Server (7.0.0), File editor (5.8.0), SQLite Web (4.3.0), Terminal & SSH (9.16.0), Let's Encrypt (5.2.10), NGINX Home Assistant SSL proxy (3.11.1), Crowdsec (1.6.4), Crowdsec Firewall Bouncer (v0.0.31)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 7
views | 27
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30. Dezember 2024 um 14:39
-- | --
current_recorder_run | 2. Februar 2025 um 13:11
estimated_db_size | 84.61 MiB
database_engine | sqlite
database_version | 3.47.1

</details>
